### ISSUE TITLE
Simple way to handle update internal flow via our own script?

### ISSUE THREAD

**Issue by RichardHubertPtw** [Azure/iot-hub-device-update#107]
Hi, we're big fans of ADU ... and we have a requirement that we could handle by writing a custom handler based on the src. However, I suspect that we may be able to somehow download a (signed) script and execute it using the existing ADU handlers? I see, for example, that the adu-agent calls a shell script. We'd like to download and call our own shell script to handle complex internals of our installation. Is there a way to do this already, or should we write our own handler to call our shell script? Thanks for a tip.

**Comment by alancshi** [comment]
Hi, as you point out this isn't supported out-of-the-box with the reference agent, although it is certainly possible to do it exactly as you suggest (with a customer handler type). Is your main concern running of a script, or specifically verifying and running a signed script?

**Comment by Nox-MSFT** [comment]
Hi @RichardHubertPtw ,  please checkout Script Handler https://github.com/Azure/iot-hub-device-update/tree/main/src/content_handlers/script_handler

**Comment by jw-msft** [comment]
To elaborate a bit more, the newly released [0.8.0 agent](https://github.com/Azure/iot-hub-device-update/commit/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9) supports an update type of **microsoft/script:1**.

Upon download, the agent would verify the hash of the script payload just like any other update payload. These hashes come from the Microsoft-signed update metadata so the hashes would not be tampered with.

Once the agent does the hash check on the script file, the script is executed via [the script handler](https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/src/content_handlers/script_handler/src/script_handler.cpp).

Would this work for your needs, or are the scripts already signed and you need to verify it?

**Comment by RichardHubertPtw** [comment]
The script handler is an interesting improvement. We had to reduce the dependency on ADU since this feature didn't exist. So, we'll now look again. Preventing tampering is a must, so good that you do that. Medical compliance requires that artifacts are end-to-end traceable, so we normally sign everything. However, this script is not actually the installed artifact, so could be ok as is. Thanks again, great feature!

**Comment by RichardHubertPtw** [comment]
This is a big help, thanks! 
https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/update-manifest-v4-schema.md

**Comment by RichardHubertPtw** [comment]
Hi, all I can report for you at the moment is that we are working with the script handler feature and -- up to now -- making good progress. It is a "killer" feature in ADU. I've signaled your query to persons who may be able to help with your explicit problem...
