### ISSUE TITLE
Connect Adu-Client to Azure by using dps with x509 certs

### ISSUE THREAD

**Issue by TK-FS** [Azure/iot-hub-device-update#111]
Hello,

I have registered my IoT device with the Device Provisioning Service to IoT Hub and now I want to connect the Adu-Client with Azure.
The registration was done with X509 certificates, so I want ask, how I can connect the Adu-Client with Azure by using the X509 certificates.
By the way, I have found a solution [here ](https://github.com/Azure/iot-hub-device-update/issues/48)approach, but I have not understand how I can implement it. 
Would it be possible to introduce me to this approach to be able to implement it?
Thanks in advance.

**Comment by Pan5ky** [comment]
Did you mange to connect via x509 certs? I'm having the same issue.
