### ISSUE TITLE
Maximum size for OTA Firmware file 

### ISSUE THREAD

**Issue by GauravChoube** [Azure/iot-hub-device-update#112]
Hi,
I want to know limitation about size of file that can be import for OTA process which is updated Firmware in swu file.
My Requirement is used a large file about 5 GB for OTA update.

Does current implementation if DU service support the 5GB size of file for OTA update.

Regards
Gaurav Choubey

**Comment by devlie** [comment]
Hi @GauravChoube, sorry, the largest file size we currently support is 2 GB. Please refer to [this](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-limits) for the limits.

**Comment by devlie** [comment]
If you don't mind sharing, what kind of device requires such a large firmware?

**Comment by GauravChoube** [comment]
Thanks for reply @devlie 
our client want to update hub kind of system which has file size about 5GB.
