### ISSUE TITLE
unnecessary update to the same version

### ISSUE THREAD

**Issue by JanZachmann** [Azure/iot-hub-device-update#114]
Hi ADU Team

In our scenario we continuously build new yocto based linux firmware images, with adu agent configured to that latest version. Later on, the newest available version of the image is flashed to the device in a factory environment. In parallel to building the firmware, we also create and import an update of the same version into adu and create a deployment respectively.

We experienced that after the device was successfully provisioned and is visible in iothub for the first time, an update to the same version is offered by iothub. This is a bug in our opinion since there is no need for updating in that case.

Regards
Jan

**Comment by alancshi** [comment]
Hi Jan, if I understand the scenario, I think you are saying that you may have devices already using the latest version of your image/update, however in the ADU console, it shows you the ADU update for that version is still applicable to your device (and that it is out of compliance?).

There are actually two versions here: the version of your image itself, and the version of the ADU update that contains that image. The latter is the version number ADU uses to understand what is on the device (and that ADU update is 'currency' that's used to describe updates everywhere in ADU, starting from when you import it).

I can confirm that today that unless you have previously used ADU to deploy the update specifically to the device, ADU is unaware of what version is on the device, but after the update is deployed it should appear properly in the dashboard. There are conceivably ways in which the ADU update identity can be embedded inside the images themselves so this "bootstrapping" scenario can avoid reporting that an update is needed unnecessarily, but don't yet have that capability.

**Comment by JanZachmann** [comment]
@alancshi  thanks for your answer. you got me correct - we produce devices with a flashed firmware image version that we also provide as adu update (in order to update older devices that are already in the field). unnecessarily the adu console also provides this update to devices which have been already produced with this same version.

If I understand your answer correctly, adu determines, if to provide an update, by an "adu update version" and not by the sw version. Can we see this update version somewhere in iothub? Is it returned when importing an update or at time of deployment creation? Where can we see this version after an update on the device (adu agent)? I assume in our CI/CD environment we need to:

1. build the firmware image
2. create and import the adu update into iothub and get the update version
2. add this version to the adu agent in our flash image
3. flash the device with this image in our production

BR
Jan

**Comment by alancshi** [comment]
Hi @JanZachmann , yes you understood this correctly. The ADU update version is the version that is specified in the import manifest (which you used to upload the content to the ADU in the first place). The identity specified in that import manifest is the "currency" that ADU uses throughout the system to determine what to install (so you can think of it as an abstraction that embodies identity of the update, regardless of what update technology is being used--swupdate, apt, etc). You can see this identity in the import manifest JSON as the "updateId" property (and it contains three elements: provider, name, version).

In the portal, you can see the the updates you imported in the Updates pane (these are the updates available to send to devices). If you have devices that match those updates, you can see that in the "groups" pane (the details view also shows you what ADU thinks it has installed on those devices).

As for figuring out what version ADU thinks is installed on the device, you can see this in the device twin for the device (I believe it is the installedUpdateId property). I'm am not 100% sure if the agent persists this version inside the device itself, though. @Jerry-GeGarcia , do you know?

**Comment by jw-msft** [comment]
For the swupdate image updates, the reference agent looks at [/etc/adu-version](https://github.com/Azure/iot-hub-device-update/search?q=ADUC_VERSION_FILE), which would be baked into the image.
For apt package updates, it looks at [/var/lib/adu/installedcriteria](https://github.com/Azure/iot-hub-device-update/search?q=ADUC_INSTALLEDCRITERIA_FILE_PATH)

**Comment by JanZachmann** [comment]
Hi again. I spent some time meanwhile with looking into the adu-agent code and studying the logs of my RPI4. For me it seems that the agents workflow never triggers reporting "installedUpdateId" to adu twin on first boot of a flashed device. After I apply the update of the same version everything seems like expected. 
Can you please have a look into the log files attached:
**adu-agent logs and adu-agent twin after first start of freshly flashed device:**
[adu-agent-fresh-device.log](https://github.com/Azure/iot-hub-device-update/files/7911702/adu-agent-fresh-device.log)
[adu-agent-twin-fresh-device.log](https://github.com/Azure/iot-hub-device-update/files/7911711/adu-agent-twin-fresh-device.log)

**adu-agent logs and adu-agent twin after update of the same version was applied and installed:**
[adu-agent-after-initial-update.log](https://github.com/Azure/iot-hub-device-update/files/7911723/adu-agent-after-initial-update.log)
[adu-agent-twin-after-initial-update.log](https://github.com/Azure/iot-hub-device-update/files/7911726/adu-agent-twin-after-initial-update.log)

Thanks
Jan

**Comment by jw-msft** [comment]
So, in the first log (adu-agent-fresh-device.log), you mentioned that it is needlessly processing the update the first time and that is what was the bootstrapping issue that was mentioned earlier, where it will ask the agent to process the update.  For this, I noticed in the log that `SWUpdateHandlerImp::IsInstalled()` was not being called via
```c
ADUC_Workflow_HandleStartupWorkflowData  -> ADUC_MethodCall_IsInstalled
```
Instead it is proceeding straight into downloading. Was the code modified perhaps?

In the reference swupdate handler, to determine if the update is installed or not, it compares the contents of `/etc/adu-version` with the Criteria String that was in the import manifest.
If they match, then the agent considers the the update as installed; otherwise, if there's a mismatch OR /etc/adu-version doesn't exist, then the update is considered **not** installed.

However, in the log, I saw something like that but it was called `/etc/sw-versions`.
```
Jan 21 08:28:29 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:28:28.9716Z [I] read os name "***sanitized***" from /etc/sw-versions [DeviceInfo_GetOsName]
```

Ok, so now going into the question about why it's not reporting the "installedUpdateId" on the first boot:

In the first set of logs, I see that the agent reported InstallSucceeded(4) and it was able to PATCH the twin, but the twin you provided shows state as 0, which means Idle state:
```
Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7534Z [I] Action 'Install' complete. Result: 1, 0 [ADUC_Workflow_WorkCompletionCallback]
Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7534Z [I] WorkCompletionCallback: Install succeeded. Going to state InstallSucceeded [ADUC_Workflow_WorkCompletionCallback]
Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7534Z [I] Setting UpdateState to InstallSucceeded [ADUC_SetUpdateStateHelper]
Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7535Z [I] Reporting state: InstallSucceeded (4) [AzureDeviceUpdateCoreInterface_ReportStateAndResultAsync]
Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: -> 08:36:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=11 | PAYLOAD_LEN: 59
Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: <- 08:36:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/res/204/?$rid=11&$version=8 | PAYLOAD_LEN: 0
Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: <- 08:36:40 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=4 | PAYLOAD_LEN: 3024
```

However, the twin should have in it reported state of `4 (InstallSucceeded)` instead of `0 (Idle)`.
This suggests that the backend either did not receive or successfully process the twin change notification.
That would then explain why the cloud-based orchestration (CBO) did not issue an Apply action in the twin. I will talk to someone tomorrow in the backend to see if we are able to determine what happened here.


In the 2nd set of logs, I see the Apply(2) action and see it reporting the installedUpdateId after successful apply, which aligns with what was mentioned about applying the update after the first boot seems to make things work as expected:
```
Jan 21 08:37:25 raspberrypi4-64 AducIotAgent[652]: 2022-01-21T08:37:25.1601Z [I] IsInstalled call was true - setting installedUpdateId to ***sanitized*** and setting state
 to Idle [ADUC_Workflow_HandleStartupWorkflowData]
Jan 21 08:37:25 raspberrypi4-64 AducIotAgent[652]: 2022-01-21T08:37:25.1601Z [I] Reporting state: Idle (0); UpdateId ***sanitized*** [AzureDeviceUpdateCoreInterface_Report
UpdateIdAndIdleAsync]
```

and it patched the twin
```
Jan 21 08:37:25 raspberrypi4-64 AducIotAgent[652]: -> 08:37:25 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=5 | PAYLOAD_LEN: 
217
```

**Comment by JanZachmann** [comment]
> So, in the first log (adu-agent-fresh-device.log), you mentioned that it is needlessly processing the update the first time and that is what was the bootstrapping issue that was mentioned earlier, where it will ask the agent to process the update. For this, I noticed in the log that `SWUpdateHandlerImp::IsInstalled()` was not being called via
> 
> ```c
> ADUC_Workflow_HandleStartupWorkflowData  -> ADUC_MethodCall_IsInstalled
> ```
> 
> Instead it is proceeding straight into downloading. Was the code modified perhaps?
> 
> In the reference swupdate handler, to determine if the update is installed or not, it compares the contents of `/etc/adu-version` with the Criteria String that was in the import manifest. If they match, then the agent considers the the update as installed; otherwise, if there's a mismatch OR /etc/adu-version doesn't exist, then the update is considered **not** installed.
> 
> However, in the log, I saw something like that but it was called `/etc/sw-versions`.
> 
> ```
> Jan 21 08:28:29 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:28:28.9716Z [I] read os name "***sanitized***" from /etc/sw-versions [DeviceInfo_GetOsName]
> ```
> 
> Ok, so now going into the question about why it's not reporting the "installedUpdateId" on the first boot:
> 
> In the first set of logs, I see that the agent reported InstallSucceeded(4) and it was able to PATCH the twin, but the twin you provided shows state as 0, which means Idle state:
> 
> ```
> Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7534Z [I] Action 'Install' complete. Result: 1, 0 [ADUC_Workflow_WorkCompletionCallback]
> Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7534Z [I] WorkCompletionCallback: Install succeeded. Going to state InstallSucceeded [ADUC_Workflow_WorkCompletionCallback]
> Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7534Z [I] Setting UpdateState to InstallSucceeded [ADUC_SetUpdateStateHelper]
> Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: 2022-01-21T08:36:36.7535Z [I] Reporting state: InstallSucceeded (4) [AzureDeviceUpdateCoreInterface_ReportStateAndResultAsync]
> Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: -> 08:36:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=11 | PAYLOAD_LEN: 59
> Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: <- 08:36:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/res/204/?$rid=11&$version=8 | PAYLOAD_LEN: 0
> Jan 21 08:36:40 raspberrypi4-64 AducIotAgent[1820]: <- 08:36:40 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=4 | PAYLOAD_LEN: 3024
> ```
> 
> However, the twin should have in it reported state of `4 (InstallSucceeded)` instead of `0 (Idle)`. This suggests that the backend either did not receive or successfully process the twin change notification. That would then explain why the cloud-based orchestration (CBO) did not issue an Apply action in the twin. I will talk to someone tomorrow in the backend to see if we are able to determine what happened here.
> 
> In the 2nd set of logs, I see the Apply(2) action and see it reporting the installedUpdateId after successful apply, which aligns with what was mentioned about applying the update after the first boot seems to make things work as expected:
> 
> ```
> Jan 21 08:37:25 raspberrypi4-64 AducIotAgent[652]: 2022-01-21T08:37:25.1601Z [I] IsInstalled call was true - setting installedUpdateId to ***sanitized*** and setting state
>  to Idle [ADUC_Workflow_HandleStartupWorkflowData]
> Jan 21 08:37:25 raspberrypi4-64 AducIotAgent[652]: 2022-01-21T08:37:25.1601Z [I] Reporting state: Idle (0); UpdateId ***sanitized*** [AzureDeviceUpdateCoreInterface_Report
> UpdateIdAndIdleAsync]
> ```
> 
> and it patched the twin
> 
> ```
> Jan 21 08:37:25 raspberrypi4-64 AducIotAgent[652]: -> 08:37:25 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=5 | PAYLOAD_LEN: 
> 217
> ```

Thanks for your support. With 0.8.0 we could see that there is no update with the same version anymore since orchestration was moved to device.
