### ISSUE TITLE
RPI tryboot?

### ISSUE THREAD

**Issue by wasabii** [Azure/iot-hub-device-update#115]
I am trying to get ADU to work properly with the new Raspberry PI 'tryboot' support.

`adu-swupdate.sh` has an 'apply' command, which use `fw_setenv rpipart` to switch to the active partition. When using tryboot, instead of using a boot.scr script to select the partition, we run `reboot 'N tryboot'` to initiate a reboot using a secondary tryboot.txt file. Basically, there really doesnt' need to be a separate 'apply' step. Instead, we need to reboot with a specific command.

The command to reboot appears to be hard coded into the ADU agent.

It would make sense to me if the ADU agent was updated to call `adu-swupdate.sh reboot`, and a new 'reboot' command was added to that script. This way, we could edit that script in the case of tryboot. For the tryboot case, the 'apply' command would simply be a noop, and the reboot command would initiate tryboot.

Potentially, having the operations of adu-swupdate.sh configurable in some fashion would be nice. However, it would be fine for me to just replace this file with my own.

**Comment by Nox-MSFT** [comment]
@wasabii, thank you for the feedback & idea! I'll doing some investigation and incorporate that in the plan for upcoming SWUpdate Handler improvements.

**Comment by timg236** [comment]
We've just added some enhancements to tryboot/autoboot.txt that hopefully make swupdate integration easier. Feel free to raise a firmware bug if that's not the case :)

https://www.raspberrypi.com/documentation/computers/config_txt.html#autoboot-txt
