### ISSUE TITLE
Support for multiple package update using apt-handler

### ISSUE THREAD

**Issue by gc-zoetis** [Azure/iot-hub-device-update#116]
Hi,
I have some question for package based update using apt-handler.
Current adu-agent only support signal package update and seem like does not has code for multiple package.

My question for some custom development as follow
1. I have saw some document for manifest file where its has zip file mentioned in it. Can we used zip file which contain the bunch of package and import the place of apt-manifest file? Does adu-agent code has part for handling zip file ? if no , can we do it above approach?
2. Does adu-agent code has logic for handling and installing multiple package file for apt-update ? IF logic there, how can it be used in adu-agent code?
3. Does do-agent code support the multiple or list of file download in single call ?
4. If Suppose change the parsing logic of apt-manifest file in adu-agent while downloading action and manually enter the content into variable that parsing function suppose to do, will is it affect flow of agent ? What will be consequence ?

Any help will be appreciated!
regards

**Comment by alancshi** [comment]
There is no native support in the reference agent source code to do the things you mention, although it is certainly possible to augment this code to do these things. You could create an ADU update with your own updateType (which specifies which handler should be used in the agent to support it). That updateType could be something that tells your agent that it is a zip file and what to expect inside, so you know how to install it.

As long as the agent adheres to the protocol, it will be more or less opaque to the ADU service how many actual files (or packages in your case) get installed. So this means, you could send several packages in a single zip and install all of them via your handler. However, from ADU's perspective it looks like one update (which means if you do install multiple packages, you should be aware they are versioned and bundled as a whole).

I couldn't follow the details of what you had in mind for #4, although you are free to modify the agent to change the download or other logic, so long as the overall protocol is still honoured.

**Comment by jw-msft** [comment]
The reference agent already supports multiple apt packages in the apt package manifest, where it is an array in the [device update apt manifest schema](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-apt-manifest#schema).

Here is an [example of multiple apt packages in apt manifest](https://github.com/Azure/iot-hub-device-update/tree/main/src/content_handlers/apt_handler#example).

In the code for [apt handler code](https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/src/content_handlers/apt_handler/src/apt_handler.cpp#L287), it loops over each package.

If you want custom handling where you upload zip archives of files to azure blob storage in DeviceUpdate service and then process them in the Agent, then there are 2 options:
1. [Write your own content handler](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-implement-custom-update-handler.md#how-to-implement-a-custom-content-handler-extension), include your own UpdateType in [the import manifest](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/import-concepts#import-manifest), and [register your update handler for that UpdateType](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-implement-custom-update-handler.md#how-to-register-a-content-handler-extension)
2. Modify 0.8.0 agent Script Handler. Link to [Script Handler code](https://github.com/Azure/iot-hub-device-update/blob/main/src/content_handlers/script_handler/src/script_handler.cpp)
