### ISSUE TITLE
Fix the need to re-trigger twinChangeEvents of ADUGroup to devicetwin  

### ISSUE THREAD

**Issue by SaraOlsson** [Azure/iot-hub-device-update#117]
### Expected behavior

Order of setting ADUGroup tag and receiving reported ADU properties should not affect whether the device appears in 
the list of Create group/is automatically added to an already existing group.

### Actual behavior

Not all devices are added to the ADU group, even though they have both ADUGroup tag and reported properties from adu-agent.

Example: having 5 devices with the same ADUGroup tag, only 3 were added to the Group under IoT Hub Updates. For the other two devices, the tag had to be changed to something else and then back to the actual value to trigger a twinChangeEvent. Thereafter, the devices were added to the group.

### Suggested

Please make the ADUGroup tag take effect without having to re-trigger a twinChangeEvent.

related to issue #76

**Comment by jw-msft** [comment]
Is this for the 0.7.0 agent? For the 0.8.0 agent there was work done to fix some related issues surrounding this. @josephmsft Could you confirm?

@SaraOlsson For the 2 devices that were not added to the group perhaps they were not connected or had their ADUGroup added before they connected? For those 2, could you try:
* Clearing the ADUGroup tag by setting it to `null` in the twin
* Connect the device e.g. `sudo systemctl restart adu-agent`
* Once status is `connected` in the twin, then add the ADUGroup tag back in

**Comment by josephmsft** [comment]
Yes this scenario was fixed and verified with a 0.8.0 agent (the tags will be detected even if they were set in the twin prior to the Device Update agent connecting to Hub)

**Comment by jw-msft** [comment]
Also, after discussing it with @josephmsft, if these are upgrading from 0.7.0 to 0.8.0, then the 0.7.0 devices should be deleted from iothub, then upgrade the devices to 0.8.0, and then add add the devices to iothub, connect the device, and then change the ADUGroup tag.
