### ISSUE TITLE
Meta adu layer for the 0.8.0 pre-release

### ISSUE THREAD

**Issue by balazoetis** [Azure/iot-hub-device-update#121]
Hello MS DU team,
We are currently working on the migration of the azure device update (adu) agent from 0.7.0 to 0.8.0
As a part of this migration, we need to build the yocto image to include the new version of the adu-agent (0.8.0).
We could not see the meta adu layer as a part of 0.8.0 pre-release.
Could you please advise whether you are working/planning on the release of meta adu-layer as a part of adu-agent pre-release 0.8.0

Many thanks,
Bala

**Comment by jw-msft** [comment]
These may help--
This is similar to issue #101 
Related to #50 
and #79

**Comment by balazoetis** [comment]
Thanks for your reply. Please note that we have meta adu layer for the adu version 0.7.0 But in new version (0.8.0) some diagnostics features are included which uses azure blob storage utility & azure sdk for cpp. We don't have the recipe for those two. we expect these two recipes to be included in the meta adu layer which will support new adu version(0.8.0). Kindly advise.

Many thanks,
Bala

**Comment by SimonSimCity** [comment]
@balazoetis If you (like we) did quite some changes to the original meta layer to have it working with your environment (and yes, there are quite some flaws in it 😓 ) feel free to take a look at our repo which is thought to be a git repository containing the meta layer only.

In its master-branch, we keep up with the meta-layer released as part of this repo. This is also the reason why you can easily track all the changes done on the meta-layer between v0.7.0 and v0.8.0 there: https://github.com/munit-solutions/meta-azure-device-update/commit/7b237fa76d7c34919f074f85af1d36b9b99818a9

We have also branches for the different yocto versions, whereby we currently are focussing on `dunfell`. Take a look at our repo, maybe you'll like it and use it in your project: https://github.com/munit-solutions/meta-azure-device-update

**Comment by eshashah-msft** [comment]
Our Yocto layers published in this repo and will be maintained for our releases: https://github.com/Azure/iot-hub-device-update-yocto
