### ISSUE TITLE
Device specific deployment not visible in the current ADU page in Azure

### ISSUE THREAD

**Issue by Undermyspell** [Azure/iot-hub-device-update#122]
In the old ADU page i could see deployments targeting a single device, for example:  'Device:[mydevice]'.
It is still possible to create such deployments with the ADU api and they also work, they are just not displayed.
Is this feature coming in the future in azure portal or will it be dropped in api as well?

**Comment by josephmsft** [comment]
Deployments targeting individual devices has been removed in the 2021-06-01-preview version of the API.  All deployments are targeted to groups, which are either defined by a tag and device class id (which you can find from the devices you want to include in the group) or by the lack of a tag (automatically created default device class groups).

**Comment by Undermyspell** [comment]
This is unfortunate as I use the JS package @azure/iot-device-update from npm which is still in version 1.0.0 beta1 since March 2021. Seems the package is  using the old API and classes. Are there any plans that this packages gets maintained or do I have to switch to another method for using the latest API version? .net package? Plain rest API?

**Comment by sourabhkrishna** [comment]
So does that mean that we wont be able to do Device Specific deployments with the new ADU release ? If so how do approach this ?

**Comment by josephmsft** [comment]
We should have a new JS package, I'm trying to confirm it was pushed to the same repo as the last one.

In the new ADU release deployments cannot be targeted to individual devices as I mentioned, you must add a tag and then create a group from that tag or use the default group the device will be placed in automatically (if there is no tag).  This should be in the API documentation

https://docs.microsoft.com/en-us/dotnet/api/azure.iot.deviceupdate.devicemanagementclient.createorupdategroupasync?view=azure-dotnet-preview#azure-iot-deviceupdate-devicemanagementclient-createorupdategroupasync(system-string-azure-core-requestcontent-azure-requestcontext)
https://docs.microsoft.com/en-us/dotnet/api/azure.iot.deviceupdate.devicemanagementclient.createorupdatedeploymentasync?view=azure-dotnet-preview#azure-iot-deviceupdate-devicemanagementclient-createorupdatedeploymentasync(system-string-system-string-azure-core-requestcontent-azure-requestcontext)

**Comment by josephmsft** [comment]
The latest JS library is at: https://www.npmjs.com/package/@azure-rest/iot-device-update

We'll update the docs that point to it.
