### ISSUE TITLE
Workflow of deployment status

### ISSUE THREAD

**Issue by AmithaVPadiyar** [Azure/iot-hub-device-update#123]
Where can i find the workflow of deployment status and what happens to new deployment that is created for the device while it has in-progress deployment?

Currently, i tried to create a new deployment for a device while it has an InProgress deployment i.e. 'devicesInProgressCount' being set to 1,  the status of the new deployment had 'devicesAlreadyInDeploymentCount' set to 1. Post successfully completing the In-progress deployment, the new deployment that was created didn't move to InProgress and there was no change in the status.

**Comment by josephmsft** [comment]
In the prior preview release for Device Update, the devices in a deployment would be snapshotted at the time the deployment was created, and if a device was already in another deployment it would not receive the new deployment but would be marked as "AlreadyInDeployment".  In the latest preview release, deployments are now dynamic and devices will move to the latest deployment.  https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-deployments

**Comment by esha0611** [comment]
Hi @AmithaVPadiyar, closing this issue as answered. Please feel free to reopen if there are any other questions.
