### ISSUE TITLE
[0.8.0] Yocto meta layer changes permission of folder twice ... wrong variable?

### ISSUE THREAD

**Issue by SimonSimCity** [Azure/iot-hub-device-update#127]
While comparing the changes from the yocto meta layer, provided in this repo as artifacts, I wondered about the changes supplied in the receipe `azure-device-update`:

At first this looked suspicious that the permissions for the folder `ADUC_DOWNLOADS_DIR` are changed in a block meant for `ADUC_LOG_DIR`:

https://github.com/munit-solutions/meta-azure-device-update/blob/7b237fa76d7c34919f074f85af1d36b9b99818a9/recipes-azure-device-update/azure-device-update/azure-device-update_git.bb#L156-L159

And then I found out that you change the permissions of that folder just a few lines above already:

https://github.com/munit-solutions/meta-azure-device-update/blob/7b237fa76d7c34919f074f85af1d36b9b99818a9/recipes-azure-device-update/azure-device-update/azure-device-update_git.bb#L145-L148

Could it be that you mixed up the naming of the variables there?

**Comment by Nox-MSFT** [comment]
Hi @SimonSimCity , I've updated the asset in the [0.8.0 Release Page](https://github.com/Azure/iot-hub-device-update/releases/tag/0.8.0) with the changes you've suggested.

Thank you for you contribution!
