### ISSUE TITLE
[0.8.0] Yocto meta layer changes group of folder twice - once would be sufficient...

### ISSUE THREAD

**Issue by SimonSimCity** [Azure/iot-hub-device-update#128]
In the file azure-device-update_git of the meta layer provided for version 0.9.0, I suggest that the file azure-device-update_git could be simplified by removing line 152. This line changes the group of the folder to root, and in the next line you change it again to ADUGROUP.

https://github.com/munit-solutions/meta-azure-device-update/blob/7b237fa76d7c34919f074f85af1d36b9b99818a9/recipes-azure-device-update/azure-device-update/azure-device-update_git.bb#L150-L154

**Comment by Nox-MSFT** [comment]
Hi @SimonSimCity , I've updated the asset in the [0.8.0 Release Page](https://github.com/Azure/iot-hub-device-update/releases/tag/0.8.0) with the changes you've suggested.

Thank you for you contribution!
