### ISSUE TITLE
User consent workflow

### ISSUE THREAD

**Issue by JanZachmann** [Azure/iot-hub-device-update#129]
Hi 

We would like to extend our swupdate based linux update workflow by a user consent. The consent should be possible via cloud (e.g. desired property) or on device (e.g. via hardware button). Our approach would be to implement a multistep update with two steps:
1. `WaitForConsent ` update handler as pre-install task
2. existing `"microsoft/swupdate:1"`

- Is this a valid approach?
- Is it possible to wait in `WaitForConsent ` an undefined time for the consent?
- How can the device communicate to the update service that it is waiting for the consent? Can we maybe use Agent Metadata like `Custom compatibility Properties` and `resultDetails` for that purpose?
- Would it be possible to send the consent via via agent twin?

BR
Jan

**Comment by esha0611** [comment]
Hi @JanZachmann, we are tracking this feature with out of box support for a future release. I am marking this as closed for now. Please feel free to reopen if there are any other questions/ feedback on this.
