### ISSUE TITLE
adu_core_interface.h include directive invalid path.

### ISSUE THREAD

**Issue by bennydiamond** [Azure/iot-hub-device-update#130]
adu_core_interface.h has an include directive that reference a relative path in [azure-iot-sdk-c](https://github.com/Azure/azure-iot-sdk-c) that does not exist.

`#include <azureiot/iothub_client_core_common.h>` cannot be resolved by GCC without modifying folder structure of [azure-iot-sdk-c](https://github.com/Azure/azure-iot-sdk-c) project.

Details are located over here:
https://stackoverflow.com/questions/71238001/reference-a-virtual-location-as-include-path-in-gcc

**Comment by bennydiamond** [comment]
I just saw the `install-deps.sh` script. I am wondering if it's possible to specify manually an install location. I would like to avoid installing libs on a system-level.

**Comment by jw-msft** [comment]
At the end of the day, it would require setting [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) (default is /usr/local) on all dependency and in DU agent project--it's not exposed as an option in install-deps.sh today

For example, azure-iot-sdk-c has build.sh that uses $cmake_install_prefix to set -DCMAKE_INSTALL_PREFIX in cmake command to generate the build script.
One could try setting [azureiotsdkc_make_options](https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/scripts/install-deps.sh#L164) to include cmake_install_prefix.  For DO, catch2, and azure_storage_cpplite, one might be able to just set -DCMAKE_INSTALL_PREFIX:PATH=<path>

Tracking this internally now as a possible improvement to the install-deps.sh/build.sh scripts.

**Comment by nihemstr** [comment]
@bennydiamond if you're still looking into how to do this locally you can modify `install-deps.sh` to add cmake options for each of the targets you want to add to a local folder, however I'm not sure how that effects the build process (eg you specify the libs are installed to `~/aduc_libs` that needs to be added to your includes and libs path for the `build.sh` script to work properly). 

If you're just looking at installing the source in a separate directory we have a -k command that keeps all of the downloaded code and a `-f` command that you can specify a working directory to which these sources are downloaded, built, and then installed to the `/usr/include/` and `/usr/lib` directories for the compiler.

I'm closing the issue for right now. Feel free to open a new issue if this persists or there is new information.
