### ISSUE TITLE
Can used module in adu-agent

### ISSUE THREAD

**Issue by gc-zoetis** [Azure/iot-hub-device-update#132]
Hi,
As adu-agent code used device mode in IOT-HUB. But there is also option for module base communication.
We have added some extra feature for our own requirement and everything running as one device only. We want to run separately each feature as OTA in one module , our part in another.
Question are
1. Can we run OTA process and deployment part in one module and other feature in another at device side?
2.  Can we configure DPS feature if module based can work.

Thanks in advance and answer will help lot for further development

regards

**Comment by jw-msft** [comment]
adu agent can be module or device id (module is preferred). There can be multiple modules each running their own process but requiring separate connection. See [this doc](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-module-twins).
Could you explain what is DPS feature?

**Comment by gc-zoetis** [comment]
Hi jw-msft,
Sorry for delay in response and thanks for comment.
I want to implement adu-agent modular wise mean same like running on edge device but without container.
will it possible for adu-agent ?
I am planning to run above code as 
 module-1 -> run OTA process
module-2 -> run communication and device provisioning (DPS)
module-3  -> run custom application.

If I put OTA code into module, will OTA action work as normal way ?

**Comment by jw-msft** [comment]
it should. there is more info here: https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-provisioning

**Comment by nihemstr** [comment]
Closing because of in activity. If there is need of additional information please feel free to create a new issue!
