### ISSUE TITLE
Unable to read connection string from configuration file [GetConnectionInfoFromADUConfigFile]

### ISSUE THREAD

**Issue by Lux-Coding** [Azure/iot-hub-device-update#134]
Hi,

I'm currently trying to get this(https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-raspberry-pi) Tutorial working.

Everything works to the point where the Daemon(adu-agent) has to be started. My Problem is the Daemon dies because he cant read my connection String?

This is the status-report from the systemctl status adu-agent.
![status](https://user-images.githubusercontent.com/74984800/156530468-76da0072-edd9-4b4d-ab4c-bf7bf35e1279.PNG)

/adu/ Folder. Both Files created.
![ls](https://user-images.githubusercontent.com/74984800/156530489-b2b9fb30-cb8e-4cd9-83d9-946b04279bdb.PNG)

This is my config File. Connection String placed where the Tutorial told me to.
![do-config](https://user-images.githubusercontent.com/74984800/156530507-be6b66a8-d168-443f-86d6-5fd770441963.PNG)

Pls help

**Comment by Lux-Coding** [comment]
SOLVED:

Create /adu/adu-conf.txt
Daemon is able to read this.

Template:

```
connection_string = `HostName=<yourIoTHubName>;DeviceId=<yourDeviceId>;SharedAccessKey=<yourSharedAccessKey>`
aduc_manufacturer = <value to send through `AzureDeviceUpdateCore:4.ClientMetadata:4.deviceProperties["manufacturer"]`
aduc_model = <value to send through `AzureDeviceUpdateCore:4.ClientMetadata:4.deviceProperties["model"]`
manufacturer = <value to send through `DeviceInformation.manufacturer`
model = <value to send through `DeviceInformation.manufacturer`
```

**Comment by jw-msft** [comment]
Also, the du-config.json looked ok, but the logs show 0.6.0 private preview agent instead of 0.8.0, so it's probably looking for the older adu-conf.txt, not du-config.json.
It is possible in "Download the image" step, older .wic.gz was mistakenly downloaded?

To fix, you could backup /adu/*.json, flash SD card with https://github.com/Azure/iot-hub-device-update/releases/download/0.8.0/adu-base-image-raspberrypi3.wic.gz, and restore /adu/*.json

**Comment by Lux-Coding** [comment]
Nice ty that worked. 

But now I got a different problem. :(

When I try to create the "ADUGroup" tag the adu agent fails loading the extension.json file

`Mar 07 07:55:18 raspberrypi3 AducIotAgent[360]: {"deviceUpdate":{"__t":"c","agent":{"deviceProperties":{"manufacturer":"fabrikam","model":"vacuum","interfaceId":"dtmi:azure:iot:deviceUpdate;1","aduVer"
:"DU;agent\/0.8.0-public-preview","doVer":"DU;lib\/v0.6.0+20220201.143054,DU;agent\/v0.6.0+20220201.143052"},"compatPropertyNames":"manuf2022-03-07T07:55:18.0599Z [E] Cannot open an extension registrat
ion file. ('/var/lib/adu/extensions/component_enumerator/extension.json') [GetExtensionFileEntity]
Mar 07 07:55:18 raspberrypi3 AducIotAgent[360]: 2022-03-07T07:55:18.0600Z [E] Failed to load extension from '/var/lib/adu/extensions/component_enumerator/extension.json'. [LoadExtensionLibrary]
Mar 07 07:55:18 raspberrypi3 AducIotAgent[360]: 2022-03-07T07:55:18.0601Z [E] Cannot get components information. erc: 0x70000003 [DetectAndHandleComponentsAvailabilityChangedEvent]`

When looking into the /var/lib/adu/extensions/component_enumerator/ folder nothing is in there.

**Comment by Lux-Coding** [comment]
Nice Ty that worked.
