### ISSUE TITLE
[0.8.0]OTA process report success in failure of Install step

### ISSUE THREAD

**Issue by gc-zoetis** [Azure/iot-hub-device-update#135]
Hi,
I working on new version 0.8.0 of adu-version.
I observed that there may be bug while handling in install process.
I am working on package based update where apt-handler get into picture.
But event installation of package in adu-shell process failed , code returning success to high level of code [mean to step handler.]
This will not be case as per document said agent should report success/fail of OTA process 
Question is that Do agent report failure of installation package by apt to adu-service on cloud ?  or agent must be reported failed result of action[download, install ,apply].

https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/src/content_handlers/apt_handler/src/apt_handler.cpp#L307
```
 if (aptExitCode != 0)
    {
        result.ResultCode = ADUC_Result_Failure;
        result.ExtendedResultCode = ADUC_ERC_APT_HANDLER_PACKAGE_INSTALL_FAILURE;
        Log_Error("APT packages install failed. (Exit code: %d)", aptExitCode);
    }

  result = { ADUC_Result_Install_Success };
```

Code should have **goto done** after line 311 , return immediately with error code and i have tested with that logic.

```
 if (aptExitCode != 0)
    {
        result.ResultCode = ADUC_Result_Failure;
        result.ExtendedResultCode = ADUC_ERC_APT_HANDLER_PACKAGE_INSTALL_FAILURE;
        Log_Error("APT packages install failed. (Exit code: %d)", aptExitCode);
       goto done;
    }

  result = { ADUC_Result_Install_Success };
```
Confirm me about above problem. is that bug or not. if not please provide explain about why agent returning success even step get failed.
Thanks in advance.
Regards

**Comment by jw-msft** [comment]
Thanks for finding and reporting this, @gc-zoetis. The `goto done;` was indeed missing. This fix will be included with next minor release.

**Comment by gc-zoetis** [comment]
Hi jw-msft,
Thanks for confirming.
