### ISSUE TITLE
Device updates for iotedge runtime configuration

### ISSUE THREAD

**Issue by reginbald** [Azure/iot-hub-device-update#139]
Have you though about how we would update configurations of packages?
For example when when we move from iotedge 1.1 to 1.2 the configuration file structure changes completely.

**Comment by jw-msft** [comment]
//cc @esha0611 

If the deb pkg maintenance scripts handle when 'update' parameter is passed (see [maintainer script flowcharts](https://www.debian.org/doc/debian-policy/ap-flowcharts.html)), then that could be used by package maintainer scripts during update. For updating du agent itself, it will handle this case and do auto-migrationg of config.

An interesting case is configs that require user intervention for values for du agent and more generally for any apt package. A catchall can be to add a [post-step in step handler](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-multi-step-updates) with a script handler script as update payload, but exploring ways to avoid needing to do that.

**Comment by eshashah-msft** [comment]
Closing this issue as there are no updates. @reginbald Please go to [Discussions-Ideas](https://github.com/Azure/iot-hub-device-update/discussions/new?category=ideas) to add new feature requests/ suggestions.
