### ISSUE TITLE
Unable to create deployment groups because tags are not found

### ISSUE THREAD

**Issue by jzaegel** [Azure/iot-hub-device-update#142]
# Summary

I have an IoT Hub setup with DPS. My devices are a mix of physical and VMs. 
Device Update works fine with default groups - I am able to deploy updates that end up properly installed on my devices.
But I cannot create custom deployment groups because tags are not found.
This is something I need to progressively roll out updates in production and mitigate the risk of a bad update.

# Related issues

https://github.com/Azure/iot-hub-device-update/issues/117
https://github.com/Azure/iot-hub-device-update/issues/76

# Detailed cloud setup

My IoT Hub and my DPS are in Canada Central.
My Device Update is in West US 2 (limitation of the preview).

![image](https://user-images.githubusercontent.com/30506549/159932300-6bedbf8d-b494-4cfd-a6c9-aed2d47655b8.png)
The first default group, which gathers my VMs, has been able to deploy an apt update.

# Detailed device setup

Ubuntu server 20.04 LTS (Azure VM Standard_B1ms, 0001-com-ubuntu-server-focal, 20_04-lts-gen2) with virtual TPM.
Registration of the device in IoTHub is made through the DPS with TPM attestation.
IoT Edge is installed (see config.toml in device-config.zip)

The device update agent is installed with:
`wget https://github.com/Azure/iot-hub-device-update/releases/download/0.8.0/deviceupdate-agent_0.8.0_public_preview_amd64.deb`
`sudo -S apt-get install -y ./deviceupdate-agent_0.8.0_public_preview_amd64.deb`

The connection type is set to AIS - using the identity service of iot edge (see du-config.json and adu.toml in device-config.zip)

[device-config.zip](https://github.com/Azure/iot-hub-device-update/files/8342377/device-config.zip)

# Device in IoTHub

![image](https://user-images.githubusercontent.com/30506549/159935189-0afef712-d932-4418-a7cb-6b8bf42914f0.png)

![image](https://user-images.githubusercontent.com/30506549/159935498-7d0b8db6-5726-4ae5-b676-4e601990e5ea.png)

See devicetwin.json in device-config.zip

# Symptom

When trying to add a deployment group, my device classes are properly detected
![image](https://user-images.githubusercontent.com/30506549/159932712-16095a92-8c9f-43a3-816d-4e2375e903a2.png)

But tags cannnot be found:

![image](https://user-images.githubusercontent.com/30506549/159932847-7f25c2b4-16ed-4518-b600-fc2aeb89b23d.png)

# Logs found on the machine

- Iot Edge support bundle
- adu logs in /var/log/adu
- output of `sudo journalctl -u adu-agent --since "12 hours ago"`

[logs.zip](https://github.com/Azure/iot-hub-device-update/files/8342290/logs.zip)

# Observation 1

The message routing created by the device update deployment 

![image](https://user-images.githubusercontent.com/30506549/159941517-a2233d13-8d6c-49f7-90e6-95c723fae076.png)

doesn't match the message recommendation of message routing from https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-resources

Output of "Test all routes":

![image](https://user-images.githubusercontent.com/30506549/159942141-30ddbb96-a619-401b-b88f-5c08c38cb775.png)

There seem to be an issue with the DeviceTwinChanges, which could explain why we miss the tags.

# Observation 2

journalctl outputs a weird mention to contoso, the typical MS example company
`Mar 24 03:02:25 vm-sandbox-ju-dev-01 AducIotAgent[1306]: Cannot parse component configuration files ('/usr/local/contoso-devices/components-inventory.json').-> 02:58:24 PINGREQ`

But feedback from MS indicates it is inocuous.

**Comment by iryanzhang** [comment]
Hi jzaegel,

Looks like you are using module identities.  the above device twin snapshot is from device **vm-immo-lab-001-dev-01**.  could you check the module twin for **IoTHubDeviceUpdate**, and see if tags "ADUGroup" are set correctly in there?

**Comment by iryanzhang** [comment]
For details,  please refer [ADU running with device identity vs module identity](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-provisioning#module-identity-vs-device-identity)

**Comment by jzaegel** [comment]
Hi iryanzhang, thanks for jumping in quickly

Here's the Module Identity Twin IoTHubDeviceUpdate: [module-itentity-twin.json.txt](https://github.com/Azure/iot-hub-device-update/files/8351614/module-itentity-twin.json.txt)

Obserations:
- I could find no trace of the tags in twin
- The reported properties give the feedback about the proper behaviour of the update that I couldn't find the in the device twin

**Comment by iryanzhang** [comment]
Thanks for sharing the module twin.  it can explain why you didn't see the error "tags are not found".  could you try to update module twin and set the tag? and see if it work
 
"tags":{
		"ADUGroup" :"sandboxjugrouptry"
}

When you provision the Device Update agent as a Module Identity, all communications between the device and the Device Update service happen over the Module Twin so do remember to **tag the Module Twin of the device** when creating [groups](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-groups) and all [communications](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-plug-and-play) must happen over the module twin.

Thinking of the module as an independent unit, it has its own connection to Hub/ twin. so reported/desired properties will go to the module twin instead device twin.

**Comment by jzaegel** [comment]
I tried it out after your comment this morning:

![image](https://user-images.githubusercontent.com/30506549/160187640-40af5327-9898-4733-a670-c5e2e23ee32a.png)

I restarted the ADU agent and event rebooted the VM

but still not tags

![image](https://user-images.githubusercontent.com/30506549/160187774-a29bd32e-4023-4e46-9a18-4bfa3129f8d2.png)

"When you provision the Device Update agent as a Module Identity". Maybe I can live with device identity (I didn't make a conscious choice of going with Module Identity). I'd like to give a try at device identity. How can I configure this? Can you please point me towards an appropriate reference?

**Comment by jzaegel** [comment]
Feels like there is no bug on your side, everything was bad config on mine.
Maybe the doc and/or the diagnostics could benefit from some improvement though.

Thanks for the support!
