### ISSUE TITLE
adu group not visible in update portal

### ISSUE THREAD

**Issue by gc-zoetis** [Azure/iot-hub-device-update#144]
Hi,
I have been working device update sdk since  3month and worked on version 0.7.0 and 0.8.0 both.
We have customized the  device update sdk code for our requirement where we added device provisioning code in sdk.
Now recently added TPM functionality where device get provisioned using TPM module over AMQP as TPM only supported with AMQP.

But in some post found that device should have the plug and play component in order to work with du service at portal and plug and play device only work with MQTT and MQTT_WS.

This docs mentioned device should be as iot plug and play device for du service.
[https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-plug-and-play](url)

[](url)
```
 Important

IoT Plug and Play devices must use MQTT or MQTT over WebSockets. Other protocols such as AMQP or HTTP are not valid to implement IoT Plug and Play devices.
```

I have observed that some parameter in device twins not updated like 'statusUpdateTime' and 'lastActivityTime' and 'modelId' as well.

```
	"deviceEtag": "NjMyNDgxNjQ5",
	"status": "enabled",
	"statusUpdateTime": "0001-01-01T00:00:00Z",
	"connectionState": "Connected",
	"lastActivityTime": "0001-01-01T00:00:00Z",
	"cloudToDeviceMessageCount": 0,
	"authenticationType": "sas",
	"x509Thumbprint": {
		"primaryThumbprint": null,
		"secondaryThumbprint": null
	},
	"modelId": "",
	"version": 7,
	"tags": {
		"ADUGroup": "########"
	},
```

Does TPM with AMQP causing the problem for group not appearing in portal?
what could be issue for not visible the group name even everything is good?

Thanks in advance
regards
Gaurav

**Comment by xinanqiu** [comment]
You have not connected any DU agent to this twin, so it is not included.

You can follow below instruction to connect an agent.
https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-overview

Once the agent is connected, the model id will be reported. Then the tag should be shown for group creation.

**Comment by gc-zoetis** [comment]
Hi xinanqiu,
Thanks for reply.
Yes we observed that model id not updated in twins even device send it.
Eventually figure out that device twins get updated only when device using MQTT or MQTT_ws for IOT communication with IOT-HUB and du service configure IOT plug and play component which registered the model id.
As our requirement go with TPM and TPM only works with AMQP , is there other way to achieve ? 
and any update for du-agent with TPM support ?

**Comment by xinanqiu** [comment]
Hi @gc-zoetis,

Have you tried the suggestion at https://github.com/Azure/iot-hub-device-update/issues/87?

**Comment by eshashah-msft** [comment]
Hey @gc-zoetis, were you able to try the recommended approach in #87   ?

**Comment by eshashah-msft** [comment]
Closing the issue as there are no new updates
