### ISSUE TITLE
Unable to install Device Update Agent Prerequisites, Device Update Agent, C SDK, Delivery optimization Client on Raspberry Pi 4 with the Debian 11 based Raspberry Pi OS

### ISSUE THREAD

**Issue by PPK1996** [Azure/iot-hub-device-update#145]
Hi Team, I tried to provision the Device Update Agent and required prerequisites on Raspberry Pi 4 but have not been able to do so. Could anyone share the exact steps to provision the same? The documentation: https://github.com/Azure/azure-iot-sdk-c/blob/main/doc/SDK_cross_compile_example.md does not work properly.

**Comment by jw-msft** [comment]
There was [a report of RPi4 success](https://github.com/Azure/iot-hub-device-update/issues/119#issuecomment-1035416390) comment wrt [these steps ](https://github.com/Azure/iot-hub-device-update/issues/119#issuecomment-1034554506) but I haven't verified it myself yet. I did get an RPi4 device recently so will give it go.

There is also this [simpler/better option](https://github.com/Azure/iot-hub-device-update/issues/119#issuecomment-1035555755). Will see if can get it in properly in this and possibly the az blob utility depending proj to make it work out of the box.

**Comment by shiyi-peng** [comment]
Hi! Now we have full support on Debian 10 ARM64, which can be downloaded directly. Debian 11 is not on our supported OS list yet, but I think you will be able to build the agent from source.
You could try building our v1.0.0 release agent on your device. See instructions here: https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-build-agent-code.md

**Comment by jw-msft** [comment]
You can install [patch release 1.0.2 ](https://github.com/Azure/iot-hub-device-update/releases/tag/1.0.2) on Ubuntu 20.04 + RPi4 via this .md I wrote: #377

Related issue is #344
