### ISSUE TITLE
0.8.0 Extensions: need for extension registration files, and relative documentation

### ISSUE THREAD

**Issue by neonsoftware** [Azure/iot-hub-device-update#149]
Hi ! 

Thank you in advance for looking into this aspect.

**context:**
- migrating from 0.7.0 to **0.8.0**
- **non**-IotEdge scenario
- building on Ubuntu 18.04, from source, with Cmake

**issue:**
At runtime I see the following error

```[I] Loading Update Content Handler for 'microsoft/swupdate:1'. [LoadUpdateContentHandlerExtension]
[I] Loading extension 'microsoft/swupdate:1'. Reg file : /var/lib/adu/extensions/update_content_handlers/microsoft_swupdate_1/content_handler.json [LoadExtensionLibrary]
[E] Cannot open an extension registration file. ('/var/lib/adu/extensions/update_content_handlers/microsoft_swupdate_1/content_handler.json') [GetExtensionFileEntity]
[E] Failed to load extension from '/var/lib/adu/extensions/update_content_handlers/microsoft_swupdate_1/content_handler.json'. [LoadExtensionLibrary]
```

**question:**
What are these **extension registration files**, ex. **content_handler.json**, in which step are they created, and where are they documented ?

Thank you in advance

**Comment by jw-msft** [comment]
wrt to how to register an extension:
- Here is some documentation on how to [register a custom content handler](https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/docs/agent-reference/how-to-implement-custom-update-handler.md#how-to-register-a-content-handler-extension).

- The Debian package postinst post-install script [register_reference_extensions() shell script function ](https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/packages/debian/postinst#L212)has similar registration invocations, so if installing using APT, it will auto-register these during package post-install.

AFAICT, there's a gap for a comprehensive doc going over all the extensibility points of the agent, but they are documented in separate docs (except content downloader extension).

The 0.8.0 agent has various extensibility points:
- content downloaders
  - customization of how to download update content and [v4 update manifests](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/update-manifest-v4-schema.md)
  - [content downloader README.md ](https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/src/extensions/content-downloaders/README.md) ( currently empty )
- update content handlers
  - add installation of your own update content types
  - [How to implement a custom content handler extension](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-implement-custom-update-handler.md)
- component enumerator
  - customize how to list h/w components for child proxy updates.
  - [Proxy Updates and multi-component updating](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/multi-component-updating.md)

**Comment by neonsoftware** [comment]
Thank you @jw-msft.  
I will check these resources this week and keep you updated.

**Comment by esha0611** [comment]
Hi @neonsoftware, thanks for the feedback on the documentation. I have added to our backlog. Please feel free to reopne the issue if there are any other questions/ feedback.

**Comment by neonsoftware** [comment]
Hi @esha0611, 
Yes, it can be closed.
