### ISSUE TITLE
version scheme

### ISSUE THREAD

**Issue by JanZachmann** [Azure/iot-hub-device-update#152]
Hi

Due to your [documentation](https://docs.microsoft.com/en-us/previous-versions/azure/iot-hub-device-update/import-schema#updateid-object) the version field of `UpdateId Object` only allows four dot separated parts. For our use case, where we update an entire yocto firmware image, this is quite restrictive. Our existing version scheme uses the current yocto release (already three parts) plus our own release number plus a build number. Is there a plan or a chance to extend the number of possible parts in future?

BR
Jan

**Comment by devlie** [comment]
Hi @JanZachmann, unfortunately `updateId` is our core identifier used across ADU services/implementations and is unlikely to change in the future. In case it's not obvious, `updateId` is only used for communication between cloud services and ADU agent, so its `Version` does not have to exactly match the actual software version inside the update (Yocto's). Thanks.
