### ISSUE TITLE
Raspberry Pi Zero W

### ISSUE THREAD

**Issue by PeteDouma** [Azure/iot-hub-device-update#153]
I can not get this to work on Raspberry Pi Zero W. Should it work?

**Comment by SatishBoddu-MSFT** [comment]
Related to Q&A: https://docs.microsoft.com/en-us/answers/questions/813067/raspberry-pi-zero-w-and-2w-device-update.html

**Raspberry Pi Zero W and 2W Device Update**
I am reading this article https://docs.microsoft.com/en-us/azure/iot-hub-device-update/understand-device-update. It uses the example of a Raspberry Pi 3, but we have Raspberry Pi Zero W and soon will have Raspberry Pi Zero 2W devices. Can I run the agent on these devices?

**Comment by triple-it** [comment]
What distribution version are you using? 20.04 maybe? Because you are missing the packages in the repo.
If so, take a look at:
[https://github.com/Azure/iot-hub-device-update/issues/151](https://github.com/Azure/iot-hub-device-update/issues/151
)

**Comment by PeteDouma** [comment]
I compiled all the requirements which took hours, after which I got a message saying I was missing something else. What would help is just a prebuilt raspberry-pi zero w version.

**Comment by triple-it** [comment]
+1  
What OS version are you running on the Raspberry Pi? (Buster or Bullseye?)
And shouldn't you cross-compile? (On a different system)

**Comment by PeteDouma** [comment]
Bullseye 32 bit headless

**Comment by esha0611** [comment]
Hi @PeteDouma, @SatishBoddu-MSFT, Thanks for this request, we will look into this support request. I have added this to our backlog. 
Right now, we do not have out of box support for Raspberry Pi Zero. We are planning to add support for Debian 11 (which Raspbian uses) in the near future.  But, cross-compiling the DU agent and the tool chain should work to build a customized agent.

**Comment by shedy52** [comment]
@eshashah-msft any update on this support request.
