### ISSUE TITLE
How do we get code coverage reports?

### ISSUE THREAD

**Issue by Srinikethan-BH** [Azure/iot-hub-device-update#159]
I have been using this for my solution and wanted to know if there is an option to generate code coverage reports?
Or are there any tools recommended? Since trying to integrate gcov is becoming nightmare.!

**Comment by jw-msft** [comment]
we were planning on investigating using gcov + LCOV and GCovR to generate reports, but also would integrate the coverage reports into ADO pipelines. Sounds like you hit some roadblocks? Would be interested in learning what those were if you wouldn't mind sharing.

**Comment by Srini-Zoetis** [comment]
> we were planning on investigating using gcov + LCOV and GCovR to generate reports, but also would integrate the coverage reports into ADO pipelines. Sounds like you hit some roadblocks? Would be interested in learning what those were if you wouldn't mind sharing.

" Yes, i would like to know. I have installed gcov, lcov, and gcovr. I had issues in setting compiler flags to generate .gcno files, and then .gcda file. Can you let me know in detail on how do we handle these to get reports?

**Comment by srini1392** [comment]
Any update guys?

**Comment by srini1392** [comment]
Yes i have already enabled and building it, but would like if you already have some reports. But thanks i think you do not have any results for me at the moment, for my timelines. I have already generated reports using gcov and gcovr. Thanks again guys!

**Comment by eshashah-msft** [comment]
Closing this issue as no action is pending.
