### ISSUE TITLE
Need a controlled schedule/apply API to updates of *individual* IoT-Edge devices 

### ISSUE THREAD

**Issue by RichardHubertPtw** [Azure/iot-hub-device-update#163]
Hi! We use ADU for both on HW-devices (endpoints: IoT-Devices/Firmware) and IoT-Edge devices. The Iot-Edge devices are soft-devices as nodes that interact with endpoint devices. We have a critical issue with ADU for the IoT-Edge devices, as follows:

Related to the A/B "apply" support for firmware updates of endpoint Iot-Devices, we need a device-instance-level granularity with a "start now" API for IoT-Edge deployments and IoT-Device (endpoints). This is currently not possible. Currently, our understanding (based on code & doc views) is that ADU forsees only (large) groups of devices that are all updated in one fail swoop as soon as they come online, whenever that may be. There is no specific control over the precise timing/event to start the update.

For our IoT-Edge devices, such an update "whenever device is online" would constitute a severe and costly bug since these (MedTech) devices are used in production medical functions during the day in various time-zones. In short, similar to Windows 11 update scheduling, the customer must tell us when they can, and want to, update. We can't just interrupt their operations with an update. Also, they usually want to schedule an update at a time where tests are possible before the next production usage. A coordinated roll-back (of IoT-Edge node and its attached IoT-Devices) would be a derived requirement here, similar to the A/B approach taken with firmware.

For another example, what would happen if an Iot-Edge-connected drone (endpoint) were operational in a give time-zone, and all of a sudden the drone's Iot-Edge starts updating while it is in mid flight... or it comes back online and the IoT-Edge is a "different one" with potentially invalid workload/service certificates?

As such, we observe that for many realistic scenarios, including ours, the group update "at any time" is not a feasible approach. We need a mechanism to set (potentially several thousands) of devices (IoT-Hub including IoT-Edge devices) with their own update and to "apply" or "start" these updates via an ADU-API (at least, or in the Azure Portal too at best). This API would be customer driven via our systems: the customer would start (or say when to start) the planned ADU update for her (Iot-Hub/IoT-Edge) device.

Thanks for any information of tips.

**Comment by shaeussler** [comment]
Is it possible to use the "Create or Update Deployment API" https://github.com/Azure/iot-hub-device-update/blob/main/docs/management-api-reference/create-or-update-deployment.md to deploy an update to an single device with the following json:
`{
  "deploymentId": "myDeploymentId",
  "deploymentType": "complete",
  "deviceClassId": "c83e3c87fbf98074c20c3269f1c9e58d255906dd",
  "startDateTime": "2020-05-27T19:25:57.6448039Z",
  "deviceGroupType": "devices",
  "deviceGroupDefinition": [
  	"Iot-Edge-Device-Id",
  	],
  "updateId": {
    "provider": "contoso",
    "name": "virtual-machine",
    "version": "3.0"
  }
}`

**Comment by josephmsft** [comment]
Sorry my previous response was responding to shaeussler.  Right now we have very limited support for the scenario you are describing RichardHubertPtw.  A user can schedule the start of a deployment by picking a future start date and no devices will update until that time passes, but once the start date has passed all qualified devices in the group will begin receiving the deployment and start updating right away if they are online.  Having additional controls on when devices update is something I think we're tracking as a potential area to add enhancements but it's not in any of our current releases.  In order to have tighter control of when specific devices update you would need to split your eligible devices into different groups and deploy the same update to them with different start times.

**Comment by RichardHubertPtw** [comment]
Thanks. I'm in touch with shaeussler too. There is a simple workaround that would help us toward a production solution even without significant changes in the current implementation: give us a way to have at least 10000 groups (current limit is 1000 I believe), then we could put one device per group and we'd be on our way for a while...

**Comment by sourabhkrishna** [comment]
@RichardHubertPtw @josephmsft  Even we are looking for a workaround where in we can initiate deployments per device instead of the whole group.
