### ISSUE TITLE
Add meta-azure-device-update as a GitHub repository

### ISSUE THREAD

**Issue by morten-bruun-zoetis** [Azure/iot-hub-device-update#171]
Instead of releasing the meta-azure-device-update layer as a zip file, I suggest creating a GitHub repository for the meta-azure-device-update layer.

**Comment by eshashah-msft** [comment]
+ @Nox-MSFT 
Thanks for the feedback @morten-bruun-zoetis . We are currently working on setting up a separate repository for the DU meta-layers and yocto build instructions. I will update this issue when we have the repository link.

**Comment by eshashah-msft** [comment]
Our Yocto layers published in this repo and will be maintained for our releases: https://github.com/Azure/iot-hub-device-update-yocto
