### ISSUE TITLE
Support for semantic version specification for version property of Import Update Identifier

### ISSUE THREAD

**Issue by AmithaVPadiyar** [Azure/iot-hub-device-update#174]
Is the above work planned in near future or in the pipeline?

**Comment by andrewbrownmsft** [comment]
Thanks for the feedback. Can you describe the scenarios you are trying to achieve that can't be met with the Update Id Version as currently defined? Our goal is to allow the creator of a series of updates to have flexibility to use whatever versioning scheme makes the most sense for them. If there is a limitation that is blocking a useful scenario for you, we'd definitely like to understand that.

**Comment by AmithaVPadiyar** [comment]
Currently in our use-case, the version property is handled with digits only. But in future, we may accommodate alphabets in the version as we have aligned to semantic version specification that would allow alphanumeric characters for patch component of the version.

**Comment by andrewbrownmsft** [comment]
Understood - that's helpful, thanks for responding.

The reason we have a purely numeric version is to enable the service to determine the latest available update for a given device type. When updating devices at scale, especially heterogeneous fleets with many device types, we believe there's a lot of value in the simplicity of presenting our user with the latest update automatically. Without a numeric version, we have no deterministic way of doing that on the service.

As we move towards General Availability and beyond, we are continuing to listen to feedback like this and will make changes as it makes sense over time. But we don't have any current plans to change the Update Id Version approach.

**Comment by alancshi** [comment]
@AmithaVPadiyar would it help if you could attach a custom descriptor (freeform text) to your updates? this is something we are already looking into.

**Comment by eshashah-msft** [comment]
@AmithaVPadiyar Closing this issue as there is no updates/ activity. Please feel free to open a new issue if you have any other questions. You can also go to https://aka.ms/deviceupdateiot-feedback to upvote/ add any feature request/ suggestion.
