### ISSUE TITLE
meta-azure-device-update: Support recent Yocto release

### ISSUE THREAD

**Issue by morten-bruun-zoetis** [Azure/iot-hub-device-update#178]
The current meta-azure-device-update layer is compatible with the Yocto warrior release (which has reached end of life).

The layer should be updated to support a Yocto release that is supported by the Yocto Project (e.g. Dunfell or Kirkstone).

**Comment by Vishwasrao1** [comment]
Could you please share where this layer is?? I am unable to find any yocto meta-layer from azure for device update.

**Comment by eshashah-msft** [comment]
@morten-bruun-zoetis Our Yocto layers (for Honister) published in this repo and will be maintained for our releases: https://github.com/Azure/iot-hub-device-update-yocto
