### ISSUE TITLE
Include arm32 in artifacts

### ISSUE THREAD

**Issue by thegreatdane6** [Azure/iot-hub-device-update#180]
Hi,

currently there is no artifact for arm32 devices even though the build pipelines are basically ready to go. Are you planning on integrating this in the near future or is there more work that needs to be done with that?

**Comment by esha0611** [comment]
@thegreatdane6 : We will be adding support for ARM32 with our next release

**Comment by eshashah-msft** [comment]
We have added support for Debian 10 ARM 32 with our latest release. 

If you need support for other OS flavors, please add a new suggestion here: [Device Update Ideas](https://github.com/Azure/iot-hub-device-update/discussions/new?category=ideas ) for consideration
