### ISSUE TITLE
 [0.8.x] compilation: add missing POSITION_INDEPENDENT_CODE

### ISSUE THREAD

**Issue by neonsoftware** [Azure/iot-hub-device-update#182]
Hi, 

### context

when building for a device on Openwrt, the build fails as POSITION_INDEPENDENT_CODE is present in some libraries but not in other dependent ones. 

### state

I have created the PR #181 to upstream the fix.

### issue

The **automatic builds** in the PR system seem to have failed immediately, how can i access the Azure Pipeline logs to investigate ? 

Thank you in advance for any info

**Comment by neonsoftware** [comment]
I have tried logging in to DevOps with the Github account but got a "**401 - Uh-oh, you do not have access.**"

**Comment by jw-msft** [comment]
The ADO pipeline is not public. We are looking into fixing that with e.g. github actions, etc.  Not sure why it's closed but I will resurrect this https://github.com/Azure/iot-hub-device-update/pull/181 and port to the latest develop.

**Comment by neonsoftware** [comment]
Great.
I will be active in the next days, if rebase or re-touches will be needed please do not hesitate to ask. 

Have a nice day.

**Comment by neonsoftware** [comment]
@jw-msft -  I might event have an more recent version, and extended, of this commit in our latest iterations.
I will update here 10h from now.

**Comment by neonsoftware** [comment]
@jw-msft. 

Our most recent version is availalbe in the new PR #385, it corrects one file more than #384.

I have added this information also in the comments of #384.

**Comment by jw-msft** [comment]
I closed #384 in favor of your #385 and approved it. I created branch Azure:user/jw-msft/picpr to test it with the ADO pipeline [here](https://dev.azure.com/azure-device-update/adu-linux-client/_build/results?buildId=11923&view=results):

**Comment by neonsoftware** [comment]
@jw-msft  https://github.com/Azure/iot-hub-device-update/pull/385 was merged. I guess that this Issue might be closed ?

**Comment by jw-msft** [comment]
@neonsoftware yes, went ahead and merged it. Closing.
