### ISSUE TITLE
why not to support underline in ValidatePattern of DeviceModel?

### ISSUE THREAD

**Issue by KunYi** [Azure/iot-hub-device-update#19]
why not to support underline in ValidatePattern of DeviceModel?

![image](https://user-images.githubusercontent.com/2186922/111741801-0c84e100-88c2-11eb-8374-0c8c931cc4db.png)

**Comment by andrewbrownmsft** [comment]
Hi,

Thanks for trying out Device Update for IoT Hub, and for providing feedback to help us improve. You are correct that we do not currently allow the underscore character. We will look at improving this in a future release.

**Comment by KunYi** [comment]
okay, maybe we try another naming rule to avoid underscore character for current status
anyway thank you for your reply
