### ISSUE TITLE
"SECURITY.md" and "Security.md" collide on Windows

### ISSUE THREAD

**Issue by ccli8** [Azure/iot-hub-device-update#193]
On Windows 10, clone and switch to `0.8.2` branch:
```
git clone https://github.com/Azure/iot-hub-device-update -b 0.8.2
```

Meet error:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'SECURITY.md'
  'Security.md'
```

`SECURITY.md` and `Security.md` collide on case-insensitive filesystem.

**Comment by jspaith** [comment]
I see the same error on Win11 and even just cloning the latest `main` branch.

**Comment by esha0611** [comment]
Issue acknowledged. Tracking the bug. Will remove the additional security.md file.

**Comment by shiyi-peng** [comment]
This is resolved, thanks!
