### ISSUE TITLE
Unable to execute script handler unit test & throws segmentation fault

### ISSUE THREAD

**Issue by Srini-Zoetis** [Azure/iot-hub-device-update#194]
I have built the adu agent code for 0.8.1 release and built the unit test files. When i try to execute the script handler executeable from ./out/bin it is failing all the test cases and also throws segmentation fault.

Please let me know how i can build and execute this correctly, also send me documentation if there is any regarding the same.

**Comment by Nox-MSFT** [comment]
@Srini-Zoetis , the Script Handler unit test is a work in progress and currently disabled by default. We will add more test in the next few weeks.

**Comment by Srini-Zoetis** [comment]
Ok got it. thanks for the update.
