### ISSUE TITLE
Cannot configure device update agent to communicate through a proxy server

### ISSUE THREAD

**Issue by LanceLiMS** [Azure/iot-hub-device-update#207]
Hi team, Our is following the doc [Provisioning Device Update for Azure IoT Hub Agent | Microsoft Docs](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-provisioning)

Their device is connected to a network that uses a proxy server and they managed to configure iotedge runtime to communicate through the proxy server. But we didn't find any doc regarding configuring proxy server for device update agent and always got connection errors.

May we know if there's a way to do the configuration for device update agent?

**The errors we got:**
deviceupdate-agent start with errors in proxy env
Aug 22 03:35:07 alanhyperv systemd[1]: Started Device Update Agent daemon..
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2724Z [D] Log file created: /var/log/adu/du-agent.20220822-033507.log [zlog_init]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2728Z [I] Agent (linux; 0.8.2-public-preview) starting. [main]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2728Z [I] Git Info: HEAD:b2cc550 [main]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2728Z [I] Agent built with handlers: microsoft/swupdate,microsoft/apt,microsoft/simulator. [main]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2733Z [I] Health check passed. [HealthCheck]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2733Z [I] Attempting to create connection to IotHub using type: ADUC_ConnType_Device  [ADUC_DeviceClient_Create]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2733Z [I] Initializing PnP components. [ADUC_PnP_Components_Create]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2733Z [I] ADUC agent started. Using IoT Hub Client SDK 1.7.0 [AzureDeviceUpdateCoreInterface_Create]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2734Z [I] Calling ADUC_RegisterPlatformLayer [ADUC_MethodCall_Register]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2742Z [I] IoTHub Device Twin callback registered. [ADUC_DeviceClient_Create]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2742Z [I] Loading extension 'Content Downloader'. Reg file : /var/lib/adu/extensions/content_downloader/extension.json [LoadExtensionLibrary]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:07.2768Z [I] Agent running. [main]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: Error: Time:Mon Aug 22 03:35:17 2022 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:415 Failure: select failure.Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: Error: Time:Mon Aug 22 03:35:17 2022 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:833 wait_for_connection failed
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: Error: Time:Mon Aug 22 03:35:17 2022 File:/tmp/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: 2022-08-22T03:35:17.4839Z [D] IotHub connection status: 1, reason:4 [ADUC_ConnectionStatus_Callback]
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: Error: Time:Mon Aug 22 03:35:17 2022 File:/tmp/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:849 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: Error: Time:Mon Aug 22 03:35:17 2022 File:/tmp/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1437 Failed opening the underlying I/O.
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: Error: Time:Mon Aug 22 03:35:17 2022 File:/tmp/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1118 Error: io_open failed
Aug 22 03:35:38 alanhyperv AducIotAgent[184380]: Error: Time:Mon Aug 22 03:35:17 2022 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2696 failure connecting to address iothub-7kza6s.azure-devices.net.

**Comment by esha0611** [comment]
Hi @LanceLiMS , we will be adding documentation on setting up DU with a proxy server soon. In the meantime, to resolve your issue, can you share the below details on your set up?
-> Are you setting up Device Update at device level or a module?
-> Have you set 'Connection Type' as 'AIS' in your du-config file? 
-> Are you running a nested edge scenario?
-> Are you able to locate the adu.toml file in etc/aziot/identityd/config.d ?

**Comment by LanceLiMS** [comment]
Hi @esha0611 , here are the answers from Cx:
1. Device Level
2. Yes, they have already tried it.
3. No
4. Yes, they can.

**Comment by jw-msft** [comment]
@LanceLiMS https_proxy or HTTPS_PROXY environment variables need to be set and be made available to AducIotAgent process. The logic for initializing the proxy options from these env vars is here:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/utils/https_proxy_utils/src/https_proxy_utils.c#L95

It is used during initialization of the Azure IoTHub C SDK library DeviceClient during DU agent startup here where it sets the OPTION_HTTP_PROXY option:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/communication_managers/iothub_communication_manager/src/iothub_communication_manager.c#LL345C58-L345C75

For some examples of values used for https_proxy env var, check out the unit test: https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/utils/https_proxy_utils/tests/https_proxy_utils_ut.cpp#L2

Closing as this is a stale issue.  Tracking addition of the documentation for this internally.
