### ISSUE TITLE
Cannot clone repo

### ISSUE THREAD

**Issue by jelalanne** [Azure/iot-hub-device-update#217]
I cannot clone this repo, with error:

```fatal: cannot create directory at 'src/extensions/component-enumerators/examples/contoso-component-enumerator/demo/demo-devices/contoso-devices/vacuum-1/cameras/contoso-camera-serial-00000': Filename too long```

Few files are not downloaded.

**Comment by devlie** [comment]
Hi @jelalanne, since you're using PowerShell 5.1 in the other issue that you reported, I assume you're trying this on Windows. Windows has certain limitation on file path length; were you perhaps trying to clone the repo under a very deep subdirectory or using a very long root folder name? Can you try cloning it somewhere closer to the root of your drive? 

For example, I can reproduce this by cloning to somewhere deep:

```powershell
PS C:\users\leolie\Downloads\somewhereovertherainbow\deep\deeper\deepest\verydeepest\superdeepest\supersuperdeepdeepdeepest> git clone https://github.com/Azure/iot-hub-device-update.git
Cloning into 'iot-hub-device-update'...
remote: Enumerating objects: 6078, done.
remote: Counting objects: 100% (496/496), done.
remote: Compressing objects: 100% (274/274), done.
Receiving objects: 100% (6078/6078), 55.47 MiB | 16.08 MiB/s, done. 5582Receiving objects: 100% (6078/6078), 50.39 MiB | 16.59 MiB/s

Resolving deltas: 100% (3269/3269), done.
error: unable to create file src/extensions/component-enumerators/examples/contoso-component-enumerator/assets/contoso-virtual-vacuum-components-diagram.svg: Filename too long
error: unable to create file src/extensions/component-enumerators/examples/contoso-component-enumerator/assets/contoso-virtual-vacuum-update-flow.svg: Filename too long
fatal: cannot create directory at 'src/extensions/component-enumerators/examples/contoso-component-enumerator/demo/demo-devices/contoso-devices': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by jelalanne** [comment]
Works fine in a folder closer to root, but that's annoying... I tried to manually create it and it just seemed that it was the final folder's name that was too long, i couldn't create a folder longer 'contoso-camera-serial-0'. Maybe you might change that in your scripts?

**Comment by devlie** [comment]
It's not the folder name, but the whole path. It's also not a scripting issue but a well-known Windows limitation that can be removed by opting into [long path support](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry).

**Comment by jelalanne** [comment]
Had to deal with this once long ago... But question: was it necessary to go this deep into subfolders in the project? (real question, no sarcasm)

**Comment by devlie** [comment]
Maybe we can move the examples out of `src` folder, but that will break people's bookmark - @Nox-MSFT , something to consider?

P.S. I compared our repo to .NET runtime repo, and our longest path is not much longer than theirs :) 190 vs 196 chars.

>D:\ADU\dotnetruntime\src\coreclr\nativeaot\System.Private.CoreLib\src\System\Reflection\Runtime\TypeInfos\NativeFormat\NativeFormatRuntimeGenericParameterTypeInfoForMethods.UnificationKey.cs

> D:\ADU\iot-hub-device-update\src\extensions\component-enumerators\examples\contoso-component-enumerator\demo\demo-devices\contoso-devices\vacuum-1\cameras\contoso-camera-serial-00000\firmware.json
