### ISSUE TITLE
Cannot import module AduUpdate.psm1

### ISSUE THREAD

**Issue by jelalanne** [Azure/iot-hub-device-update#218]
Hello,

I am following tutorial https://learn.microsoft.com/en-us/azure/iot-hub-device-update/create-update

When trying to import AduUpdate.psm1, here is the result:
![image](https://user-images.githubusercontent.com/32770824/193051849-975878b1-0d5b-40e1-b408-a34a8d635b38.png)

Sorry it is in French, but it says "The given assembly name or codebase was invalid"

Powershell version is good (5.1), running in admin mode.

Thanks for helping!

**Comment by devlie** [comment]
Hi @jelalanne, I tried to reproduce that error with a few things that I suspect, but couldn't get the same error message. Let's see if we can determine whether this is an issue with our module or with the specific PowerShell setup on your box. Can you try running the following command in PowerShell and see if we can get `Bonjour!` back? If not, please share the resulting output. Thanks and sorry for the inconvenience.

```powershell
"function Hello { Write-Host `"Bonjour!`" }; Export-ModuleMember -Function Hello" | Out-File .\Hello.psm1
Import-Module .\Hello.psm1 
Hello
```

**Comment by devlie** [comment]
Also, if you happen to have PowerShell Core 7.* on your box, could you try following the tutorial there and see what happens?

**Comment by jelalanne** [comment]
Hi @devlie , thanks for your answer! It outputs nothing at all, but no error.
And I don't have powershell core (at least i don't think so, powershell is not part of my expertise), $PSVersionTable gives me 'Desktop' value for PSEdition, not Core.

**Comment by devlie** [comment]
That is weird. Do you mind sharing your OS information by running this in PowerShell?

```powershell
Get-ComputerInfo OsName,OsVersion,OsBuildNumber,OsHardwareAbstractionLayer,WindowsVersion
$PSVersionTable
```

In the meantime, there's a newer way to create import manifest using `azcli` IoT extension that we've not fully documented in our tutorial yet. The extension can be installed from [here](https://github.com/Azure/azure-iot-cli-extension#installation). The documentation can be found [here](https://learn.microsoft.com/en-us/cli/azure/iot/device-update?view=azure-cli-latest)

**Comment by jelalanne** [comment]
![image](https://user-images.githubusercontent.com/32770824/193120840-ece22dfe-5b21-4497-af39-d8dd68a76f9d.png)

Oh yes, I forgot about that method, I already used it last year if I remember well. I had a hard time finding it at that time, in the deep sides of github! I will try them tomorrow! Thanks
