### ISSUE TITLE
Bug in AduImportUpdate

### ISSUE THREAD

**Issue by jzaegel** [Azure/iot-hub-device-update#223]
I've been using the [AduImportUpdate](https://github.com/Azure/iot-hub-device-update/blob/main/tools/AduCmdlets/AduImportUpdate.psm1) commandlet.

There is an issue in the script: line ` $updateIdStr = "$($UpdateId.Provider).$($UpdateId.Name).$($UpdateId.Version)"` must be moved before populating the $fileMetaList so it can be referenced in `$blobName = "$updateIdStr/$filename"`

I moved it to line 57 and confirm it works this way.

**Comment by devlie** [comment]
Thank you for the report. Somebody else noticed the same thing and submitted PR https://github.com/Azure/iot-hub-device-update/pull/215 for this. @shiyi-peng, can you help approve that PR please?

**Comment by shiyi-peng** [comment]
> Thank you for the report. Somebody else noticed the same thing and submitted PR #215 for this. @shiyi-peng, can you help approve that PR please?

No problem. This has been approved and merged in

**Comment by jzaegel** [comment]
PR https://github.com/Azure/iot-hub-device-update/pull/215 implements the change I needed

**Comment by jzaegel** [comment]
The merged fix is wrong: the initialization of $updateIdStr has to happen before the loop at line 60, which content refrrences $updateIdStr.

All files end up in a strange <no name> folder 

![image](https://user-images.githubusercontent.com/30506549/201431321-9221924e-5517-4154-89f6-d4efface7837.png)

whereas the import manifest correctly ends up in the $updateIdStr folder

**Comment by shiyi-peng** [comment]
> The merged fix is wrong: the initialization of $updateIdStr has to happen before the loop at line 60, which content refrrences $updateIdStr.
> 
> All files end up in a strange folder
> 
> ![image](https://user-images.githubusercontent.com/30506549/201431321-9221924e-5517-4154-89f6-d4efface7837.png)
> 
> whereas the import manifest correctly ends up in the $updateIdStr folder

Hi @jzaegel , I am not sure what do you mean -  isn't the merged in commit has the initialization of $updateIdStr happening before the loop at line 60? also please feel free to post a PR too!

**Comment by devlie** [comment]
@jzaegel, I just tested the copy from `main`/`develop` branch, and it doesn't repro the `<no name>` issue anymore. Were you accidentally using an older copy somehow? You may have to manually call the below command if you're not using a new PS session:

```powershell
remove-module AduImportUpdate
```

**Comment by jzaegel** [comment]
Hi @devlie 
I juste checked on main, and the script seems right
My script references the [1.0.0 release of the script](https://raw.githubusercontent.com/Azure/iot-hub-device-update/1.0.0/tools/AduCmdlets/AduImportUpdate.psm1), which seems to have been issued before the merge.
My bad, sorry about the noise.
