### ISSUE TITLE
Please follow least privilege principle when setting default permissions for /etc/adu and containing files

### ISSUE THREAD

**Issue by ChristianBeier** [Azure/iot-hub-device-update#225]
Please check if the applied default permissions to the /etc/Adu folder and its containing files can be reduced to rw for adu only.
The default installation grants read+write access to the adu user, read access to the adu group and read access to others.
The config files contain the connection string what is sensitive data. Thus, its contents should not be readable by default to unprivileged users of the machine.

**Comment by esha0611** [comment]
@Nox-MSFT to take a look

**Comment by shiyi-peng** [comment]
This will be included for our GA release. Thanks!
