### ISSUE TITLE
ADUGroup not visible to deployment group setup on ThinkedEdge SE30 with 0.9.2-early-access

### ISSUE THREAD

**Issue by jzaegel** [Azure/iot-hub-device-update#226]
### Summary

Trying the latest updates of device-update agent and deliveryoptimization agents.
My physical device seems poperly configured, but the device class does not appear in the device update deployment group list. 

### Configuration

Physical machine: ThinkEdge SE30 (same as the one used by joproulx on https://github.com/Azure/iot-hub-device-update/issues/185)
OS: 20.04.5 LTS (Focal Fossa)
IotEdge: 1.4.1
Device update agent: deviceupdate-agent_0.9.2_20.04_amd64.deb
Delivery optimization agent : deliveryoptimization-agent_0.7.0_amd64.deb and libdeliveryoptimization_0.7.0_amd64.deb from https://github.com/microsoft/do-client/releases/download/v0.9.0/ubuntu2004_x64-packages.tar

du-config.json:

`{
  "schemaVersion": "1.1",
  "aduShellTrustedUsers": [
    "adu",
    "do"
  ],
  "iotHubProtocol": "mqtt",
  "manufacturer": "Lenovo",
  "model": "ThinkEdge SE30",
  "agents": [
    {
      "name": "Device update agent",
      "runas": "adu",
      "connectionSource": {
        "connectionType": "AIS",
        "connectionData": ""
      },
      "manufacturer": "Lenovo",
      "model": "ThinkEdge SE30"
    }
  ]
}`

Azure portal of Device Update has the public preview enabled.

### Device history

Provisioned through the DPS with TPM attestation before migrating the portal.
Original device update version: deviceupdate-agent_0.8.2_public_preview_amd64.deb

### Basic troubleshooting

The devices and the seem to run fine:
- [du-agent.20221017-040207.log](https://github.com/Azure/iot-hub-device-update/files/9803842/du-agent.20221017-040207.log)
- [iotedge-check.txt](https://github.com/Azure/iot-hub-device-update/files/9803844/iotedge-check.txt)
- [systemctl-status.txt](https://github.com/Azure/iot-hub-device-update/files/9803845/systemctl-status.txt)

Message routing (untouched) seems fine:

![image](https://user-images.githubusercontent.com/30506549/196264320-b6e37887-2d00-4802-b1b7-2d1c0ec96bd8.png)

Here is the current state of the IoTHubDeviceUpdate module twin: [ModuleIdentityTwin.json.txt](https://github.com/Azure/iot-hub-device-update/files/9803850/ModuleIdentityTwin.json.txt)

**The reported properties seem to tell that the communication between the agent and Device update is fine.** (good aduVer and doVer uploaded by the agent, recent communication date).

Here is the section that defines the tags for the deployment groups:
`    "tags": {
        "ADUGroup": "se30_canary"
    },`

Following the advice of [the Device Update troubleshooting guide](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/troubleshoot-device-update#q-im-trying-to-group-my-devices-but-i-dont-see-the-tag-in-the-drop-down-when-creating-a-group), I set the ADUGroup tag to another tag, or tried to set it null and recreate it a while after; nothing changed.

### Symptom

I'm trying to create a deployment group for this device but the tag "se30_canary" is not available:

![image](https://user-images.githubusercontent.com/30506549/196265266-b6c101b5-2a4a-468e-9ddd-79a9596576e5.png)

The two tags on the screenshot are coming from other tests. **What is expected here is to have a tag "se30_canary"**

Moreover, the device is not even visible in the default group (by device class):

![image](https://user-images.githubusercontent.com/30506549/196518093-899c87ce-230b-46b9-a069-77fbd17ddbc6.png)

### More context

I am doing the same think for AzureVms on deviceupdate-agent_0.8.2_public_preview_amd64.deb with no delivery optimisation agent installed. Groups can be created just fine, and updates can be deployed:

![image](https://user-images.githubusercontent.com/30506549/196265666-2779ef10-a2fc-427d-a07a-b3eebdc07d1a.png)

### potentially related issues

https://github.com/Azure/iot-hub-device-update/issues/156
https://github.com/Azure/iot-hub-device-update/issues/185
https://github.com/Azure/iot-hub-device-update/issues/216

**Comment by esha0611** [comment]
Hi @jzaegel, you are using the early access agent for the upcoming release and the current portal which is why your groups may not be appearing correctly. Please can you check if your group are appearing here -  [early access Azure Portal](https://portal.azure.com/?feature.adu=true&feature.canmodifystamps=true&Microsoft_Azure_Iothub=tip1&Microsoft_Azure_ADU_Diagnostic=true)?

**Comment by jzaegel** [comment]
Hi esha0611

You are right. I can see my group just fine on the new portal.
![image](https://user-images.githubusercontent.com/30506549/196551119-198bb2e3-cb7f-4d32-bda6-28007c5fcb21.png)

I mistakenly thought that the upper banner was a sign that I was on the early access portal:

![image](https://user-images.githubusercontent.com/30506549/196551561-9bc46863-d852-45e1-bca0-08bb0120a5df.png)

Thanks a lot
