### ISSUE TITLE
Device update total number of updates per instance count mismatch

### ISSUE THREAD

**Issue by ravi-mungalpara** [Azure/iot-hub-device-update#228]
Hi,

I was trying to import updates in azure IotHub. According to the [document](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-limits) Total number of updates per instance = 100 but I am able to import up to around 72-75 imports after that I started getting error saying "_Error importing update due to exceeded limit_". 

I used  GET endpoint (**https://{endpoint}/deviceupdate/{instanceId}/updates?api-version=2021-06-01-preview**) to fetch total number of updates but I am getting around 72-75 updates only. Also tried using SDK (Azure.IoT.DeviceUpdate-1.0.0-beta.3) method **_DeviceUpdateClient.GetUpdatesAsync** without passing any parameter value but still getting around 72-75 updates only.

I am not sure why I am getting limit exceeded error even though I didn't reach the limit.  Can you help me figure out what could be the issue ? I will be happy to provide more info.

**Comment by esha0611** [comment]
@rvmungalpara Investigating the issue

**Comment by alancshi** [comment]
Hi @rvmungalpara, it's probably not the most clear from the documentation, but the 100 device update limit is the total maximum number of updates, but there are other restrictions in the same document you reference that you can hit, even before you hit 100 updates. For example, the total number of update providers is 25 (meaning if you can receive a limit error with as few as 26 updates if they all have different providers). Likewise with the number of names per provider. 

That said, the error message you are getting should be specific enough for you to figure out the problem (and it seems the error message you got back seems too ambiguous). @devlie can you look into why there is such a generic message returned? @rvmungalpara if you have an operation ID for the import request, we can look specifically into this as well.

**Comment by devlie** [comment]
> Error importing update due to exceeded limit
That is just the top-level message; there should be another message in the error object that specifies which limit was exceeded.

**Comment by rvmungalpara** [comment]
@alancshi @devlie  Thanks for looking into that issue. I am using only one update provider and max 4-5 different update names during my import workflow. So I believe I am not hitting that 25 update provider/ 25 update names per provider limit. Attached more info around error message probably that could help to investigate further.

- OperationId: 97181171-4c2f-4aab-a7ee-0003ae65d7d7

<img width="295" alt="Import01" src="https://user-images.githubusercontent.com/68859394/197520788-17ebc43f-f4cb-454f-b1cd-1561e015dd0e.PNG">

- OperationId: c1b2b644-64c2-43ea-878d-665b2e0b6c80

<img width="293" alt="Import02" src="https://user-images.githubusercontent.com/68859394/197520884-054ba82a-0a61-420e-ad88-e9088179dc45.PNG">

**Comment by devlie** [comment]
@rvmungalpara thank you very much for the operationIds. We identified a bug in our import system that causes us to leave orphaned documents in database when user deletes an update very shortly after it is imported. Those orphaned documents are included by the limit calculation, causing the error you're seeing. I have manually cleaned up the database associated with your instance, and you should be able to import up to 100 updates now.

**Comment by rvmungalpara** [comment]
Thanks for looking into that issue.

**Comment by ravi-mungalpara** [comment]
@devlie Same issue we are getting on other environment that we are using for our internal testing.
OperationIds:

- 2274b580-90ba-4088-ac01-561455b027c7
- 3483ca3d-b243-432a-8783-774046aeba49
- 58dcf6e2-1e04-428f-bc20-fce72759dbec

Can you delete orphaned documents from the database ? What will be the long term solution so those orphaned document doesn't get created. Let me know something needs to be done from our side.
