### ISSUE TITLE
Where can I find the model definition for dtmi:AzureDeviceUpdate;1

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/iot-hub-device-update#23]
Where can I find the model definition for dtmi:AzureDeviceUpdate;1
Cannot access https://devicemodels.azure.com/dtmi/azuredeviceupdate-1.json

Currently I need to set dtmi:AzureDeviceUpdate;1 as my default component so the Device Update can recognize this PnP device for tagging/group support via Azure Iot Hub

**Comment by fvdnabee** [comment]
From my POV, the model definition is a concise overview of what the ADU component looks like. There is the ADU Core Interface page that you linked to, but a DTDL model definition is an unambiguous definition of what the contract of the ADU Core interfaces look like.

Additionally, having the DTDL model definition lets Azure IoT explorer determine the schema of the ADU PnP component and auto-render a user interface for it.

**Comment by esha0611** [comment]
Hi @sourabhkrishna, we have published our latest model definitions [here](https://github.com/Azure/iot-plugandplay-models/tree/main/dtmi/azure/iot). Please feel free to reopen the issue if there any other questions.
