### ISSUE TITLE
Ability to support custom model Id instead of dtmi:azure:iot:deviceUpdateModel;1

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/iot-hub-device-update#230]
Currently it is mandated for the agent to report a default modelId dtmi:azure:iot:deviceUpdateModel;1 for the ADU service to recognise the device as ADU compatible while we want our devices to report a custom pnp modelId that are hosted on our private repository. 

Is the default modelId just a one time action that we need to make our adu compatible?

Can we schedule updates on a device that reports a custom modelId and has the device update and device information components defined in its DTDL? 

Is there a plan to support custom pnp models from private repository?

**Comment by eshashah-msft** [comment]
Hi @sourabhkrishna, custom PnP models that extend the device update models can be created and used on the devices. The dtmi:azure:iot:deviceUpdatecontractModel;2 that has the device update core interface or the dtmi:azure:iot:deviceUpdateModel;2 with the device update core interface, diagnostics interface and device info interface can be used and extended. 
Please refer to this doc for [how to create custom models](https://learn.microsoft.com/en-us/azure/iot-develop/concepts-modeling-guide). 

Private models are not supported at this time. Please go to https://aka.ms/deviceupdateiot-feedback to upvote/ add this as a feature request/ suggestion.
