### ISSUE TITLE
Invalid model but compatible DU device

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/iot-hub-device-update#245]
Currently the DU service recognises a device/module enabled for DU even though it advertises a different modelId than the recommended 2pnp models. 

The replication steps would need the device to first advertise one of the compatible pnp models and post this the device advertises a custom pnp model. 

What should be the DU service behaviour? Should it cancel existing deployments and remove that device? Or allow for newer deployments to be scheduled?

**Comment by josephmsft** [comment]
If I'm understanding your question correctly, you're asking what the DU service behavior is if a device changes its modelId?

Group membership is based on tag, so as long as changing the ADUGroup tag doesn't change its value even if the modelId changes the device would remain in the same group.

Deployments are based on group, compatibility properties, and DeviceUpdate PnP interfaceId. If you switch to a new modelId (which references the PnP interfaceId), as long as none of those change, you would continue to receive the same deployments. If your new modelId references a different supported interfaceId (for example your old modelId could reference one of the preview DeviceUpdate interfaceIds, and then the new modelId could reference the general availability release interfaceId) then it's possible you would stop receiving the previous deployment and receive a new deployment (or no deployment if there is no existing deployment compatible with that new interfaceId).

Hopefully that answers your question.

**Comment by sourabhkrishna** [comment]
@josephmsft the new modelId we used was in our private repository and didn't reference any DU pnp interfaces.

**Comment by josephmsft** [comment]
Ok so you're saying that your custom modelId that doesn't implement any DU PnP interfaces (presumably it includes only your own interfaces) is still being imported as a DU device? That's not expected, I will follow up.

**Comment by sourabhkrishna** [comment]
Yes and the scenario for this to happen is when the device actually uses a DU compatible model once and post that uses a custom model. So want to understand what is the expected behaviour?

**Comment by josephmsft** [comment]
After following up the fix for this issue should have been deployed around middle of November. Is the issue still reproducible?

**Comment by eshashah-msft** [comment]
@sourabhkrishna , closing this as the fix is deployed. Please reopen or create a new issue if you are seeing the bug again.
