### ISSUE TITLE
The swupdate_handler_v2 README create custom content handler link is dead/404

### ISSUE THREAD

**Issue by SillyKeith** [Azure/iot-hub-device-update#248]
The README has a dead link for Create custom content handler.
[https://github.com/Azure/iot-hub-device-update/tree/main/src/extensions/step_handlers/swupdate_handler_v2](url)

See [How To Implement A Custom Content Handler Extension](https://github.com/Azure/iot-hub-device-update/blob/main/src/docs/agent-reference/how-to-implement-custom-update-handler.md) for more information.

Not sure where the new link is but that one gives 404.  We did find this link though for Custom Content Handler **EXTENSION**. [https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-implement-custom-update-handler.md#how-to-implement-a-custom-content-handler-extension](url)

But that page still has references to the v1 update handler vs v2..  should that page be updated too?

**New:** 
Registering SWUpdate Handler extension
To enable SWUpdate on the device, the handler must be registered to support 'microsoft/swupdate:2'.

Note that this version of SWUpdate Handler is different from the previous version published as part of the 2022 Public Preview Refresh release. The new handler is not backward compatible with previous versions. Hence, we recommend using a new **update-type ('microsoft/swupdate:2')**

Current page shows **'microsoft/swupdate:1'**
```
Device Update has previously supported four reference Device Update Agent binaries, each designed to work with only 1 Update Type:

- An agent that supports 'microsoft/swupdate:1' update type
- An agent that supports 'microsoft/apt:1' update type
- A simulator agent that supports 'microsoft/swupdate:1' update type
- A simulator agent that supports 'microsoft/apt:1' update type
```

**Comment by eshashah-msft** [comment]
Doc is updated.
