### ISSUE TITLE
./scripts/install-deps.sh: default DO branch name (v0.6.0) does not exist

### ISSUE THREAD

**Issue by arlotito** [Azure/iot-hub-device-update#25]
Hi,
I'm trying to build the agent (on a raspberry pi 4) following the [how to build](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-build-agent-code.md) guide.

I launched the script to install the dependencies:
`./scripts/install-deps.sh -a`

...and I got the error:
![image](https://user-images.githubusercontent.com/60540284/112518733-f1badc80-8d99-11eb-8a65-d4bb0c0b52cd.png)

...suggesting that the branch name "v0.6.0" does not exist in the repo https://github.com/microsoft/do-client... 
and indeed it should be "0.6.0", not "v0.6.0": https://github.com/microsoft/do-client/releases/tag/0.6.0

I then re-launched the script by forcing the do branch name to "0.6.0" as follows:
`./scripts/install-deps.sh -a --do-ref 0.6.0`

...and it worked.

Does it make sense? Thanks!

**Comment by jimson-msft** [comment]
Thanks arlotito, I've adjusted the do-client repo to also adhere to the v<SemVer> tagging convention. You should be able to utilize the install script as is now.
