### ISSUE TITLE
Unable to delete deployment group

### ISSUE THREAD

**Issue by sheshadri99** [Azure/iot-hub-device-update#261]
Hi,
There are few deployment groups, which doesnot have any devices or any deployments in it, when tried to delete those groups, the below error message is shown. Ideally we should be able to delete those groups.
Is this the expected behaviour?

Error Message:
-----------------
Group 4e63870a34774967b9ffb73505271931 could not be removed.
Status code: 400.
Detail error code: NotEmptyGroupCannotBeDeleted
Details: Cannot delete Group which is not empty. Please delete or retag the agents before deleting the group.

**Comment by sheshadri99** [comment]
Hi @alancshi, i could see there are no devices in the group when viewed through portal. 
Checked through cli as well, i am getting empty list as response.

**Comment by alancshi** [comment]
@sheshadri99  that is strange, can you share your account/instance and group name? @josephmsft @Olee2021 can you please help with this investigation?

**Comment by josephmsft** [comment]
I'll take a look, please do tell us the account and instance. I'll see if I can find it from the group name alone but that will take longer.

**Comment by josephmsft** [comment]
Ok I have determined the issue. You have 1 unhealthy device that is still tagged as part of this group. Because it is unhealthy it is not listed in the device queries you're running. The deviceId is "4e63870a34774967b9ffb73505271931" and moduleId is "FirmwareModule". If you delete this device from your hub you should be able to delete the group. You can see what unhealthy devices you have by querying for unhealthy devices, although for now that API is not returning group information. I will follow up on how we can improve this scenario.

**Comment by sheshadri99** [comment]
For one particular device group, when viewed from portal it has no deployments, but when tried with api it says group has 1 active deployment, when tried to delete the deployment via api, it is returning 204 and deployment is not getting deleted.

DeviceId: ACCE000000000000A20000000F23D602

**Comment by saumya093** [comment]
We have noticed another issue where in we are unable to delete a group as the error messages says that there are active deployments in the group, even though via the portal the deployment is not visible.
DELETE `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId?api-version=2022-10-01`

![image](https://user-images.githubusercontent.com/19192656/205668298-ecf461f0-245f-4f61-9c89-da20ea064519.png)

**On calling the get deployments by group Id API we get an empty list:**
GET `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId/deployments?api-version=2022-10-01`

![image](https://user-images.githubusercontent.com/19192656/205667073-2593a2e3-b610-4ddf-b647-55aeb9c90edf.png)

**However on calling the GET group details API, we get the deployment Id in the response:**
GET `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId?api-version=2022-10-01` 

![image](https://user-images.githubusercontent.com/19192656/205666107-10220ba5-7da0-4b97-a397-781a2ec22e96.png)
When we try to delete this deployment using API:
DELETE `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId/deployments/ce681527-3101-47d6-853c-b9c1737fb5fa/?api-version=2022-10-01`
We get 204 No Content but post that when we try to delete the group again we still get `400 BadREquest` with error as: 
```json
{
    "error": {
        "code": "GroupWithActiveDeploymentCannotBeDeleted",
        "message": "Cannot delete Group with an Active deployment. Please delete or cancel the deployment before deleting the group."
    }
}
```

**Comment by josephmsft** [comment]
> Is this the expected behaviour, having unhealthy devices being tagged to a group stops us from deleting them. Is untagging the device from group not sufficient to delete group? Can you share if there is documentation about health of devices?

Untagging the unhealthy device should also work to be able to delete the group.

**Comment by josephmsft** [comment]
> > Is this the expected behaviour, having unhealthy devices being tagged to a group stops us from deleting them. Is untagging the device from group not sufficient to delete group? Can you share if there is documentation about health of devices?
> 
> Untagging the unhealthy device should also work to be able to delete the group.

https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-check?tabs=portal is the documentation for agent check

**Comment by josephmsft** [comment]
> ACCE000000000000A20000000F23D602

What is the groupId that is failing to be deleted?

**Comment by josephmsft** [comment]
> We have noticed this issue with another device group as well where in we are unable to delete a group as the error messages says that there are active deployments in the group, even though via the portal the deployment is not visible. DELETE `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId?api-version=2022-10-01`
> 
> ![image](https://user-images.githubusercontent.com/19192656/205668298-ecf461f0-245f-4f61-9c89-da20ea064519.png)
> 
> **On calling the get deployments by group Id API we get an empty list:** GET `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId/deployments?api-version=2022-10-01`
> 
> ![image](https://user-images.githubusercontent.com/19192656/205667073-2593a2e3-b610-4ddf-b647-55aeb9c90edf.png)
> 
> **However on calling the GET group details API, we get the deployment Id in the response:** GET `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId?api-version=2022-10-01`
> 
> ![image](https://user-images.githubusercontent.com/19192656/205666107-10220ba5-7da0-4b97-a397-781a2ec22e96.png) When we try to delete this deployment using API: DELETE `https://aduEndpoint/deviceUpdate/aduInstance/management/groups/groupId/deployments/ce681527-3101-47d6-853c-b9c1737fb5fa/?api-version=2022-10-01` We get 204 No Content but post that when we try to delete the group again we still get `400 BadREquest` with error as:
> 
> ```json
> {
>     "error": {
>         "code": "GroupWithActiveDeploymentCannotBeDeleted",
>         "message": "Cannot delete Group with an Active deployment. Please delete or cancel the deployment before deleting the group."
>     }
> }
> ```

I have investigated and this is due to a bug in the service. Your group currently has no subgroups, but it does have a deployment. In this scenario with no subgroups we are not correctly updating the group record to remove the active deployment when DELETE deployment is called. I will work on a fix and it should be deployed by late next week, after which you should be able to fully delete the deployment by calling DELETE deployment.

**Comment by josephmsft** [comment]
This was deployed the following week from my last comment. Closing this issue.
