### ISSUE TITLE
The Import Manifest of Tutorial on Raspberry Pi

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iot-hub-device-update#27]
Hi,
I trying to do [the tutorial of Raspberry Pi](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-raspberry-pi#import-update) with release [0.6.0](https://github.com/Azure/iot-hub-device-update/releases/tag/0.6.0).
But I don't know parameters to create an Import Manifest.
Could you tell me example of parameters or send the manifest file?

**Comment by KunYi** [comment]
I have some experience 
this my import manifest file
{
  "updateId": {
    "provider": "UWINGS",
    "name": "raspberrypi3b",
    "version": "0.0.2"
  },
  "updateType": "microsoft/swupdate:1",
  "installedCriteria": "0.0.2",
  "compatibility": [
    {
      "deviceManufacturer": "UWINGS",
      "deviceModel": "RefDevice"
    },
    {
      "deviceManufacturer": "ADUTeam",
      "deviceModel": "RefDevice"
    }
  ],
  "files": [
    {
      "filename": "adu-update-image-raspberrypi3.swu",
      "sizeInBytes": 98631168,
      "hashes": {
        "sha256": "SV5bYr+EVPUt2yT47/XaXbrYG2cp30+p5lTWKJ7JihI="
      }
    }
  ],
  "createdDateTime": "2021-03-24T05:07:58.2211123Z",
  "manifestVersion": "2.0"
}
this have my own image and update logs

**Comment by matsujirushi** [comment]
Hi @KunYi ,
Thanks for information.
I could upload.
![image](https://user-images.githubusercontent.com/8079404/112630365-d83c9200-8e78-11eb-9ed0-633a086f530a.png)
