### ISSUE TITLE
Howto: Block updates until user confirmation

### ISSUE THREAD

**Issue by Christian-e-S** [Azure/iot-hub-device-update#286]
Dear Device Update Team and Experts,

we are developing a critical IoT Application in the healthcare field, and want to use IoT-Hub Device Update for OTA Updates.

Since this is a critical application, we have to prevent system interruptions caused by updates (i.e., re-boot after an image based A/B update) while the device is in active use.

The optimal solution would be to show a notification to the user like "A new update is available. Please press APPLY whenever you are ready to apply the update."

How would I extend the agent (using an SWUpdate handler) to realize such a functionality?

Thank you in advance!

**Comment by eshashah-msft** [comment]
Hi @Christian-e-S, we have heard this request from other users and are tracking this for our long-term roadmap. 
However, if you need this consent feature sooner, you can refer to our agent documentation to create a [custom handler](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-implement-custom-update-handler.md) or use a [script](https://github.com/Azure/iot-hub-device-update/tree/main/src/extensions/step_handlers/script_handler) to enable this feature. Please email our discussion alias at [deviceupdatedisc@microsoft.com](mailto:deviceupdatedisc@microsoft.com) to request guidance on modifying your agent or contributing to the DU repo.

**Comment by eshashah-msft** [comment]
@Christian-e-S Closing this issue as there are no update. Please feel free to open a new issue if needed or a new PR if you would like to contribute to the Device update project.
