### ISSUE TITLE
Automatic insertion of ADUGroup

### ISSUE THREAD

**Issue by arminghasemazar** [Azure/iot-hub-device-update#304]
Hi.

I'm wondering if there is any automated way to add `"ADUGroup": "ubuntu"` tag into the module twin of IoTHubDeviceUpdate? We are using DPS to provision our devices automatically. We try to configure "Initial Device Twin State" as follows:
![image](https://user-images.githubusercontent.com/13336488/210248516-c64c32c6-8ca9-4478-99e7-2e8a65ade4bb.png)

However, the device is added to Default Group and not ubuntu group, which is expected since ADUGroup tag is not in module twin and instead is in device twin. 
![image](https://user-images.githubusercontent.com/13336488/210248668-4c622b2b-b670-4aae-bf2d-7fbb63fce7a2.png)

We also tried to create a layered module twin configuration deployment in IoT hub. However, it only applies to `properties` section of any module twin not `tags` section.
![image](https://user-images.githubusercontent.com/13336488/210249067-cef1bb55-971f-4b24-a973-c68d4dba582b.png)

Also, tried to use Azure Functions within DPS for provisioning any new device. However, the issue is that Azure Function is triggered immediately after the request is sent from device to DPS and the IoTHubDeviceUpdate module may not be ready/installed yet in the device.

Would be nice to hear your thoughts.

**Comment by yuvalg-MSFT** [comment]
@vimeht Hey, would be good to get your opinion about the issue here, thx.

**Comment by OscarLee-MSFT** [comment]
Hello @arminghasemazar, thank you for your input. Closing this issue and tracking via: https://github.com/Azure/iot-hub-device-update/discussions/392 for future releases. For other users, please upvote if this is a feature you would like to see supported as this helps us prioritize it in future releases.
