### ISSUE TITLE
How to create .swu file?

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iot-hub-device-update#32]
Hi,
Could you tell me steps for how to create .swu file?

[adu-update-image-raspberrypi3-0.6.5073.1.swu](https://github.com/Azure/iot-hub-device-update/releases/download/0.7.0-rc1/adu-update-image-raspberrypi3-0.6.5073.1.swu)

**Comment by ValOlson** [comment]
Hello,

Thank you for reaching out to us. Here are some links to get started on how to create a .swu file:
1. https://sbabic.github.io/swupdate/
2. https://sbabic.github.io/swupdate/signed_images.html

Were you looking for our recipes on how were created the image file?

**Comment by matsujirushi** [comment]
Hi @ValOlson ,
This is exactly.
Thanks for information.
