### ISSUE TITLE
compile error with iot-hub-device-update 1.0.1: 'IOTHUB_CLIENT_CONNECTION_QUOTA_EXCEEDED' not handled in switch

### ISSUE THREAD

**Issue by JoergZeidler** [Azure/iot-hub-device-update#346]
Hi,
during integration the provided release 1.0.1, i get an compile error in the new communication manager.
I use a  gcc compiler version 11.

Compiler Log Message:
`/src/communication_managers/iothub_communication_manager/src/iothub_communication_manager.c:685:9: error: enumeration value 'IOTHUB_CLIENT_CONNECTION_QUOTA_EXCEEDED' not handled in switch [-Werror=switch]
|   685 |         switch (g_connection_status_reason)
|       |         ^~~~~~
| cc1: all warnings being treated as errors`

I have provided a possible solution in this PR: https://github.com/Azure/iot-hub-device-update/pull/345

**Comment by jw-msft** [comment]
Please see comment therein: https://github.com/Azure/iot-hub-device-update/pull/345#issuecomment-1387602218

Agent is pinned at an older release of azure-iot-sdk-c and that enum value was added in a later release and that enum value was introduced in a later release of azure-iot-sdk-c:  [LTS_07_2022_Ref02](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_07_2022_Ref02) 
 [1.9.1](https://github.com/Azure/azure-iot-sdk-c/releases/tag/1.9.1)

You should be able to fix it by installing the older version--one way is via `./scripts/install-deps.sh --install-azure-iot-sdk`
that uses this older version:
azure_sdk_ref=LTS_07_2021_Ref01
as seen here https://github.com/Azure/iot-hub-device-update/blob/main/scripts/install-deps.sh#L46

Do let us know if you have particular needs for using the newer version of azure-iot-sdk-c as it may help prioritize moving the device udpate agent to a newer version, which is planned.

**Comment by JoergZeidler** [comment]
yes it's right. We using latest LTS sdk revision [LTS_07_2022_Ref02](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_07_2022_Ref02) for building iot-hub-device-update.  I will change my PR based on proposal from https://github.com/Azure/iot-hub-device-update/pull/345#discussion_r1080851828

**Comment by JoergZeidler** [comment]
closed, fixed in PR https://github.com/Azure/iot-hub-device-update/pull/345
