### ISSUE TITLE
iot-hub-device-update v1.0.1: swupdate handler v2 don't use custom script handling in CancelApply and Apply step

### ISSUE THREAD

**Issue by JoergZeidler** [Azure/iot-hub-device-update#348]
Hi,
during integration and testing iot-hub-device-update v1.0.1 with swupdate handler v2, i found a possible mistake in CancelApply and Apply step. Both steps won't use the provided custom script. 

I provided a possible solution for this bug in this PR: https://github.com/Azure/iot-hub-device-update/pull/347

**Comment by Nox-MSFT** [comment]
PR approved. @JoergZeidler , thanks so much for your contribution!
