### ISSUE TITLE
DU Agent does not update Twin when credentials are refreshed

### ISSUE THREAD

**Issue by agreentree-dmc** [Azure/iot-hub-device-update#367]
## Expected Behavior
Using x509 certificates as Device Authentication Type. When certificates are periodically rotated by Azure Identity Service, the DU Agent re-establishes it's connection with the IoT Hub.  The DU Agent **_should_** refresh Module Identity Twin when connection is re-established and remain in healthy state without needing to restart the service.

## Current Behavior
Using x509 certificates as Device Authentication Type. When certificates are periodically rotated by Azure Identity Service, the DU Agent re-establishes it's connection with the IoT Hub.  The DU Agent **_does not_** update the Module Identity Twin which leaves the device in an unhealthy, not updatable state. Service must be restarted to get DU Agent back to healthy state.

## Steps to Reproduce
1. Install Azure Identity Service (AIS) 1.4.0.
2. Configure AIS to use self-signed certificates issued from an EST Server (as described in this tutorial: https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-configure-est-server?view=iotedge-1.4). Set the `threshold` property under `[provisioning.attestation.identity_cert.auto_renew]` in the aziot config.toml file to be 10% to observe frequent certificate rotations (as described in suggestion 2 at the end of the 'Test Certificate Renewal' section of the EST Server Tutorial). 
3. Configure AIS to use 'DPS provisioning with X.509 certificate' method.
4. Install ADU 1.0.1 and configure it to obtain credentials from AIS. 
5. Observer the Module Identity Twin in portal just after the DU agent successfully starts for the first time.
6. Wait for certificate renewal. 
7. Observe the Module Identity Twin in portal after the certificate has rotated.

### Device Information
* Host OS: NI Linux Real-Time 9.1 (hardknott)
* Architecture: amd64
* Provisioning Method: DPS Provisioning with X.509 certificate
* DU Agent Version: 1.0.1

## Logs
Main log that I think shows the behavior when the device certificate is refreshed and the connection is re-established (towards the bottom): 
[du-agent.20230127-162704.log](https://github.com/Azure/iot-hub-device-update/files/10539669/du-agent.20230127-162704.log)

Zip of all logs in the /var/log/adu folder for reference: 
[du_logs.zip](https://github.com/Azure/iot-hub-device-update/files/10539677/du_logs.zip)

## Additional Information
_Screenshots after certificate rotation_
DU Agent connection status:  
![image](https://user-images.githubusercontent.com/60200297/215587826-b46f30b0-c871-4d2e-83a7-1b21d62fa1d0.png)
DU Agent Module Identity Twin:  
![image](https://user-images.githubusercontent.com/60200297/215588080-72688264-fea0-479a-88b6-d8fcdb0641b3.png)
Unhealthy status reported by ADU:  
![image](https://user-images.githubusercontent.com/60200297/215588488-58c67767-a52b-447a-821d-4fc2ffbec4b7.png)

**Comment by Nox-MSFT** [comment]
@JoergZeidler , thank you for PR. I believed this solve your issue? 
We will revisit this again once we integrated the newer version of the IoT Hub Device Client C SDK.
