### ISSUE TITLE
Adding explicit link to libatomic. PR provided.

### ISSUE THREAD

**Issue by neonsoftware** [Azure/iot-hub-device-update#387]
## Expected Behavior

This project compiles on OpenWRT MIPS Musl.  

## Current Behavior

On OpenWRT MIPS Musl the toolchain requires an explicit link to libatomic.
In many other scenarios this is just implicit. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Compile on OpenWRT 21 + Musl for MIPS32

## Device Information
* OpenWRT 21
* MIPS 32
* Provisioning Method: TPM
*DU Agent Version v1.0.1

## Additional Information

A PR is available at #386 
Normal compiler scenarios should not, normally, be affected by the added explicit link.

**Comment by neonsoftware** [comment]
@Nox-MSFT I will be able to do fixes for this at the same time with other PRs already in progress.

**Comment by jw-msft** [comment]
I added comment to the PR. If can't get to it, will try to find some time next week to address.

**Comment by neonsoftware** [comment]
Thanks, I might, probably, be on it today/tomorrow.

**Comment by jw-msft** [comment]
@neonsoftware Running some pipelines on it on a branch under Azure org so that it is authorized to pull from the container registry and will merge once they pass.

**Comment by jw-msft** [comment]
@neonsoftware pipeline passed. Feel free to merge the PR.

**Comment by neonsoftware** [comment]
> @neonsoftware pipeline passed. Feel free to merge the PR.

@jw-msft Sorry, do you mean that there is a way for me to merge the PR, as non-contributor ? 
Thanks in advance for the info.

**Comment by jw-msft** [comment]
@neonsoftware It is merged with https://github.com/Azure/iot-hub-device-update/commit/9452631febe0018e3d108c906eb2c1d0fd555469
We're looking into bot to auto-merge these in the future.
