### ISSUE TITLE
Two remaining usages of _Bool in generated error types. PR Provided

### ISSUE THREAD

**Issue by neonsoftware** [Azure/iot-hub-device-update#391]
## Expected Behavior

Compilation does not require anymore type `_Bool`. (Which was already massively removed in #268 )  

## Current Behavior

Some compiler scenarios using Musl do not provide `_Bool` aliases out-of-the-box.
In such scenarios the addition of manual type aliases are required.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Compile on OpenWRT 21 + Musl + MIPS32
2. You will encounter compilation error `Type _Bool unknown` 

## Device Information
* OpenWRT 21
* MIPS 32
* Provisioning Method: TPM
* DU Agent Version v1.0.1

## Additional Information

A PR is available at #390 .

**Comment by neonsoftware** [comment]
@Nox-MSFT I will be able to do fixes for this at the same time with other PRs already in progress.

**Comment by jw-msft** [comment]
Approved the PR and  thanks for contribution.
Quite interested in the use of Musl instead of glibc as well as MIPS32.  Sounds like you mostly got it working?

**Comment by neonsoftware** [comment]
> Approved the PR and thanks for contribution.

Thank you.

--------

> Quite interested in the use of Musl instead of glibc as well as MIPS32.

**On MIPS32**

- The custom board was developed years ago on an Archos MIPS32 due to the project's specific powerline requirements. (the board was based on previous solutions, and the processor naturally mostly targets powerline basic routers / access point). At creation the board was delivered by the with out-of-the-box OpenWRT BSP.
- Very stable operation. Thousands of remote installations exist in a **non-Azure** IoT context. Hundreds added each month.

**On Musl instead of glibc**

- OpenWRT supports, with significant efforts and feedbacks, such Archos boards due to widespread presence of routers based on it. 
- The experience of this project, on the field, in the previous years, has been that OpenWRT has proven stable, low-footprint, simple, and extensible. 
- The use of Musl is **just** due to OpenWRT, which has switched to it by **default** in 2019 (actually not from glibc, but rather from uClibc). [OpenWRT releases and compilers](https://en.wikipedia.org/wiki/OpenWrt#Releases)

---------

>  Sounds like you mostly got it working?

- Current effort is porting (including retro-compatibility) the system to use Azure IoT.
- Yes, currently working. Pre-prod is using 100% Azure. **Non-edge**. Device use just SDK + Azure Device update.
- In touch with Azure IoT teams along this journey.

---------

Please let me know if any information was unclear, or if other aspects could help understand the scenario or requirements.
Thank you.

**Comment by jw-msft** [comment]
merged https://github.com/Azure/iot-hub-device-update/pull/390
