### ISSUE TITLE
AMQP support? AMQP used E2E for our iot-edge/iot-hub/dps but ADU only supports MQTT...

### ISSUE THREAD

**Issue by RichardHubertPtw** [Azure/iot-hub-device-update#394]
Hi, we leverage Azure DPS/iot-hub/iot-edge in MedTec where connections/protocols are under particular scrutiny. AMQP is important for MedTec also for its store+forward and seamless token update features (to name a few). Long story short: We (and our customers) prefer AMQP and all the above mentioned Azure services recommend/support AMQP. When will ADU support AMQP?

Thank you -- in particular for ADU, a crucial addition to the stack.

**Comment by jw-msft** [comment]
DU currently uses [iot plug and play](https://docs.microsoft.com/azure/iot-pnp/overview-iot-plug-and-play) and the azure-iot-sdk-C library, where its Device Client with AMQP does _not_ support PnP as can be seen in this table:
https://github.com/Azure/azure-iot-sdk-c#device-client-sdk

Therefore, DU Agent currently only supports MQTT and MQTT/WS since those are the only ones that support PnP.

**Comment by RichardHubertPtw** [comment]
Thank you for the clear answer. Besides wanting to have common (AMQP) transport across our IoT-stack (to reduce the deployment configuration complexity), we also noticed that the the MQTT (in contrast to AMQP) disconnects to the IoT-Edge Gateway each time an access token is restored (once an hour). This disconnect/reconnect drops the connection and blocks the data transport for roughly 700ms each time. Since we may be doing critical (MedTec) machine measurements during this "connection drop", we are concerned. AMQP handles this with store-and-forward and a more transparent token refresh. Any thoughts? Thanks again for the clarity on your technical constraints using AMQP.

**Comment by eshashah-msft** [comment]
Hi @RichardHubertPtw, I believe the SAS token refresh can be configured as described in this doc: https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-dev-guide-sas?tabs=node

Closing this issue as no action is planned right now. Feel free to open a new issue or add this in the [Device Update discussion](https://github.com/Azure/iot-hub-device-update/discussions) for us to track as feature request for future releases.
