### ISSUE TITLE
Two remaining hardcoded adu-shell paths used instead of ADUSHELL_FILE_PATH,

### ISSUE THREAD

**Issue by neonsoftware** [Azure/iot-hub-device-update#404]
## Expected Behavior

The user-defined CMake compilation variable `ADUSHELL_FILE_PATH` defines the path of adu-shell to be uses **all-around** the software.

## Current Behavior

In two occurrencies, the system does not use the value `ADUSHELL_FILE_PATH`.
Instead it uses a fixed path `"/usr/lib/adu/adu-shell"`

Here

https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/src/adu-shell/inc/adushell_const.hpp#L16

and here

https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/src/platform_layers/linux_platform_layer/src/linux_adu_core_exports.cpp#L78

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Define a value for CMake's `ADUSHELL_FILE_PATH` to a value different than `"/usr/lib/adu/adu-shell"`, and move the binary to the new location.  
2. Use the ADU as normal.
3. You will see that when actively operating the system will report a message of type  "`Binary not found at /usr/lib/adu/adu-shell", while the variable defined a different path.

### Device Information
* OpenWRT 21
* MIPS 32
* Provisioning Method: TPM
* DU Agent Version v1.0.1

## Additional Information

This time I do not actually have an open PR or a nice upstream patch.
(Our patch was a low-effort fix that was not as elegant as the natural fix probably be.)

**Comment by neonsoftware** [comment]
@jw-msft and @Nox-MSFT for this I do not have actually a ready-to-upstream patch.

**Comment by neonsoftware** [comment]
Tagging https://github.com/Azure/iot-hub-device-update/pull/403 which operates on a nearby area.

**Comment by neonsoftware** [comment]
@jw-msft Done

**Comment by jw-msft** [comment]
Should be fixed in develop branch.
