### ISSUE TITLE
show-demo-components.sh is missing 

### ISSUE THREAD

**Issue by iotarchitect** [Azure/iot-hub-device-update#405]
In [this article](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-howto-proxy-updates) there is a step to run show-demo-components.sh, however, I see no trace of this file anywhere here. Expectation is that the file should be present or documentation updated with other steps.

**Comment by eshashah-msft** [comment]
Hi @iotarchitect , taking a look at the above issue

**Comment by eshashah-msft** [comment]
Removed command. Docs should be updated by tomorrow. Closing the issue as resolved.
