### ISSUE TITLE
Missing NUL for null-terminated string

### ISSUE THREAD

**Issue by ccli8** [Azure/iot-hub-device-update#406]
The issue can reproduce just by code review. Check the code fragment below:
https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/utils/jws_utils/src/jws_utils.c#L214-L222

`tempHeader` should append with `NUL` to be a valid null-terminated string:
```C
strncpy(tempHeader, jws, headerLen);
tempHeader[headerLen] = '\0';
```

**Comment by jw-msft** [comment]
will add unit test to cover this particular issue. Across the board will replace all instances of strn*xxx and replace with equivalent safer ones (possibly STRING_*). Also, looking for gcc compiler flag or static analysis to add to pipeline to prevent future occurences.

**Comment by jw-msft** [comment]
I opted for a more targeted fix to start with.  Will address the rest of code base in separate PR(s).

**Comment by jw-msft** [comment]
Thanks for the report, @ccli8. Resolved with this commit:
https://github.com/Azure/iot-hub-device-update/commit/e40b7e3d611d7fe9d6af99af325eb550ff0d5c49
