### ISSUE TITLE
Large URL generated by ADU instance

### ISSUE THREAD

**Issue by ravi-mungalpara** [Azure/iot-hub-device-update#407]
Hello,

Adding link of the [issue ](https://github.com/Azure/iot-hub-device-update/issues/73)reported previously. We are having issues with the URL generated by ADU instance while doing integration with our firmware. Here are few questions

- Any plan to shorten URL generated by ADU.
- How to enable HTTPs support

Here is the example of the URL generated by ADU.

"fileUrls": {
                        "f9cacd0a31461c4e3": "http://iot-services-adu-instance-01--iot-services-adu-dev.b.nlu.dl.adu.microsoft.com/westus2/iot-services-adu-instance-01--iot-services-adu-dev/66b18a2ed55e4102a9867009347bc1a0/Release_63.0.0.bin"
                    }

**Comment by eshashah-msft** [comment]
+ @devlie + @andrewbrownmsft for the questions above

**Comment by andrewbrownmsft** [comment]
We do not have any plans today to shorten the URLs, as this has not been a common request or blocker so far. Is your requirement for a shorter URL identical to what's listed in the issue you linked? Or is this a different scenario? If you can provide exactly what you need in terms of URL length (and details about your scenario), that would help our team explore options.

In regards to https support for update downloads, today we use signatures to detect and reject any tampering with update files, as documented [here](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-security). Is your request for https related to having confidential information contained in your update payload?

**Comment by ravi-mungalpara** [comment]
> Is your requirement for a shorter URL identical to what's listed in the issue you linked?
- Apologies for the confusion. It was reported by us only and just wanted to check if there is any update in recent time.

> Is your request for https related to having confidential information contained in your update payload?

- Generally our firmware makes secure connection calls so was curious to know if there is any plan to enable Http(s) support for the same.

**Comment by ravi-mungalpara** [comment]
@andrewbrownmsft Do we have any workaround for the URL as our firmware has around 100 character limitations due to memory constraint.

**Comment by devlie** [comment]
> @andrewbrownmsft Do we have any workaround for the URL as our firmware has around 100 character limitations due to memory constraint.

This not ideal, but if you pick 3-character long account and instance id (`abc` in the example below) and 6-character long file name (`a.bin` in the example below, but extension is optional), that will bring down the download URL to 100 chars.

http://abc--abc.b.nlu.dl.adu.microsoft.com/westus2/abc--abc/66b18a2ed55e4102a9867009347bc1a0/a.bin

**Comment by andrewbrownmsft** [comment]
> Generally our firmware makes secure connection calls so was curious to know if there is any plan to enable Http(s) support for the same.

For ensuring that files are downloaded unmodified (integrity), we believe our existing approach provides strong security. If there is a specific requirement for the files not being obtainable by other parties (e.g. they contain confidential information), we are looking at several options, including encryption of the content by the service and decryption on the client. Would that address your concerns?

**Comment by andrewbrownmsft** [comment]
Hi. We are reviewing our backlog of GitHub issues and are planning to close any that have not had any new activity in some time. Please let us know if there is any further assistance we can provide here; otherwise I will go ahead and close this item next week. Thanks!

**Comment by andrewbrownmsft** [comment]
Per above, I'm going to close this issue, but please let us know if there is any further assistance we can provide. Thanks!

**Comment by friesendrywall** [comment]
The url's are too long, this obviously has something to do with something other than security.
