### ISSUE TITLE
Health-check fails and blocks the update of an installed deviceupdate-agent package on a IoT Edge Device

### ISSUE THREAD

**Issue by shaeussler** [Azure/iot-hub-device-update#414]
On a IoT Edge device (iotedge 1.4.9) with DPS provisioning with TPM the command "sudo /usr/bin/AducIotAgent --enable-iothub-tracing --health-check --log-level 0" fails with the error message "Invalid connection info" and blocks the update deviceupdate-agent package, see https://github.com/Azure/iot-hub-device-update/blob/e6c848a911643008bc51c588cacf0507be5d80b2/packages/debian/postrm#L95

## Expected Behavior
The health-check should work

## Current Behavior
The health-check fails and blocks the deviceupdate-agent package update.

## Steps to Reproduce
1. Install iotedge 1.4.9 on a PC with TPM 2.0 and configure DPS provisioning with TPM 
2. Run "sudo /usr/bin/AducIotAgent --enable-iothub-tracing --health-check --log-level 0" on the IoT Edge device

### Device Information
* Host OS: Ubuntu 18.04 
* Architecture amd64
* Provisioning Method: DPS provisioning with TPM 
* DU Agent Version: 1.0.0

## Logs
```
2023-03-02T13:55:56.5203Z 5887[5887] [D] Log file created: /var/log/adu/du-agent.20230302-135556.log [zlog_init]
2023-03-02T13:55:56.5209Z 5887[5887] [I] Failed to provision a connection string from eis, Failed with error EISErr_InvalidJsonRespErr on service EISService_KeyService [GetConnectionInfoFromIdentityService]
2023-03-02T13:55:56.5209Z 5887[5887] [E] Invalid connection info. [HealthCheck]
2023-03-02T13:55:56.5209Z 5887[5887] [I] Health check failed. [HealthCheck]
2023-03-02T13:55:56.5209Z 5887[5887] [I] Agent exited with code 1 [main]
2023-03-02T13:55:56.5209Z 5887[5887] [I] Agent is shutting down with signal 0. [ShutdownAgent]
2023-03-02T13:55:56.5209Z 5887[5887] [I] De-initializing command listener thread [UninitializeCommandListenerThread]
2023-03-02T13:55:56.5210Z 5887[5887] [I] ADUC agent stopping [AzureDeviceUpdateCoreInterface_Destroy]
```

**Comment by jw-msft** [comment]
@shaeussler Only running as adu user is supported. Is there a reason you need to run it as root uid 0?  can also use sudo -u adu ...

**Comment by shaeussler** [comment]
@jw-msft Thanks for the response. I did not configure the edge identity service. 
I installed the IoT Edge using the following instructions: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-linux-tpm?view=iotedge-1.4&tabs=physical-device%2Cubuntu
When I now try to update deviceupdate-agent with the command "sudo apt-get install deviceupdate-agent" I get the error message

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  deviceupdate-agent
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 1915 kB of archives.
After this operation, 87.0 kB of additional disk space will be used.
(Reading database ... 59359 files and directories currently installed.)
Preparing to unpack .../deviceupdate-agent_1.0.2_amd64.deb ...
******************** Running /var/lib/dpkg/tmp.ci/preinst upgrade 1.0.0 ***********************
Existing DU Agent version: 1.0.0
Unpacking deviceupdate-agent (1.0.2) over (1.0.0) ...
******************** Running /var/lib/dpkg/info/deviceupdate-agent.postrm upgrade 1.0.2 ***********************
[postrm upgrade 1.0.2] Perform new ADU agent health validation.
AducIotAgent version:
1.0.2
2023-03-13T06:47:47.3901Z 8058[8058] [D] Log file created: /var/log/adu/du-agent.20230313-064747.log [zlog_init]
Error: Time:Mon Mar 13 06:47:47 2023 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:353 Failure: connect failure 111.
Error: Time:Mon Mar 13 06:47:47 2023 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:829 lookup_address_and_connect_socket failed
Error: Time:Mon Mar 13 06:47:47 2023 File:/tmp/azure-iot-sdk-c/deps/uhttp/src/uhttp.c Func:uhttp_client_open Line:1134 opening xio failed
2023-03-13T06:47:47.3903Z 8058[8058] [I] Failed to provision a connection string from eis, Failed with error EISErr_ConnErr on service EISService_IdentityService [GetConnectionInfoFromIdentityService]
2023-03-13T06:47:47.3904Z 8058[8058] [E] Invalid connection info. [HealthCheck]
2023-03-13T06:47:47.3904Z 8058[8058] [I] Health check failed. [HealthCheck]
2023-03-13T06:47:47.3904Z 8058[8058] [I] Agent exited with code 1 [main]
2023-03-13T06:47:47.3904Z 8058[8058] [I] Agent is shutting down with signal 0. [ShutdownAgent]
2023-03-13T06:47:47.3904Z 8058[8058] [I] De-initializing command listener thread [UninitializeCommandListenerThread]
2023-03-13T06:47:47.3905Z 8058[8058] [I] ADUC agent stopping [AzureDeviceUpdateCoreInterface_Destroy]
[postrm upgrade 1.0.2] ERROR: ADU Agent (/usr/bin/AducIotAgent) validation failed. Aborting the upgrade.
dpkg: warning: old deviceupdate-agent package post-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
******************** Running /var/lib/dpkg/tmp.ci/postrm failed-upgrade 1.0.0 ***********************
[postrm failed-upgrade 1.0.0] Perform new ADU Agent health validation.
Attempting to fix-up /usr/lib/adu/adu-shell and /etc/adu after postrm upgrade failure from 1.0.0 ...
AducIotAgent version:
1.0.2
2023-03-13T06:47:47.4122Z 8064[8064] [D] Log file created: /var/log/adu/du-agent.20230313-064747.log [zlog_init]
Error: Time:Mon Mar 13 06:47:47 2023 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:353 Failure: connect failure 111.
Error: Time:Mon Mar 13 06:47:47 2023 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:829 lookup_address_and_connect_socket failed
Error: Time:Mon Mar 13 06:47:47 2023 File:/tmp/azure-iot-sdk-c/deps/uhttp/src/uhttp.c Func:uhttp_client_open Line:1134 opening xio failed
2023-03-13T06:47:47.4123Z 8064[8064] [I] Failed to provision a connection string from eis, Failed with error EISErr_ConnErr on service EISService_IdentityService [GetConnectionInfoFromIdentityService]
2023-03-13T06:47:47.4124Z 8064[8064] [E] Invalid connection info. [HealthCheck]
2023-03-13T06:47:47.4124Z 8064[8064] [I] Health check failed. [HealthCheck]
2023-03-13T06:47:47.4124Z 8064[8064] [I] Agent exited with code 1 [main]
2023-03-13T06:47:47.4124Z 8064[8064] [I] Agent is shutting down with signal 0. [ShutdownAgent]
2023-03-13T06:47:47.4124Z 8064[8064] [I] De-initializing command listener thread [UninitializeCommandListenerThread]
2023-03-13T06:47:47.4124Z 8064[8064] [I] ADUC agent stopping [AzureDeviceUpdateCoreInterface_Destroy]
[postrm failed-upgrade 1.0.0] ERROR: ADU Agent (/usr/bin/AducIotAgent) validation failed. Aborting the upgrade.
dpkg: error processing archive /var/cache/apt/archives/deviceupdate-agent_1.0.2_amd64.deb (--unpack):
 new deviceupdate-agent package post-removal script subprocess returned error exit status 1
******************** Running /var/lib/dpkg/info/deviceupdate-agent.preinst abort-upgrade 1.0.2 ***********************
******************** Running /var/lib/dpkg/tmp.ci/postrm abort-upgrade 1.0.0 ***********************
******************** Running /var/lib/dpkg/info/deviceupdate-agent.postinst abort-upgrade ***********************
Errors were encountered while processing:
 /var/cache/apt/archives/deviceupdate-agent_1.0.2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by eshashah-msft** [comment]
Hi @shaeussler, the DU agent needs a connection string for authentication and connection. By default, we recommend doing this using IoT Identity service ([described here](https://azure.github.io/iot-identity-service/pkcs11/)). But if you are using TPM directly without IoT Identity service (AIS) service, you will need to write custom code, similar to [eis_util](https://github.com/Azure/iot-hub-device-update/tree/main/src/utils/eis_utils) which creates the connection string with the identity service

**Comment by eshashah-msft** [comment]
@shaeussler: Is the above error after the identity service was configured as defined in this section: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-linux-tpm?view=iotedge-1.4&tabs=physical-device%2Cubuntu#provision-the-device-with-its-cloud-identity?

**Comment by shaeussler** [comment]
Yes, I configured my IoT Edge using the instructions from https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-linux-tpm?view=iotedge-1.4&tabs=physical-device%2Cubuntu#provision-the-device-with-its-cloud-identity

**Comment by shaeussler** [comment]
I think the problem is that root is not allowed to get the identity for adu. Only the adu user can get his identity from the iot-identity-service, see https://azure.github.io/iot-identity-service/develop-an-agent.html#client-authorization

**Comment by eshashah-msft** [comment]
@nihemstr

**Comment by nihemstr** [comment]
Hey @shaeussler 

I took a look through the above logs and wanted to confirm a few things, but before I do I wanted to address:

> I think the problem is that root is not allowed to get the identity for adu. Only the adu user can get his identity from the iot-identity-service

That's not expressly true. It is true that the agent out of the box creates the principle file that authenticates ADU when it attempts to connect to the azure-identity-service \( within the azure-identity-service there are three services- the identity service (IS), key service (KS), and certificate service (CS) that we interact with \). You can read more about the principle file [here](https://azure.github.io/iot-identity-service/develop-an-agent.html#client-authorization) at ```bash /etc/aziot/identityd/config.d/adu.toml```. Inside of the principle file there's a field called the `idType` that is initially set to the user-id of the adu user, however if you want to run as root you can always change that value to a `0` indicating you're allowing any process that runs as root \( in this case the ADU process if you're running it as root \) to access the IS,KS, and CS. 

We don't support that out of the box because of the security implications, but you're welcome to do so during development. 

As for debugging the ADU agent it looks like your agent is getting past requesting the identity from the identity response but is instead failing to parse/getting a bad response from the key service. This might point to an issue with the way the key service has been configured or some logic path we haven't explored yet, but first we check the configuration of the IS (within the azure-identity-service) by running the following command \( assuming you've configured AIS to allow the adu user to connect, if configured for sudo access run the command without the `-u adu` \):

``` sudo -u adu curl -XGET --unix-socket /run/aziot/identityd.sock http:/foo/identities/identity?api-version=2020-09-01 ```

The response should be the actual identity response the du-agent would receive when we ask for a response. Once we get the value we can determine what might be going wrong with the identity response.

Let me know when you get the data!

Thanks,

Nic Hemstreet

**Comment by shaeussler** [comment]
Hi @nihemstr 
Thanks for your response.
Here are the requested data:
```
sudo curl -XGET --unix-socket /run/aziot/identityd.sock http:/foo/identities/identity?api-version=2020-09-01
{"type":"aziot","spec":{"hubName":"XXXXXX.azure-devices.net","gatewayHost":"XXXXXX.azure-devices.net","deviceId":"my-device-id","auth":{"type":"tpm"}}} 
```
```
sudo cat /etc/adu/du-config.json
{
    "schemaVersion": "1.1",
    "aduShellTrustedUsers": [
      "adu",
      "do"
    ],
    "manufacturer": "XXX",
    "model": "<my-model>",
    "agents": [
      {
        "name": "my-adu-agent",
        "runas": "adu",
        "connectionSource": {
          "connectionType": "AIS",
          "connectionData": ""
        },
        "manufacturer": "XXX",
        "model": "<my-model>"
      }
    ]
  }
```
```
sudo cat /etc/aziot/identityd/config.d/adu.toml
[[principal]]
 name="IoTHubDeviceUpdate"
 idtype=["module"]
 uid= 111
```
```
id adu
uid=111(adu) gid=117(adu) groups=117(adu),106(syslog),999(aziotks),997(aziotcs),996(aziotid),118(do)
```

**Comment by jw-msft** [comment]
Here are some additional resources to help setup Iot Identity Service (aka AIS) for use with TPM
https://azure.github.io/iot-identity-service/pkcs11/

and for TPM2.0:
https://azure.github.io/iot-identity-service/pkcs11/tpm2-pkcs11.html

/etc/aziot/config.toml file needs:
```toml
[aziot_keys]
pkcs11_lib_path = "<path of the PKCS#11 library>"
pkcs11_base_slot = "<PKCS#11 URI of a slot where dynamically generated keys will be stored>"
```

As per that page, try to test with:
```sh
pkcs11-tool --module "$PKCS11_LIB_PATH" -IOT
p11tool --provider="$PKCS11_LIB_PATH" --list-token-urls
```

I saw that the provided `id adu` output shows that `adu` user is not in the `aziottpm` unix group, which seems a bit suspect.

If you do 

```sh
ls -latr /dev/tpm*
```

are the tpm devices should be in `aziottpm` group?

The `id adu` output shows `adu` user is already in the `aziotid`, `aziotcs`, and `aziotks` groups

However, I think you may need to add `adu` user into `aziottpm` group as well, so give that a try.

Also, ensure that the azure identity .toml config file has user and group owners as aziotid and aziotid, respectively.

Closing as this is a stale issue. Feel free to open a new issue if the above does not resolve the issue.
