### ISSUE TITLE
Device Update instance: Missing message route in connected IoT Hub

### ISSUE THREAD

**Issue by ccli8** [Azure/iot-hub-device-update#418]
I am following [Create Device Update for IoT Hub resources](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/create-device-update-account?tabs=portal) to create Device Update account and instance. After generation, I find one message route is missing. According to [Message Routing](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-resources#message-routing),  there should be 4 routes:
- DeviceUpdate.DeviceTwinChanges
- DeviceUpdate.DigitalTwinChanges
- DeviceUpdate.DeviceLifecycle
- DeviceUpdate.DeviceConnectionState

But my Device Update instance only shows 3: **DeviceUpdate.DeviceConnectionState** is missing

![Device Update instance](https://user-images.githubusercontent.com/15923441/223605081-b8faf0d7-b712-4b8b-8ccb-524443756cb9.png)

![Connected IoT Hub](https://user-images.githubusercontent.com/15923441/223605541-e4b633ed-f8ae-4fb7-94ab-9865d545014e.png)

**Comment by eshashah-msft** [comment]
Hi @ccli8, DeviceUpdate.DeviceConnectionState is not created and needed with Device Update. 
I have also updated the docs to reflect the correct message routes. The changes will be merged by tomorrow. 
Closing this issue. But please feel free to open a new issue if there are any other issues in the update workflow.
