### ISSUE TITLE
Broken link to porting guide

### ISSUE THREAD

**Issue by Voxel07** [Azure/iot-hub-device-update#44]
The link

`https://github.com/Azure/azure-c-shared-utility/blob/public-preview/devdoc/porting_guide.md` 

mentioned in 
`/docs/agent-reference/how-to-modify-the-agent-code.md` 
Porting to a different OS or platform is broken.

I think it should be replaced by
`https://github.com/Azure/azure-c-shared-utility/blob/master/devdoc/porting_guide.md`

**Comment by ValOlson** [comment]
Thank you for pointing that out! We will fix it shortly.
