### ISSUE TITLE
device group creation

### ISSUE THREAD

**Issue by Shotariusii** [Azure/iot-hub-device-update#451]
Hello.

I am trying to add groups for devices by adding tags in Device Twins. but when i check Groups and Deployments under Update section there is no any Group to deploy update.

any idea what i am missing ?

**Comment by Shotariusii** [comment]
Hello, i am using ESP32 with Freertos Azure C sdk,  i check it also after successful connection but it didn't appear, also I checked that i am sending ADU agent state successfully.

there is nothing, message with : There are no groups to display.

you mean may i have no permission from my admin to do that ? 
i did container creation and importing files.

**Comment by Shotariusii** [comment]
Can anyone help me to find out what is a problem ? 
i think the problem is Azure Portal side, i am missing something.

**Comment by jw-msft** [comment]
Hi @Shotariusii, Could you share the snippet in your twin that you added to add the group tag?

What typically works for me is to add a snippet at the top-level properties (NOTE: exact casing of `"ADUGroup"` ):
```json
  "tags": {
    "ADUGroup": "yourGroupNameHere"
  },
```

A lengthier snippet:

```json
{
    "deviceId": "test",
    "etag": "AAAAAAAAAIg=",
    ...
    ...
    ...
    "modelId": "dtmi:azure:iot:deviceUpdateModel;2",
    "version": 5731,
    "tags": {
        "ADUGroup": "yourGroupNameHere"
    },
    "properties": {
    ...
    ...
    ...
}
```

**Comment by Shotariusii** [comment]
I configure accesses again, i was missing something. so now i am getting this in diagnostic section. 

![groupanddeploy1](https://user-images.githubusercontent.com/91596284/232777243-ab223596-d3a4-403f-97c5-78fccafee483.jpg)

**Comment by jw-msft** [comment]
@Shotariusii Could you provide more details about the agent being used? Is it installed via .deb package, built from sources, customized/rewritten?

**Comment by Shotariusii** [comment]
thanks for your replay, i was writing my flow of ADU and I missed some initialisation function, that's why I had that problem, now I solved thanks a lot.
