### ISSUE TITLE
Problem with connecting to IoT hub via MqttWs

### ISSUE THREAD

**Issue by arminghasemazar** [Azure/iot-hub-device-update#452]
We are facing an issue with one of our clients VM. Unfortunately we don’t have direct access to VM to troubleshoot but we managed to receive some logs from them. So edgeAgent/Hub and all other modules are working flawlessly. Upstream protocol has been set to MqttWs and we receive data from modules. Twins also get updated regularly. However, adu module can’t communicate with IoT hub and update twin. See attached the logs. Also see below the screenshot of firewall logs we got from client. We can clearly see that the edge (particularly adu) tries to communicate with IoT hub via Mqtt 8883 port, which is strange. I also checked the adu settings and it states “MqttWs” for upstream protocol. So the first question is why adu can’t communicate with hub via MqttWs 443 when edgeAgent and edgeHub can. Also, seems like there is a fallback strategy in adu that switches to 8883 when for any reason it can’t go though 443. Would appreciate if you can shed some lights.

[deviceupdate.txt](https://github.com/Azure/iot-hub-device-update/files/11147407/deviceupdate.txt)
![1](https://user-images.githubusercontent.com/13336488/229763202-e8b66a0b-404d-4bfc-8838-c7be74f5ec86.png)

### Device Information
* Host OS Ubuntu 20.04
* Architecture amd64
* Provisioning Method: DPS symmetry key
* DU Agent Version latest

**Comment by jw-msft** [comment]
In `/etc/adu/du-config.json`, what is the value of `"iotHubProtocol"` property at top-level?  For mqtt over websockets, it should be `"mqtt/ws"` (NOTE: the forward-slash character between `mqtt` and `ws`).

See this doc for more details:
https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-build-agent-code.md#build-options-for-mqtt-and-mqtt-over-websockets-iothub-transport-providers

**Comment by jw-msft** [comment]
Closing. Let us know if the above does not resolve the issue.
