### ISSUE TITLE
Missing Metadata in the IoTHub Eventhub twinChangeEvents when the Properties are updated via Configurations

### ISSUE THREAD

**Issue by BhagyashreeRH** [Azure/iot-hub-device-update#461]
## Expected Behavior
If a property exists under the desired section of the IoT Hub `twinChangeEvents` then the metadata (_$lastUpdated_ information) for that property should exist.
The `twinChangeEvent` should contain the metadata of all the properties which are available in the body section when the desired properties on the twin are updated using IoTHub Configurations.
## Current Behavior
Updating any desired property via IoTHub Configurations results in missing metadata information for the some of the properties available in the body section of the event. This metadata is available in the twin though.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.Add a desired property on twin. {"Prop2":"Value2"}
2.Add a desired property on the twin via configurations {"Prop3":"Value3"}
3.Tap in the IoTHub twinchangeEvents and capture the event triggered for Step no.2 
4.Observe the metadata section in the event body

## Sample twinchangeEvent
```json
{
  "body": {
    "version": 8,
    "properties": {
      "desired": {
        "Prop2": "Value2",
        "Prop3": "Value3",
        "$metadata": {
          "$lastUpdated": "2023-03-30T09:15:42.2952664Z",
          "$lastUpdatedVersion": 6,
          "Prop3": {
            "$lastUpdated": "2023-03-30T09:15:42.2952664Z",
            "$lastUpdatedVersion": 6,
            "$lastUpdatedBy": "####",
            "$lastUpdatedByDigest": "####"
          }
        },
        "$version": 6
      }
    }
  },
  "enqueuedTime": "Thu Mar 30 2023 14:45:42 GMT+0530 (India Standard Time)",
  "properties": {
    "hubName": "####",
    "deviceId": "####",
    "operationTimestamp": "2023-03-30T09:15:42.2952664Z",
    "moduleId": "FirmwareModule",
    "iothub-message-schema": "twinChangeNotification",
    "opType": "updateTwin",
    "iothub-name": "####"
  }
}
```
**Observation** 
The metadata information for Prop2 is missing here.

**Related Issue**
#173

**Comment by Nox-MSFT** [comment]
@OscarLee-MSFT, I'm not sure if this is specific to ADU, but, mind taking a look please?

**Comment by BhagyashreeRH** [comment]
@OscarLee-MSFT May I know where can I report this issue?

**Comment by bshurn** [comment]
@BhagyashreeRH 

This issue is unrelated to Azure Device Update. 
I recommend submitting a support request to IoT Hub.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#create-a-support-request
