### ISSUE TITLE
adu-base-image takes long to boot

### ISSUE THREAD

**Issue by wayne-david** [Azure/iot-hub-device-update#463]
## Expected Behavior
I would expect the image to take shorter time to boot.When I build core-image-base,it takes around 20 seconds to boot.But adu-base-image takes 2 minutes 30 seconds.Adu base image is expected to take a little longer but not that much.

## Current Behavior
When adu-base-image is installed in the arm64 device,the device takes 2 minutes 30 seconds to bootup into a usable state.Is this the standard boot time for image using meta-azure-device-update or is there an issue. Could you guide me into the right direction to make the boot time  shorter.

## Steps to Reproduce
1.Create adu-base-image in yocto targetting arm64
2.Intall adu-base-image in the device
3.
4.

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Provisioning Method:
*DU Agent Version (run 'sudo -u adu /usr/bin/AducIotAgent -v'):

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by jw-msft** [comment]
Does dmesg or /var/log/syslog reveal anything?
I haven't tried it but you could try:
```
systemd-analyze time -H user@host
systemd-analyze blame -H user@host
systemd-analyze critical-chain -H user@host
systemd-analyze plot -H user@host > boot.svg
xviewer boot.svg
```
or do it locally without the `-H user@host` cmdline arg.
The team is low on bandwidth at the moment, but may be able to attempt a repro later this week or early next.

**Comment by jw-msft** [comment]
Hi @wayne-david, have you had a chance to try out some of the diagnostics I suggested? I haven't noticed slow boot when using the released rpi tutorial zips with .wic that I've flashed on rpi3/rpi4, so I would not expect there to be slow boots due to what's in the base image.

**Comment by wayne-david** [comment]
Hello @jw-msft.Looked into this.It was unrelated to adu.it was a systemd service configuration issue.Works great now.Thanks
