### ISSUE TITLE
Question: 1.0.3 ?

### ISSUE THREAD

**Issue by neonsoftware** [Azure/iot-hub-device-update#470]
Hi, 

just a question.

Do you plan the next release to be a patch, ex v1.0.3, or a minor/major ?  
Thank you in advance for any timeline/roadmap.

Have a nice day

**Comment by eshashah-msft** [comment]
Hi @neonsoftware, we don't have a specific release planned right now. But it would be good to understand if there is a feature that you are looking for?

**Comment by neonsoftware** [comment]
Hi @eshashah-msft,

Thank you for your response.
No, just knowing whether 1.0.3 was around the corner.

(we are using 1.0.1 and will go through a QA phase. Thinking of taking the chance, moving to latest, at the same time.).

**Comment by eshashah-msft** [comment]
Closing this issue and will share an update when we have the next release.
