### ISSUE TITLE
Support for agents on Ubuntu 22.04 LTS?

### ISSUE THREAD

**Issue by tkirkpatrick-mirion** [Azure/iot-hub-device-update#471]
Is there a plan to support the Device Update agent on Ubuntu 22.04 LTS?

**Comment by eshashah-msft** [comment]
Hi @tkirkpatrick-mirion, yes, we plan to add support for Ubuntu 22.04. We don't have an exact release date for this yet. 

Please upvote this discussion item that help with prioritization and planning new features and support: https://github.com/Azure/iot-hub-device-update/discussions/408
