### ISSUE TITLE
Debian 10 Unable to locate package deviceupdate-agent

### ISSUE THREAD

**Issue by PAKalucki** [Azure/iot-hub-device-update#483]
## Expected Behavior
deviceupdate-agent should be installed

## Current Behavior
E: Unable to locate package deviceupdate-agent

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Have IoT Edge enabled Debian device
2. Follow steps from https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-provisioning

### Device Information
* Debian 10 
* arm32

## Logs
```
sudo apt-get install deviceupdate-agent
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package deviceupdate-agent
```

**Comment by eshashah-msft** [comment]
Hi @PAKalucki, 

The Debian 10 ARM32 package is located here: https://packages.microsoft.com/debian/10/prod/pool/main/d/deviceupdate-agent/

Can you verify that the right repo has been added to the sources.list.d directory?

**Comment by PAKalucki** [comment]
Repo was setup via https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb

```
cat /etc/apt/sources.list.d/microsoft-prod.list
deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main
```

Looks like the issue was arch, after manually changing it to arch=armhf, I was able to install.
