### ISSUE TITLE
How to get the exit code of the script-handler from ExtendedResultCode?

### ISSUE THREAD

**Issue by mahdighorbanpourptw** [Azure/iot-hub-device-update#487]
Hi,
I am using a script-handler in Adu update service and I am trying to decode the ExtendedResultCode of the update state. I have prepared my environment so when Adu runs the script, the script exit code will be 22. The ExtendedResultCode that I am getting is 810553366.
According to the [documentation](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-error-codes#resultcode-and-extendedresultcode), First I should get the unsigned hex representation of it, which with my implementation below will be: "30501016".

It doesn't start with "D" or "E" but is "3"
The error code according to the documentation is the last 20 bytes which will be "01016". Now If we should transform this hex number back to the integer number. the result is 4118 which is obviously not 22 :-)
If I instead of 20 bytes, take the last 12 bytes (016) then I would get the expected result 22.
Please let me know if something in the documentation is missing, or I am doing something wrong. Thank you

public void TranslateCode(long extendedResultCode)
    {
        string hexString = ((ulong)extendedResultCode).ToString("X8", CultureInfo.InvariantCulture); // Convert to hexadecimal string
        var uHexstring = hexString.TrimStart("FFFFFFFF".ToCharArray());
        var facilityCode = uHexstring[0];
        var errorNo = UInt32.Parse(uHexstring.AsSpan(3), NumberStyles.HexNumber, CultureInfo.InvariantCulture);
    }

**Comment by jw-msft** [comment]
# Summary
I am sorry that this is not documented well, so we are now tracking a documentation work item to improve it.

For non-zero exit codes of child processes run via adu-shell process, such as executing a script in script handler, the agent parent process adds an offset of 0x1000 (4096 hex) to avoid collisions with other error codes for the content handler facility and the specific per-content-type component encoded error.

So, in your case `4096 + 22 == 4118` or `0x1016` in hex, so the last 20 bits is `0x01016` as you are seeing.

# Details

The full bit-encoding of the ERC is described here:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/inc/aduc/result.h#L54

ADUC_ERC_SCRIPT_HANDLER_CHILD_PROCESS_FAILURE_EXITCODE is called for script child process failure exit code:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/extensions/step_handlers/script_handler/src/script_handler.cpp#LL589C1-L595C6
```c
    if (exitCode != 0)
    {
        int extendedCode = ADUC_ERC_SCRIPT_HANDLER_CHILD_PROCESS_FAILURE_EXITCODE(exitCode);
        Log_Error("Script failed (%s), extendedResultCode:0x%X (exitCode:%d)", action.c_str(), extendedCode, exitCode);
        result = { .ResultCode = ADUC_Result_Failure, .ExtendedResultCode = extendedCode };
        goto done;
    }
```

## Offset 0x1000 (4096) added to non-zero child process exit codes
The offset of 0x1000 can see that ADUC_ERC_SCRIPT_HANDLER_CHILD_PROCESS_FAILURE_EXITCODE adds an offset of 0x1000 (4096 decimal) to the exit code value:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/inc/aduc/result.h#L1552

## Definition of MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_HANDLER_SCRIPT
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/inc/aduc/result.h#L277

## ADUC_CONTENT_HANDLER_SCRIPT Component used
It uses the component bits of `ADUC_CONTENT_HANDLER_SCRIPT`:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/inc/aduc/result.h#L277
which has a value of 0x5:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/inc/aduc/result.h#L124

with the a facility code of `0x3 (ADUC_FACILITY_EXTENSION_UPDATE_CONTENT_HANDLER)`:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/inc/aduc/result.h#L85

## Final encoding of ERC

bitwise-OR'ing in the Facility and Component bits yields:
```
    3 05 01016     Total 4 bytes (32 bits)
    - -- -----
    | |  |
    | |  |
    | |  +---------  Error code (20 bits)
    | |
    | +------------- Component/Area code (8 bits)
    |
    +--------------- Facility code (4 bits)
```

which is exactly the `0x30501016` value you saw.

**Comment by mahdighorbanpourptw** [comment]
Thanks a lot, this clears things up.

**Comment by AndreRicardo-Zoetis** [comment]
Python code explanation for building the ERC `810553366`

```python3
def MakeERC(facility, component, result):
    """
    Creates an ExtendedResultCode from the facility, component, and result

    Returns the ExtendedResultCode value calculated using the facility, component, and result codes
    """
    return ((facility & 0xF) << 0x1C) | ((component & 0xFF) << 0x14) | (0xFFFFF & result)

# ADUC_FACILITY_EXTENSION_UPDATE_CONTENT_HANDLER =
#     3, //!< ADUC_FACILITY_EXTENSION_UPDATE_CONTENT_HANDLER : 3, indicates errors from a step handler
facility = 3
#   ADUC_CONTENT_HANDLER_SCRIPT =
#     5, //!< ADUC_CONTENT_HANDLER_SCRIPT : 5, Results that originate from the script handler part of the step handlers
component = 5

#define ADUC_ERC_SCRIPT_HANDLER_CHILD_PROCESS_FAILURE_EXITCODE(exitCode) \
#    MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_HANDLER_SCRIPT((0x1000 + exitCode))
result = int('0x1000', 16) + 22 

print(MakeERC(facility, component, result))
```
```sh
$ python3 make_erc.py
810553366
```

Same that happens in 
https://github.com/Azure/iot-hub-device-update/blob/fd69e827422f7fd8be06e04617c6cf8176bb104a/src/inc/aduc/result.h#L69-L72

**Comment by AndreRicardo-Zoetis** [comment]
I've tried to understand the extendedErrorCode `810553345` to no avail.

```
                    "lastInstallResult": {
                        "extendedResultCode": 810553345,
                        "resultCode": 0,
```

```python3
def ExtractERC(extended_result_code):
    """
    Extracts the facility, component, and result from an ExtendedResultCode.

    Returns a tuple containing the facility, component, and result.
    """
    facility = (extended_result_code >> 0x1C) & 0xF         # Extract the facility (top 4 bits)
    component = (extended_result_code >> 0x14) & 0xFF       # Extract the component (next 8 bits)
    result = extended_result_code & 0xFFFFF                 # Extract the result (bottom 20 bits)
    
    return facility, component, result

print(ExtractERC(810553366))
print(ExtractERC(810553345))
```

```sh
$ python3 make_erc.py
(3, 5, 4118)
(3, 5, 4097)
```

https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/scripts/error_code_generator_defs/result_codes.json#L501-L502

`810553345` is not present in my result.h

**Comment by jw-msft** [comment]
> I've tried to understand the extendedErrorCode 810553345 to no avail.

@AndreRicardo-Zoetis 

810553345 (0x30501001) is used in a few places.
0x30501000 is the base for external processes launched (such as a script for script handler).

You can see here that it's for packing child process error codes:

https://github.com/Azure/iot-hub-device-update/blob/fd69e827422f7fd8be06e04617c6cf8176bb104a/scripts/error_code_generator_defs/error_code_defs_generator.py#L147

```py
//
// Child process error code generators
//

#define ADUC_ERC_SWUPDATE_HANDLER_CHILD_FAILURE_PROCESS_EXITCODE(exitCode) MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_HANDLER_SWUPDATE((0x1000 + exitCode))

#define ADUC_ERC_SCRIPT_HANDLER_CHILD_PROCESS_FAILURE_EXITCODE(exitCode) MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_HANDLER_SCRIPT((0x1000 + exitCode))

#define ADUC_ERROR_DELIVERY_OPTIMIZATION_DOWNLOADER_EXTERNAL_FAILURE(exitCode) MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_DOWNLOADER_DELIVERY_OPTIMIZATION((0x1000 + exitCode))

#define ADUC_ERROR_CURL_DOWNLOADER_EXTERNAL_FAILURE(exitCode) MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_DOWNLOADER_CURL_DOWNLOADER((0x1000 + exitCode))
```

Also, the example shell scripts explicitly take 0x305001000 and add it to the exit code:
* https://github.com/Azure/iot-hub-device-update/blob/fd69e827422f7fd8be06e04617c6cf8176bb104a/src/extensions/component_enumerators/examples/contoso_component_enumerator/demo/sample-updates/scripts/contoso-motor-installscript.sh#L799
* https://github.com/Azure/iot-hub-device-update/blob/fd69e827422f7fd8be06e04617c6cf8176bb104a/src/extensions/component_enumerators/examples/contoso_component_enumerator/demo/sample-updates/scripts/contoso-camera-installscript.sh#L799
* https://github.com/Azure/iot-hub-device-update/blob/fd69e827422f7fd8be06e04617c6cf8176bb104a/src/extensions/component_enumerators/examples/contoso_component_enumerator/demo/sample-updates/scripts/contoso-update-simulatorscript.sh#L840

The lower 20 bits are 01001 in the case of `0x30501001`, so this is expressing an exit code from the external exec'ed process of `1` (failure) assuming `0` is success

**Comment by AndreRicardo-Zoetis** [comment]
Thank you for the explanation @jw-msft.

So to double check, does that mean that 810553345 (0x30501001) really is the 0x30500000, for facility=3, component=5, padded 0x1000 and error code 1?

```
#define ADUC_ERC_SCRIPT_HANDLER_CHILD_PROCESS_FAILURE_EXITCODE(exitCode) \
    MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_HANDLER_SCRIPT((0x1000 + exitCode))
```

```python3

# ADUC_FACILITY_EXTENSION_UPDATE_CONTENT_HANDLER =
#     3, //!< ADUC_FACILITY_EXTENSION_UPDATE_CONTENT_HANDLER : 3, indicates errors from a step handler
facility = 3
#   ADUC_CONTENT_HANDLER_SCRIPT =
#     5, //!< ADUC_CONTENT_HANDLER_SCRIPT : 5, Results that originate from the script handler part of the step handlers
component = 5

#define ADUC_ERC_SCRIPT_HANDLER_CHILD_PROCESS_FAILURE_EXITCODE(exitCode) \
#    MAKE_ADUC_EXTENDEDRESULTCODE_FOR_COMPONENT_ADUC_CONTENT_HANDLER_SCRIPT((0x1000 + exitCode))
result = int('0x1000', 16) + 1 

print(MakeERC(facility, component, result))
```

```sh
python3 make_erc.py
810553345
```
