### ISSUE TITLE
docs/agent-reference/how-to-build-agent-code.md contains text referencing deleted content

### ISSUE THREAD

**Issue by patheikkinen** [Azure/iot-hub-device-update#500]
In "How to build the Device Update Agent" the instructions for integrating the Device Update agent in your existing application or solution were deleted in a recent commit. The introductory text, however, still states that it is an option and there is a broken link to the now missing section in the document.

This makes the document contradictory; so, if the deletion was intentional, the introductory text should be updated as well, and if it wasn't, the missing text should be reintroduced.

**Comment by jw-msft** [comment]
Is this on develop or main branch and could you provide which commit removed the instructions?  If main branch, is it #433 that is in question per chance?

**Comment by patheikkinen** [comment]
Main branch, and that was indeed the PR I was referring to. Commit 4ce421b.

**Comment by jw-msft** [comment]
@Nox-MSFT Could you take a look?

**Comment by Nox-MSFT** [comment]
@patheikkinen We appreciate your report on the issue. Our team is currently working on enhancing the DU Agent architecture to simplify integration with existing applications. Once the improvements are completed, we will reintroduce the documentation. Thank you.

**Comment by patheikkinen** [comment]
Thanks.
