### ISSUE TITLE
ScriptHandler crashs ADU

### ISSUE THREAD

**Issue by shaeussler** [Azure/iot-hub-device-update#526]
Bug in line https://github.com/Azure/iot-hub-device-update/blob/b71516d3e85f09db48c06980448e3a07d90d05e4/src/utils/process_utils/src/process_utils.cpp#L110 when count is 1024.

## Expected Behavior
ADU should not crash with a segmentation fault

## Current Behavior
ADU crash with a segmentation fault

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Run ADU and using the ScriptHandler

### Device Information
* Host OS: Buildroot Linux
* Architecture: arm64
* Provisioning Method: TPM
*DU Agent Version (run 'sudo -u adu /usr/bin/AducIotAgent -v'): 1.0.2

## Logs
-

## Additional Information
The following code snippet on line https://github.com/Azure/iot-hub-device-update/blob/b71516d3e85f09db48c06980448e3a07d90d05e4/src/utils/process_utils/src/process_utils.cpp#L110 solves the bug:
```
        if(count < sizeof(buffer))
        {
            buffer[count] = 0;
        }
```

**Comment by jw-msft** [comment]
Thanks for reporting this, @shaeussler.

I have a PR #527 out to address this in main branch that also fixes same issue I found in [string_c_utils LoadBufferWithFileContents](https://github.com/Azure/iot-hub-device-update/blob/b71516d3e85f09db48c06980448e3a07d90d05e4/src/utils/c_utils/src/string_c_utils.c#L136)

I'm also porting the fix to develop branch.

**Comment by jw-msft** [comment]
@shaeussler, Her is the merged commit in [main](https://github.com/Azure/iot-hub-device-update/tree/main) that should fix this issue: https://github.com/Azure/iot-hub-device-update/commit/f9b180dede4a6ed362cdf809862a9ef12872db4d

**Comment by shaeussler** [comment]
Thanks
