### ISSUE TITLE
Question: How to make custom DTMI model private for ADU

### ISSUE THREAD

**Issue by oedze** [Azure/iot-hub-device-update#539]
Direct copy of the original post on Microsoft Learn, where it was asked to post the question here [original question](https://learn.microsoft.com/en-us/answers/questions/1372457/how-to-make-custom-dtmi-model-private-for-adu)

We are using ADU to udpate our devices.

We currently have the modelId dtmi:azure:iot:deviceUpdateContractModel;1 set in DPS and our device. All the other ADU requirements are also met and we can see the device in the devices list in the "Update" section of the IoT Hub.

However, we want to define our own DTMI model for our device, something like:

dtmi:company:project:device;1 which extends the dtmi:azure:iot:deviceUpdateContractModel;1

This works fine in something like the Azure IoT Explorer, but now are devices won't get listed in the Groups& Deployments tab. I believe i need to make my device model public in the repository: https://github.com/Azure/iot-plugandplay-models/tree/main But i don't want to make it public

Is there a way to link a private repository to Azure Device Update so device can report some modelId other than dtmi:azure:iot:deviceUpdateContractModel;1

### Device Information
* OS/Microschip:ESP32S3
* Provisioning Method: DPS using X509 Certificate attestation
*DU Agent Version (run 'sudo -u adu /usr/bin/AducIotAgent -v'): [FreeRTOS iot adu client](https://github.com/Azure/azure-iot-middleware-freertos/blob/main/source/azure_iot_adu_client.c)

## Logs

None

## Additional Information
None

**Comment by eshashah-msft** [comment]
Hi @oedze, custom PnP models that extend the device update models can be created and used on the devices. This doc covers [how to create custom models](https://learn.microsoft.com/en-us/azure/iot-develop/concepts-modeling-guide).

However, private models are not supported at this time. Please go to https://aka.ms/deviceupdateiot-feedback to upvote/ add this as a feature request/ suggestion.

+ @xinanqiu , @OscarLee-MSFT - To review
