### ISSUE TITLE
Device Update Agent attempting MQTT connection over TLSv1

### ISSUE THREAD

**Issue by sandipanaich** [Azure/iot-hub-device-update#549]
Hi,

I am facing an issue with a device update not reaching the CONNECTED state and I was hoping if you could share some debugging steps.
I have 2 identical Azure Ubuntu VMs, but they are with 2 different but identical IoT Hubs (say, Dev and QA). For one of them (Dev) the device-update-agent is fine, but for the other one (ie. QA) it is not.
Please note that all the other aspects of a device registering with the IoT Hub and having a proper Device Update for IoT Hub are in place.

We took a tcpdump and checked the packets. We noticed that on Dev, the MQTT connection on port 8883 is initiated by the device-update-agent over TLSv1.2, but on QA it is attempting the connection over TLSv1.
Since the IoT Hub is configured to only accept TLSv1.2 connection, it is rejecting the TLSv1.2 on QA.

Can you please suggest any steps that we can follow to enforce the MQTT connection attempt over TLSv1.2 on QA as well?
Otherwise, it would be helpful if you could provide us with any other debugging steps that we can carry out.

Since it is a blocker for QA, may I request it to be prioritized?

Thanks,
Sandipan

**Comment by jw-msft** [comment]
@sandipanaich Could you run and provide output for the following?

(I am assuming `"iotHubProtocol"` in `/etc/adu/du-config.json` has value of `"mqtt"`. Change `8883` port to `443` below instead if it has `"mqtt/ws"` for using MQTT over Websockets)

1. `openssl s_client -connect <ip4 addr of iothub host>:8883 -showcerts -prexit -servername localhost -debug`
2. tcpdump for TLS handshake
```sh
sudo systemctl stop deviceupdate-agent
sudo tcpdump -v -A -x "tcp port 8883 and (tcp[((tcp[12] & 0xf0) >> 2)] = 0x16)" > /tmp/out.pcap.txt 2>&1
# Now, do <Ctrl + Z> and run "bg" to background the task

# then, run agent standalone (not as a service)
sudo /usr/bin/AducIotAgent -l0 -e

# let it run for 1-2 seconds and then:
<Ctrl + C>
fg
<Ctrl + C>

# provide /tmp/out.pcap.txt
```

**Comment by jw-msft** [comment]
Resolving as incident was resolved.
