### ISSUE TITLE
Device Update Free Edition

### ISSUE THREAD

**Issue by sinusX** [Azure/iot-hub-device-update#550]
According to the pricing calculator (https://azure.microsoft.com/en-au/pricing/calculator/) there is an Free Edition of the IoT Hub Device update:

![image](https://github.com/Azure/iot-hub-device-update/assets/55558750/c9dc57d8-4698-4242-b81b-ce3246ebce76)

But when I try to setup an "Device update for IoT Hub" with a "Free Tier"-Iot Hub, I get an error, that this combination is not possible.
Can you clarify on this topic?

**Comment by eshashah-msft** [comment]
@sinusX : Device Update paid and free SKU, both require minimum S1 (Standard) IoT Hub tier as the hub message limits in the free tier would significantly impact the Device Update experience. [[Doc](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/create-device-update-account?tabs=portal#prerequisites)]
