### ISSUE TITLE
Device Update not applying due to lower case conversion of compat property

### ISSUE THREAD

**Issue by devika-vinay** [Azure/iot-hub-device-update#553]
I have a VM in which I have installed the deviceupdate-agent package. I have also uploaded importmanifest and apt-manifest files to a storage container.
This storage container is linked to a device update instance which is in turn linked to the same iothub that the VM is provisioned in.

The du-config.json file on the VM as well as the importmanifest file both have the same compat properties, following which the device is tagged to a group.

However, on clicking deploy in the group, the update goes into "Active" state but the device count, failure count or success count do not change. The update never gets applied on the VM.
-->

Expected Behavior:
Ideally, if the compat properties are matching, including case, the update should start on the VM which can be confirmed by the success count and by checking the version of the updated package on the VM.

Current Behavior:
The update is not applying on the VM as the model compat property is automatically changing to lower case in target device information.

**du-config.json file**

![image](https://github.com/Azure/iot-hub-device-update/assets/50499237/3b9a5d78-df22-4645-bfe4-ba493161116d)

**IoTHubDeviceUpdate Module Identity - reported properties**

![image](https://github.com/Azure/iot-hub-device-update/assets/50499237/5d40b415-2ff4-4364-9f6e-f22d525eb6ed)

**Update information present in importmanifest file**

![image](https://github.com/Azure/iot-hub-device-update/assets/50499237/6e0724c3-79c7-456d-a87d-6316ec09ec6f)

**Target device properties auto converting model into lower case**

![image](https://github.com/Azure/iot-hub-device-update/assets/50499237/ebcec6ae-c14f-4565-a1df-eaed6b4c135e)

**Deployment stuck in "Active" state**

<img width="422" alt="image" src="https://github.com/Azure/iot-hub-device-update/assets/50499237/fb32684f-8024-4fcc-a25a-b3a9bb4733ba">

Device Information:
Host OS: Ubuntu20.04.6
Architecture: amd64
DU Agent Version: 1.0.2

**Comment by eshashah-msft** [comment]
@devika-vinay: Investigating this for bug/issue on service side.

**Comment by eshashah-msft** [comment]
Hi @devika-vinay, for du-config.json, the compat property values such as "Ubuntu 20.04" in the above example, must be in lower case for correct targeting with device class. We have a work to remove case sensitivity in our backlog.
I have also made a change in the [documentation](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-configuration-file#list-of-fields) to call out this requirement.
Can you please let me know if you were able to successfully able to deploy an update (prior to the 2.2 update above) with to the same device with the above du-config.json?

**Comment by devika-vinay** [comment]
Hi Esha,

Thanks for the update.
To answer your question, yes I had been testing everyday for more than a
month with the above properties and recorded a video as well, in one
instance.
This inconsistency only came to my attention 4-5 days ago.

Regards,
Devika Vinayarajan.

**Comment by eshashah-msft** [comment]
@devika-vinay: For the import manifest, was the mixed casing use there as well? Or was only lower case was used there?

**Comment by devika-vinay** [comment]
No, there was no mixed casing used in the import manifest, as seen in the 3rd screenshot provided above.

**Comment by eshashah-msft** [comment]
But it does have a mix of lower case and upper case from the above image?
![image](https://github.com/Azure/iot-hub-device-update/assets/92388818/0c641e87-fb2a-4834-9fde-dccf30c3739b)

Also, were you able to get around the issue by moving the du-config and import manifest compat property values to lower case? 

Also, was there was only one device in this group at all points, or if some device was removed or changed?

**Comment by eshashah-msft** [comment]
Closing this as we have not been able to repro the issue. But consistently using the lower case for specifying the compat properties will ensure correct targeting of the updates.
