### ISSUE TITLE
Device not added in Azure Device Update Groups in IoT Hub

### ISSUE THREAD

**Issue by jbiemar** [Azure/iot-hub-device-update#557]
Hi, 

## Expected/Current Behavior
I try to use firmware update with Azure IoT Hub.

I followed this guide [Device Update for IoT Hub documentation](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/) but device is not shown in *Groups and deployments*.

## What I already checked:
1. *Azure Device Update* has the role *IoT Hub Data Contributor* in the hub
2. Device was deleted and recreated after setting *Device Update*
3. DU agent was update in twin before adding ADUGroup:
```
"reported": {
            "deviceUpdate": {
                "__t": "c",
                "agent": {
                    "deviceProperties": {
                        "manufacturer": "Company",
                        "model": "model",
                        "contractModelId": "dtmi:azure:iot:deviceUpdateContractModel;2",
                        "aduVer": "DU;agent/1.0.0"
                    },
                    "compatPropertyNames": "manufacturer,model",
                    "state": 0,
                    "installedUpdateId": "{\"provider\":\"Company\",\"name\":\"model\",\"version\":\"1.0.0\"}"
                }
            },
```
4. ADUGroup is:
```
    "tags": {
        "test": 1,
        "ADUGroup": "adutest"
    },
```

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: ESP32
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Provisioning Method: DPS
*DU Agent Version: DU;agent/1.0.0

Thank you

**Comment by josephmsft** [comment]
what is the device and module Id (if any) and the ADU account and instance Ids?

**Comment by jbiemar** [comment]
I will not write it here but I can give it to you by mail. Thank you

**Comment by jbiemar** [comment]
> @jbiemar Investigating the issue on our end

Do you have any idea ?

**Comment by eshashah-msft** [comment]
@jbiemar Please create a [Customer Support Ticket](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) so that we can continue the investigation which would allow you to share the account and instance info. 
Can you additionally see if the device appears in the default group or run the [device sync](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-check?tabs=portal) operation?
