### ISSUE TITLE
Cannot Install device update agent 1.0.3 beta version for Debian11 Arm64 on Debian 11.8 running on Raspberry Pi 4

### ISSUE THREAD

**Issue by DoLab-AI** [Azure/iot-hub-device-update#563]
## Expected Behavior
I am given a beta release of "deviceupdate-agent_1.0.3~beta_debian11_arm64.deb" for verifying. My platform is Raspberry Pi 4 running Debian 11.8 OS. When I try to install the .deb file, I received error suggesting there were un-resolved dependencies.

I am not familiar with  Azure ADU nor Debian so I am not sure whether I have missed something. I am appreciated if you could provide some details steps on how to proceed the installation.

## Steps to Reproduce 
I took the following steps by following the instructions in this Microsoft site (https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-provisioning) :
 
Provide a detailed set of steps to reproduce the bug.
•	Install Debian 11 (Bullseye) 64 bit on a SD card using Raspberry Imager 
 
•	Apply the latest OS updates
o	sudo apt update
        sudo apt -y full-upgrade
        sudo apt-get autoremove
        sudo apt-get clean
        sudo reboot

•	Install\Update ADU agents in Debian 11 environment

Following instructions here: https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-agent-provisioning#prerequisites:

  o	Prerequisites
      o	Install the repository configuration that matches your device’s operating system.
      curl https://packages.microsoft.com/config/debian/11/prod.list > ./microsoft-prod.list

o	Install the Microsoft GPG public key.
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/

o	Copy the generated list to the source.list.d directory.
sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/

o	Install IoT packages
curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
sudo apt install ./packages-microsoft-prod.deb

o	Install a container engine
sudo apt-get update; \sudo apt-get install moby-engine

o	Install the IoT Edge runtime
sudo apt-get update; \sudo apt-get install aziot-edge defender-iot-micro-agent-edge

o	Install deviceupdate agent
o	Sudo apt-get install ./ deviceupdate-agent_1.0.3~beta_debian11_arm64.deb

### Device Information
* Host OS: Debian 11.8 
* Architecture : Arm64 
* Provisioning Method:

## Logs
![image](https://github.com/Azure/iot-hub-device-update/assets/133031622/f347e74f-02d5-4931-820e-2fbdb1d9d9f6)

**Comment by eshashah-msft** [comment]
Investigation ongoing
