### ISSUE TITLE
Configuration file deviceupdate-agent.service is marked executable

### ISSUE THREAD

**Issue by Gunni** [Azure/iot-hub-device-update#566]
## Expected Behavior
`/lib/systemd/system/deviceupdate-agent.service` should not be marked executable.

## Current Behavior
`/lib/systemd/system/deviceupdate-agent.service` is marked executable.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install deviceupdate-agent 1.0.2
2. Observe `/lib/systemd/system/deviceupdate-agent.service` is marked executable
3. Execute `systemd daemon-reload`
4. Observe systemd warns: `Configuration file /lib/systemd/system/deviceupdate-agent.service is marked executable. Please remove executable permission bits. Proceeding anyway.`

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 20.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Provisioning Method: tpm
*DU Agent Version (run 'sudo -u adu /usr/bin/AducIotAgent -v'): 1.0.2

## Logs
Nov 06 10:17:53 xxx systemd[1]: Configuration file /lib/systemd/system/deviceupdate-agent.service is marked executable. Please remove executable permission bits. Proceeding anyway.

**Comment by jw-msft** [comment]
@yuvalg-MSFT Needs further investigation by tracking internally.

**Comment by jw-msft** [comment]
What was your method of installation? apt-get from packages.microsoft.com, apt-get of local .deb file, other?  Could you check your umask -S?

we not able to repro--seeing this on 20.04 for `ls -l /lib/systemd/system/deviceupdate-agent.service` after apt install of .deb pkg:
-rw-r--r--  1 root root   528 Oct 31 07:55  deviceupdate-agent.service

**Comment by Gunni** [comment]
Hey,

Here is a repro:

```Dockerfile
# syntax=docker/dockerfile:1
FROM ubuntu:20.04

# post-install script for deliveryoptimization-agent directly invokes
# systemctl rather than just using dh_systemd like a normal package,
# but that's another bug...
COPY <<EOF /usr/bin/systemctl
#!/bin/bash
exit 0
EOF

RUN <<EOF
    chmod +x /usr/bin/systemctl
    apt update
    apt install --no-install-recommends -y wget ca-certificates
    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
    apt update
    apt install --no-install-recommends -y deviceupdate-agent
    apt clean
EOF

CMD find / -name '*.service' -executable -ls

# 21992      4 -rw-r-xr--   1 root     root          528 Feb  4  2023 /usr/lib/systemd/system/deviceupdate-agent.service
#                    ^-- That's the problem
```

Just run it with `docker build -t asd . && docker run --rm -it asd` on a system with docker and docker buildkit enabled.

**Comment by shiyi-peng** [comment]
Hi @Gunni,
We have reproduced the issue with the device update agent in the Docker container, but as Jeff mentioned above, it does not occur in a virtual machine or on an RPi. May I ask about the necessity of running the device update agent in the Docker container? Is it for testing purposes?
Regarding the specific issue you’ve reported — the systemd warning about the executable permission bit on the deviceupdate-agent.service file — this is likely a result of how Docker handles file permissions and how systemd operates within a traditional Linux environment.
I suggest running our agent in a virtual machine or on a physical device's OS as a possible solution.

**Comment by Gunni** [comment]
The dockerfile above is only a demonstration of the issue we have on our ubuntu machines.

When we install your package the .service file is marked executable. It should not.

I even demonstrated extracting the package to show that the file inside the package contains a service file with the executable flag set.

Please reopen as this is not solved.

**Comment by Gunni** [comment]
This service file is still the only executable service file on our edge devices.

```
     7711      1 -rw-r-xr--   1 root     root          528 Jan  1  1970 /usr/lib/systemd/system/deviceupdate-agent.service
```

This ticket should be reopened
