### ISSUE TITLE
The packages deployed through device update are not reflecting in the device hosted on ubuntu 22.04

### ISSUE THREAD

**Issue by pavankpatil-bh** [Azure/iot-hub-device-update#607]
[du-logs.zip](https://github.com/Azure/iot-hub-device-update/files/14368738/du-logs.zip)
we were able to install dnsutils package in ubuntu 22.04 but when we uninstall the package and try to install again through du, the package is not reflecting although the meta data in module twin is getting updated- with the manifest files.

**Comment by jw-msft** [comment]
Could you provide the following?
- 1.0.4-aziot-edge-apt-manifest.json (url to it is not included in logs)
- twin json

Could you provide details on what it's trying to do?
It seems like updating aziot-edge package?

**Comment by jw-msft** [comment]
@pavankpatil-bh Closing for now. If you could provide the requested info, then feel free to reopen. Thanks!
