### ISSUE TITLE
Device reporting new Contract Name & ContractId after device update and stays inProgress in ADU

### ISSUE THREAD

**Issue by Undermyspell** [Azure/iot-hub-device-update#611]
Hi there! I discovered a problem when updating a device concerning the reported states
What i did was and update on a device which gets the Adu agent version upgraded from 1.0.2 to 1.1.0 and the contractModelId from v2 to v3 during the update. This caused some strange behaviour in ADU, which i describe in the following.

I have a device with adu agent 1.0.2 installed and the agent module twin reports the following
```json
"deviceUpdate": {
                "__t": "c",
                "agent": {
                    "deviceProperties": {
                        "manufacturer": "mymanufacturer",
                        "model": "mymodel",
                        "compatibilityid": "2",
                        "contractModelId": "dtmi:azure:iot:deviceUpdateContractModel;2",
                        "aduVer": "DU;agent/1.0.2",
                        "doVer": "DU;lib/v1.1.0+20230907.214407.d71ade6,DU;agent/v1.1.0+20230907.214407.d71ade6"
                    },
                    "compatPropertyNames": "manufacturer,model,compatibilityid"
                }
            },
```

1. Then i rolled out an update to my ADU Group targeting exactly these properties.
2. ADU then creates a deployment for the respective device class targeting contract model id v2
3. The device is inProgress and installs the update, after some time the device reports the following 
```json
 "deviceUpdate": {
                "__t": "c",
                "agent": {
                    "deviceProperties": {
                        "manufacturer": "mymanufacturer",
                        "model": "mymodel",
                        "compatibilityid": "2",
                        "contractModelId": "dtmi:azure:iot:deviceUpdateContractModel;3",
                        "aduVer": "DU;agent/1.1.0",
                        "doVer": "DU;lib/v1.1.0+20230907.214407.d71ade6,DU;agent/v1.1.0+20230907.214407.d71ade6"
                    },
                    "compatPropertyNames": "manufacturer,model,compatibilityid",
                    "lastInstallResult": {
                        "resultCode": 400,
                        "extendedResultCode": 0,
                        "resultDetails": ""
                    },
                    "state": 6,
                    "workflow": {
                        "action": 3,
                        "id": "ac30b972-bf3d-460c-8892-b6a420de4927"
                    }
                },
```
As one can see the contractModelId got upgraded to v3 and also the adu agent version to 1.1.0 (which is part of the update on purpose)

The problem is that the device is stuck inProgress in the Deployment targeting contractModelId v2.

In the background, ADU created another deviceclass targeting contractModelId v3.

When i now do a re-deploy of the same update ADU creates 2 deployments, one for each contract version (v2 and v3). After that the device gets an immediate succes report inside the deployment targeting contractModelId v3.

![image](https://github.com/Azure/iot-hub-device-update/assets/19801112/a1d7aae5-1c1f-4e3d-8566-0e3a4cd386d0)

The problem is that i have to manually re-deploy the update to get my device to a success state.

## Expected Behavior
After the device reported success and the updated Contract Name and ContractId (with v3) the status and the device should be moved to the new deviceclass (targeting compatibility with contract v3) automatically instead of having the need to re-deploy the same update

## Current Behavior
Device gets Stuck in initial Deviceclass deployment targeting a previous contractModelId Version when contractModelId Version gets upgraded during update

**Comment by josephmsft** [comment]
What is your ADU account and instance?

**Comment by Undermyspell** [comment]
@josephmsft 

ADU Instance Id: 
/subscriptions/a82e69c4-87d9-40cf-ad3c-b894bb1dccdb/resourceGroups/omnect-cp-westeurope-dev-rg/providers/Microsoft.DeviceUpdate/accounts/omnect-cp-dev-adu/instances/omnect-cp-dev-instance

ADU Hostname: 
omnect-cp-dev-adu.api.adu.microsoft.com

**Comment by xinanqiu** [comment]
@Undermyspell do you use reference agent? If yes, could you please repro the issue and then share client logs?

**Comment by Undermyspell** [comment]
@xinanqiu We use the device update agent, as i described the initial version on the device is 1.0.2 and then i rolled out an update which updated the agent to 1.1.0 and the device then reports a contract version 3 as opposed to the initial version 2. The effect is that the initial deployment gets never out of "InProgress" for that device, because it targets contract version 2 which the device is not reporting anymore. To me this seems to be a problem i adu how it handles such implicit contract version upgrades during an upgrade. Hence i do not think that evaluating device logs i effective in this case

**Comment by eshashah-msft** [comment]
@

**Comment by Undermyspell** [comment]
@eshashah-msft Is there any update to this?

**Comment by xinanqiu** [comment]
@Undermyspell The service fix has been released.  Do you still repro the issue? If yes, could you please share client log?

**Comment by eshashah-msft** [comment]
Thanks for the update @Undermyspell
