### ISSUE TITLE
A/B Update Erases ADU Configuration on Yocto Kirkstone Raspberry Pi 4 - 64 bit Example

### ISSUE THREAD

**Issue by smithsonarrey-chevron** [Azure/iot-hub-device-update#614]
## Expected Behavior
A/B Update is performed using example-a-b-update.sh. The raspberrypi4-64 should boot from partition b without modifying other partitions

## Current Behavior
The /adu folder (partition) was over written after OS update was completed. As the result, all the files (including the du-config.json file that used for ADU communication) had gone. Because of missing the du-config.json, ADU was not able to communicate with the host after OS installation was completed (and rebooted). In addition, the ownership of /adu folder has changed from adu:adu to root:adu after OS installation was completed.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Build an adu update image targeting raspberrypi4-64
2. Configure ADU Agent and Cloud Device
3. Perform A/B update

### Device Information
* Hardware Model: Raspberry Pi
* Host OS: Yocto Poky Kirkstone (4.0.16) 
* Architecture: arm64

## Suggested Solution
Include an fstab file for the raspberrypi4-64

![image](https://github.com/Azure/iot-hub-device-update/assets/108370879/d4a7401b-dc30-4de2-b77d-06ffa61be85a)

**Comment by Nox-MSFT** [comment]
@smithsonarrey-chevron , can you share how you package the .swu file please? In older example, we've never update /adu folder.
I just want to make sure that this is not something that caused by your .swu file.
