### ISSUE TITLE
A/B Update Fails on Yocto Kirkstone Raspberry Pi 4 - 64 bit Example do to invalid update image

### ISSUE THREAD

**Issue by smithsonarrey-chevron** [Azure/iot-hub-device-update#615]
## Expected Behavior
A/B Update is performed using example-a-b-update.sh. The raspberrypi4-64 should boot from partition b without modifying other partitions

## Current Behavior
SWUpdate Handler rejects the update image, claiming that it is invalid

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Build an adu update image targeting raspberrypi4-64
2. Configure ADU Agent and Cloud Device
3. Perform A/B update

### Device Information
* Hardware Model: Raspberry Pi
* Host OS: Yocto Poky Kirkstone (4.0.16)
* Architecture: arm64

## Suggested Solution
modify the sw-description file for the raspberrypi4-64 to specify compatibility for the raspberrypi4-64 rather than the raspberrypi4

![image](https://github.com/Azure/iot-hub-device-update/assets/108370879/b280fded-cca3-4084-98ee-1f6c5d430d65)

**Comment by Nox-MSFT** [comment]
Thanks @smithsonarrey-chevron , our team will investigate this issue.
