### ISSUE TITLE
Unable to use additional compatibility information

### ISSUE THREAD

**Issue by damianvandoom** [Azure/iot-hub-device-update#639]
I am using Azure IoT Update, the MS Tutorial Simulator, and I can successfully send updates to my Linux device. 

I am now expanding on learning the update process by adding additional compatibility information to both the manifest file and the du-config.json file.  

When I add compatibility key/value pair into both the manifest and du-config file, the update isn't recognised as valid against the group with my device in. When I remove the compatibility information from the du-config file, my group does match a different manifest without the additional compatibility information. 
(I have two updates pending, one with the additional compatibility information in, one without)

How do I utilise additional [compatibility information](https://learn.microsoft.com/en-gb/azure/iot-hub-device-update/device-update-configuration-file#list-of-fields) in Azure IoT Update?

**Manifest File**

Notice the "a": "a"
```

    {
    	"updateId": {
    		"provider": "Contoso",
    		"name": "Yocto-Image",
    		"version": "1.7"
    	},
    	"isDeployable": true,
    	"compatibility": [
    		{
    			"deviceModel": "Video",
    			"deviceManufacturer": "contoso",
    			"a": "a"
    		}
    	],
    	"instructions": {
    		"steps": [
    			{
    				"type": "inline",
    				"description": "Update the device image to version 0.8.0003.0",
    				"handler": "microsoft/swupdate:1",
    				"files": [
    					"adu-update-image-raspberrypi3.swu"
    				],
    				"handlerProperties": {
    					"installedCriteria": "0.8.0003.0"
    				}
    			}
    		]
    	},
    	"files": [
    		{
    			"filename": "adu-update-image-raspberrypi3.swu",
    			"sizeInBytes": 112739328,
    			"hashes": {
    				"sha256": "wPdNKUSmWTZkR6Pum9oR/EIzdn5AvON4dsXME+/gHVw="
    			}
    		}
    	],
    	"createdDateTime": "2022-02-02T06:56:51.2002204Z",
    	"manifestVersion": "4.0"
    }

```

**du config**
```

    {
    	"schemaVersion": "1.1",
    	"aduShellTrustedUsers": [
    		"adu",
    		"do"
    	],
    	"iotHubProtocol": "mqtt",
    	"compatPropertyNames": "manufacturer,model,a",
    	"manufacturer": "Contoso",
    	"model": "Video",
    	"agents": [
    		{
    			"name": "aduagent",
    			"runas": "adu",
    			"connectionSource": {
    				"connectionType": "string",
    				"connectionData": "HostName=xxx.azure-devices.net;DeviceId=xxx;SharedAccessKey=xxx="
    			},
    			"manufacturer": "Contoso",
    			"model": "Video",
    			"additionalDeviceProperties": {
    				"a": "a"
    			}
    		}
    	]
    }

```

Device in Group showing the correct compatibility attributes

![image](https://github.com/Azure/iot-hub-device-update/assets/26007462/3a5c34f7-f946-4d97-82f4-5e466d9206fc)

Update showing correct compatibility attributes

![image](https://github.com/Azure/iot-hub-device-update/assets/26007462/db0999af-58d7-46b7-88fd-45159591e32a)

Not showing an update

![image](https://github.com/Azure/iot-hub-device-update/assets/26007462/e9e38f06-8e93-4c66-8452-666edf9f2c53)

## Expected Behavior
Because the du config file and the manifest file both share the same compatibility information, I expect that the IoT update portal should recognise the update. 

## Current Behavior
The group does not recognise the update

### Device Information
* Host OS Ubuntu 18.04

* Provisioning Method:
*DU Agent Version 1.0.2

**Comment by josephmsft** [comment]
I'll take a look

**Comment by josephmsft** [comment]
@damianvandoom could you share your deviceId and the rough date when this issue occurred? I can look at service logs to see if I can find any errors.

**Comment by josephmsft** [comment]
@damianvandoom Can you some information to help me investigate your issue? What region is your IoT Hub in? What's the name of the ADU account you are using? And is the agent that hit this issue just named "aduagent"?

**Comment by damianvandoom** [comment]
My IOT Hub is in northeurope
Everything is defaulted per the tutorial. 
adu and aduagent. 

I have replicated the issue again just now. 25/06/2024 09:00 BST

The hub name ends in xxx-iot-overtheair-dev (the first letters are my company name, omitted)

**Comment by josephmsft** [comment]
It looks like there is a mismatch in our storage between what compat properties the device has and what is in the update.

In the update

"compatibility": [
    		{
    			"deviceModel": "Video",
    			"deviceManufacturer": "contoso",
    			"a": "a"
    		}
    	],

I would suggest you use "model" instead of "deviceModel" and "manufacturer" instead of "deviceManufacturer". For backwards compatibility we do an internal mapping here but for simplicity for your understanding an exact match is easier.

I could only find 1 agent "damo1" in your storage, but the compat properties it has are the following:

"compatPropertyNames": "manufacturer,model,a"
"deviceProperties": {
  "manufacturer": "Contoso",
  "model": "Videov1",
  "a": "a",
  <a few other properties that are not relevant>
}

The model value of "Videov1" does not match the update value of "Video"

**Comment by josephmsft** [comment]
I don't see any messages about failing to update the compat properties for the agent, but this mismatch is what is preventing that update from being compatible with that device.

**Comment by josephmsft** [comment]
I think you'll also want to use manifestVersion: "5.0" in the update

**Comment by damianvandoom** [comment]
@josephmsft thanks for taking a look. 

I was using the [MS article here](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-simulator) to set all this up, which links the following [manifest file](https://github.com/Azure/iot-hub-device-update/releases) in the latest Tutorial_Simulator.zip file. 

When I remove the "a": "a" from the deviceProperties, it does match the device, and I can perform the update, which is strange. This is why I left everything else 'as is'. 

I'll make the changes tomorrow when I'm back at work and update.

**Comment by damianvandoom** [comment]
I can confirm that making the changes has resolved my issue. 

May I suggest the Tutorial_Simulator.zip and the article are updated to align the configuration from the start?

Many thanks for your assistance @josephmsft

**Comment by josephmsft** [comment]
Sounds good, we'll follow-up on updating the documentation
