### ISSUE TITLE
Inconsistent Deployment status for device

### ISSUE THREAD

**Issue by Undermyspell** [Azure/iot-hub-device-update#642]
## Expected Behavior
I deployed an update to an adu group with one device in it. The update failed on the device (which i expected). Yet the status displayed in the Device Update Portal is somehow inconsistent. In the view of the deployment my device status is shown as failed (which i expect). In the group basics tab or when i click the device it is shown as InProgress. Why differ the deployment status ? I'd expect the status to be failed 

#### Deployment details page
![image](https://github.com/user-attachments/assets/c5fbe036-5e11-4fd2-82c7-731a77d3488c)

#### Clicked on the device (from deployment details page)
![image](https://github.com/user-attachments/assets/927dff25-3876-4b0a-b5f2-5032ff9ef981)

#### Group basics tab
![image](https://github.com/user-attachments/assets/6da5fcd1-9df5-4a85-9e3c-71f3117fb35d)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Deploy an update to an adu group
2. Let the update fail
3. Compare Deployment status in portal (see above)

## Additional Information
IoT hub: omnect-cp-dev-iot-hub.azure-devices.net
Device: pidown
Adu group: 6409dcebd8ce39ade510df46

Thanks in advance

**Comment by eshashah-msft** [comment]
@Undermyspell : Did the inconsistency persist? The status can take up to 5 mins to sync.

**Comment by eshashah-msft** [comment]
Hi, closing this issue due to no new activity. Please feel free to create a new issue if needed. Thanks!
