### ISSUE TITLE
Bug in ADUC_Logging_Init: log level not stored in global variable

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [Azure/iot-hub-device-update#647]
ADUC_Logging_Init doesn't set g_logLevel with the value from the logLevel parameter, but always set it to ADUC_LOG_INFO.

```
void ADUC_Logging_Init(ADUC_LOG_SEVERITY logLevel, const char* filePrefix)
{
    g_logLevel = ADUC_LOG_INFO;
```

This leads to update content handler extensions always getting ADUC_LOG_INFO as log level instead of the one e.g. set via command line: 

`*handler` = createUpdateContentHandlerExtensionFn(ADUC_Logging_GetLevel());

Same for download handlers:

```
auto plugin = std::unique_ptr<DownloadHandlerPlugin>(
            new DownloadHandlerPlugin(downloadHandlerFileEntity.TargetFilename, ADUC_Logging_GetLevel()));
```

Also, using std::make_unique might be a good idea in 2024.

**Comment by eshashah-msft** [comment]
Hi @D-r-P-3-p-p-3-r , Thanks for reporting this. We appreciate the feedback here. We will track this to be added to our next release of the product (service and agent). We will share more details here once we have a release date. 


Closing this as future improvement.
