### ISSUE TITLE
CheckDataDir()  checks ADUC_DATA_FOLDER instead of config->dataFolder

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [Azure/iot-hub-device-update#657]
CheckDataDir() checks ADUC_DATA_FOLDER even though it can be overwritten in du-config.json. It probably should check config->dataFolder.
This is painful when cross-compiling because you're stuck with the built-in path from ADUC_DATA_FOLDER now.
CheckDownloadsDir on the other hand does the right thing and checks config->downloadsFolder.

Btw: https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-configuration-file doesn't explain a bunch of the configuration options available for du-config.json (e.g. dataFolder, extensionsFolder, downloadsFolder).

**Comment by OscarLeeMSFT** [comment]
Hi,
Thank you for reporting the issue.
The team will take a look at this and respond further in the next day or two.

**Comment by eshashah-msft** [comment]
Hi @D-r-P-3-p-p-3-r, This is good feedback and we will track this for our next release of the product (service and agent). We will share more details here once we have a release date. Tracking this as future improvement.

For now, while this can be changed when building the agent code from scratch. 

We will address the documentation fixes and update here.

**Comment by eshashah-msft** [comment]
Closing this issue as completed with the documentation changes completed
