### ISSUE TITLE
Can't see ADU Group after tag Device

### ISSUE THREAD

**Issue by marcelo-luna** [Azure/iot-hub-device-update#662]
## Expected Behavior

I have an IoT Edge device tagged "ADUGroup : adugroup1":

![Image](https://github.com/user-attachments/assets/51b0af48-8093-41ee-9733-0812a3e2b287)

and I expect to see it under Update > Groups and Deployments, but as you can see below it's not showing

![Image](https://github.com/user-attachments/assets/5238b986-ff4a-41e6-9f3b-ae262ba96d6f)

## Troubleshooting

I followed the [Troubleshooting Guide](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/troubleshoot-device-update) and have already checked:

 ✅ Message routing: All the necessary routings are configured;
 ✅ Using DPS with symmetric key: I tagged the device after it was provisioned and connected with the IoT Hub.
 

### Device Information

* Host OS : Ubuntu 22.04.5 LTS WSL
* Architecture: amdx86_64
* Provisioning Method: DPS symmetric key
* DU Agent Version: 1.1.0 amd64

## Additional Information

IoT hub Tier: Standard
Device Update for IoT Hub: Free

**Comment by josephmsft** [comment]
Can you share the deviceId and what region you created your ADU account and instance in? I can try to search our logs for any failures for the last few days.

**Comment by marcelo-luna** [comment]
ADU region: West Europe
DeviceId:  https://privnote.com/A06ndQK8#x3xjQhUOh

**Comment by josephmsft** [comment]
Sorry I didn't get to this yesterday, but it appears after looking into the logs that this device was not reporting a valid modelId at the time the tag change was processed, and the event was rejected because the device was considered not ADU compliant. It appears at some point the modelId WAS added because the device was eventually created in storage. Can you try removing the tag and re-adding it?

**Comment by marcelo-luna** [comment]
No prob @josephmsft.

As I'm using the "AIS" connection type, I solved my problem by placing the tag inside the "IoTHubDeviceUpdate" Module Identity Twin instead of in the device twin.

Thank you for the support.
