### ISSUE TITLE
postrm Debian script mentions services that are not installed

### ISSUE THREAD

**Issue by AndreRicardo-Zoetis** [Azure/iot-hub-device-update#672]
```sh
# apt-get remove --yes "deviceupdate-agent"
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libcurl4-openssl-dev libgdbm-compat4 libperl5.36 perl-modules-5.36 python3-wheel
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  deviceupdate-agent
0 upgraded, 0 newly installed, 1 to remove and 16 not upgraded.
After this operation, 25.7 MB disk space will be freed.
(Reading database ... 53228 files and directories currently installed.)
Removing deviceupdate-agent (1.1.0) ...
******************** Running /var/lib/dpkg/info/deviceupdate-agent.postrm remove  ***********************
Remove 'adu' user from 'aziotid' group.
gpasswd: group 'aziotid' does not exist in /etc/group
Remove 'adu' user from 'aziotcs' group.
gpasswd: group 'aziotcs' does not exist in /etc/group
Remove 'adu' user from 'aziotks' group.
gpasswd: group 'aziotks' does not exist in /etc/group
Restart IoT Identity Services
Failed to restart aziot-certd.service: Unit aziot-certd.service not found.
Failed to restart aziot-tpmd.service: Unit aziot-tpmd.service not found.
Failed to restart aziot-keyd.service: Unit aziot-keyd.service not found.
Failed to restart aziot-identityd.service: Unit aziot-identityd.service not found.
Delete 'adu' user.
userdel: group adu not removed because it has other members.
Delete 'adu' group.
```

Notice the "Failed to restart" and "group 'aziotcs' does not exist in /etc/group" messages in postrm.

https://github.com/Azure/iot-hub-device-update/blob/18e98a95f5d77a608c2c224e50fe435814f4475b/packages/debian/postrm#L34C1-L52

None of these users or services are installed by the original deviceupdate-agent.

Shouldn't this code have the same checks as the `postinst` file?

https://github.com/Azure/iot-hub-device-update/blob/18e98a95f5d77a608c2c224e50fe435814f4475b/packages/debian/postinst#L240-L242

https://github.com/Azure/iot-hub-device-update/blob/18e98a95f5d77a608c2c224e50fe435814f4475b/packages/debian/postinst#L253C9-L253C45

**Comment by eshashah-msft** [comment]
@AndreRicardo-Zoetis Thanks for the feedback. We will track this for our next release of the product (service and agent). We will share more details here once we have a release date. Tracking this as future improvement. 
While ADU does not required IoT Identity services, the postrm script removes the adu user if it exists in the group but it can be improved with the above feedback.

**Comment by AndreRicardo-Zoetis** [comment]
PR to fix this: https://github.com/Azure/iot-hub-device-update/pull/703
