### ISSUE TITLE
Device taking time while OTA firmware download 

### ISSUE THREAD

**Issue by SS-iot-devoted** [Azure/iot-hub-device-update#72]
Hello friends working on a project in which I'm downloads firmware by OTA is taking near by 2 min. I think that id too long time for 420KB file .. other thing is Im testing the same thing with AWS in that case file is hust downloaded in ~33sec so Im looking for help like what can be issue or is there sockets configuration or else ???

**Comment by devlie** [comment]
Hi @SS-iot-devoted, how did you measure the 2-min download time? Is it from creating a deployment to binary getting downloaded, or is it from actual start of download to finishing? Thanks.
