### ISSUE TITLE
UpdatesClient in C# reporting no such host is known after 4 retries.

### ISSUE THREAD

**Issue by ScottyMac-dev** [Azure/iot-hub-device-update#75]
Currently I am using 1.0.0-beta.2 of Azure.IoT.DeviceUpdate.

I used app registration in Azure AD to create an application Id and secret for use with ADU. At first I went the route of creating a service client using the RESTful implementation of ADU in Azure. I then discovered that was a class model that could be used.

The call to the UpdatesClient GetProvidersAsync() succeeds but as soon as I attempt an await foreach(var provider in providers) I get the no such host is known error 4 times.

This is a blocking issue for the AED/AICS Secured Core Device Certification development process and we are supposed to have a version of ADU available in the AICS API by June 15th.

Thanks!

**Comment by ScottyMac-dev** [comment]
Yes, I am aware of how to create the credentials and I can execute the raw calls in the RESTful API. I have it prototyped in Postman, but here is a segment of my C# code:

                    var credentials = new ClientSecretCredential(appConfig.DpsOptions.TenantId, clientId, clientSecret);
                    updatesClient = new UpdatesClient(iotHubInstanceConfig.AduAccount, iotHubInstanceConfig.AduInstance, credentials);
                    devicesClient = new DevicesClient(iotHubInstanceConfig.AduAccount, iotHubInstanceConfig.AduInstance, credentials);
                    deploymentsClient = new DeploymentsClient(iotHubInstanceConfig.AduAccount, iotHubInstanceConfig.AduInstance, credentials);

The iotHubInstanceConfig is a configuration element that is both injected by DI and is managed by region changes. I have verified that the values that I am passing are correct and I can demonstrate thos same values work in a Postman call.

The Url for my adu instance API endpoint is https://aeddevtest.api.adu.microsoft.com/deviceupdate/vyper/v2/updates/providers

Thanks!

Scott McIntosh
C: (360) 739-2293
VTEAM LABS (LLC)
***@***.***D75DF3.DDF6BCD0]

**Comment by devlie** [comment]
Just to confirm, the value of `iotHubInstanceConfig.AduAccount` is `aeddevtest.api.adu.microsoft.com`?

**Comment by ScottyMac-dev** [comment]
Okay, sometimes it takes another set of eyes! My Postman prototype used a URL:

let aduHost = pm.environment.get("aduAccount");
let baseUrl = https:// + aduHost + ".api.adu.microsoft.com";

Your class model uses just the host name.

Thanks!

You can close this issue.

**Comment by devlie** [comment]
You're welcome, and thanks for trying ADU out!
