### ISSUE TITLE
Unable to see Azure Device Update Groups in IoT Hub

### ISSUE THREAD

**Issue by sihbher** [Azure/iot-hub-device-update#76]
I followed [this procedure](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-ubuntu-agent)  I manually prepared my VM

I added a tag for ADUGroup to my edge device in the Device Twin and in the  IoTHubDeviceUpdate module Twin (because it was not clear to me to which I had to):

'tags': {
        'ADUGroup': 'gerryTest'
    }

![image](https://user-images.githubusercontent.com/59939147/121949913-a5d75e00-cd1e-11eb-9bc7-cc7a77fda42d.png)

![image](https://user-images.githubusercontent.com/59939147/121949987-be477880-cd1e-11eb-838c-1c119bebc6dc.png)

When I try to create a Group in Device Updates - Groups the tag is not present, in fact NO TAGS are available in the drop down at all. 

![image](https://user-images.githubusercontent.com/59939147/121950185-ed5dea00-cd1e-11eb-9ee0-8045e0c8a440.png)

![image](https://user-images.githubusercontent.com/59939147/121950249-fe0e6000-cd1e-11eb-8a60-73c35c6dd4a1.png)

UPDATE: 
I tried using the "Deploy to Azure" Button and it worked!!, after I checked what was the difference, I noticed that the template used for creating the VM has these commands:

        apt install -y deviceupdate-agent
        apt install -y deliveryoptimization-plugin-apt
        systemctl restart adu-agent

I believe the trick is done by restart adu-agent before tag the device! that instruction is not referenced in the manually procedure, please confirm, if it is the case please add to the documentation

**Comment by cdbierl** [comment]
Using 0.8.0 release and connecting as module from my host, can't for the life of me get the ADUGroup tag to trigger any changes in the "Create Group" dropdown in IoTHub portal.

**Comment by jw-msft** [comment]
Yes, the agent needs to connect before setting the ADUGroup tag.
Can set ADUGroup to null in the twin and then restart via `sudo systemctl restart adu-agent` to resolve it.

Once you see it is connected in the twin, then add the ADUGroup tag.
Then you should be able to see the group available when adding a group.

@esha0611 Could you include this in relevant ms docs? I'll update the .md
