### ISSUE TITLE
Resource Limits Docs

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/iot-hub-device-update#77]
Currently getting the below error 

You have reached a limit on the number of different Providers, Names of Versions allowed in your instance of Device Update for IoT Hub. Delete some updates from your instance and try again.

Is a documentation around what are the limits with for ADU

**Comment by devlie** [comment]
@sourabhkrishna the current limit per ADU instance for public preview is:
- 5 providers per ADU instance
- 5 names per providers
- 25 versions per name

There is also a limit of 100 update versions cumulatively (across all providers and names).

These limits are not documented yet, and subject to change. Hope this helps.

**Comment by sourabhkrishna** [comment]
Thanks , this certainly helps.
