### ISSUE TITLE
Device keeps in progress state after IsInstalled succeeds

### ISSUE THREAD

**Issue by Voxel07** [Azure/iot-hub-device-update#78]
Quick Question:

Question 1:
Is it intended that the device stays in the "in progress" state even when the IsInstalled call succeeds ? I would set the state to succeeded, then I have a clear picture in the deployment overview. But before doing that, I would like to know if there is more to it. 
Edit: Is it correct that I had to report apply action and idle state to get the result that I want ? 
Edit2:
Question 2:
Why is the download URL Removed after the Download success is reported ? It would be handy if this entry stays in device twin. That way, it would be possible to redownload the file if it was lost in a reboot between download and install. 
I know that the current workflow doesn't support this, so the download URL is not needed anymore.

Thanks

**Comment by ValOlson** [comment]
Hi @Voxel07,

Thank you for your questions, please see our responses below-

1. For #1, you are correct the current flow for the download, install and apply phases is shown [here.](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-build-agent-code.md#steps). Any reason you need to skip the apply action?
2. For #2, removing Files after the download action is a way of clearing the file list for the next deployment without consuming an additional IoT hub messages from your IoT Hub message quota. Today we have done this after download is complete, as you have observed. Is it a common scenario for your IoT device set up where you need to redownload the file after a reboot?

**Comment by Voxel07** [comment]
Thanks for the Answer.

1. No, there is no reason to skip the apply step. But say for example, that the agent is running and for some reason the same update gets deployed again. Then there is no check in place to stop a new installation. That's the case I wanted to catch, maybe that's implemented in swUpdate, I don't know. 
2. It's not common or a planed workflow. I was just thinking of scenarios of what cold when go wrong. And if an Installation is interrupted, because the power to the device is cut for some reason, I can't do anything at the moment, but in my eye that's a scenario that the agent could recover from without human interaction. 
But saving the File or the download URL in nonvolatile memory is not an option at the moment. That's why I am asking.

**Comment by Voxel07** [comment]
Is it possible to get some information on when the backend service will ignore a reported state?

Like for e.g. when I report an Installed update when the deployment directly in the download phase. Then the device keeps the in progress state.
Or if download succeeded is reported twice, the second time the service won't send the install action. And the device is stuck in this state.

**Comment by esha0611** [comment]
Please refer to this document on the goal state deployment that Device Update uses in the after the public preview refresh release (Feb' 22): https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/goal-state-support.md
