### ISSUE TITLE
Rules for version number validation ?

### ISSUE THREAD

**Issue by NicolasRiou** [Azure/iot-hub-device-update#86]
Hello, 

I am having issues with importing a new device update. It seems that the version number is validated against some rules. We make rc versions of our updates and there version number lookis like X.Y.Z-rc which gives me this error : Cannot parse import manifest. (Error parsing version string: 0.0.1-rc. Path 'updateId.version', line 5, position 25.)

Are those rules specified somewhere ? I couldn't find them anywhere. 
Thanks for your help

**Comment by devlie** [comment]
@NicolasRiou, only numerical version number is supported. The rules are specified in our [import manifest schema](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/import-schema#updateid-object). Hope this helps.

**Comment by NicolasRiou** [comment]
It does help, thank you !
