### ISSUE TITLE
How to use a yocto image with Device Update Service for NVIDIA Xavier-NX arm64?

### ISSUE THREAD

**Issue by abhishekcodework** [Azure/iot-hub-device-update#92]
I have created a Yocto image for my nvidia xavier nx. It is an arm64 device. The steps for a manually update are available but how do I use the Device Update Service to push the updated image through the IoT Hub?

The following are steps for deploying the image manually:
1. The disk image package for Jetson has a name like devkit.tegraflash.tar.gz.
2. This file can be used along with recovery mode on the Jetson to initially provision the device. You should insert an SDCard into the device before flashing.
3. To enter recovery mode(instructions for jetson):
4. For the Jetson carrier board, unless you have connected buttons to the header pins, use a jumper (REC to GND) to put the device into recovery mode on power up.
5. Connect the USB cable to power on the Jetson. You should see your NVIDIA device listed in the lsusb device output.
6. Extract the .tar.gz file and then run the ./doflash.sh script inside to flash the build to the device.

**Comment by ValOlson** [comment]
Hi @abhishekcodework,

The steps for deploying an image through IoT Hub are described [here](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-raspberry-pi). Try these and if you are stuck please share details of which step and any agent logs for us to help troubleshoot.

Thank you!
