### ISSUE TITLE
Module Support in Management APIs

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/iot-hub-device-update#93]
Management APIs do not support the ModulesClient just the way we have DevicesClient. 
If I setup ADU as Module Identity then the parent device isnt being fetched in the GetDevice method of DevicesClient.

**Comment by ValOlson** [comment]
You will need to pass “{deviceId}{space}{moduleId}” as device id for the API to return the modules. 
 
In our public preview refresh APIs we will have dedicated parameters for modules so it would look something like below: 
        accounts/{account}/instances/{instance}/management/devices/{deviceId}
        accounts/{account}/instances/{instance}/management/devices/{deviceId}/modules/{moduleId}
