### ISSUE TITLE
Error from package update: "The installed criteria is not met. The current update was not installed on the device"

### ISSUE THREAD

**Issue by mlagridigital** [Azure/iot-hub-device-update#94]
Hi,
I am trying to do a package update by installing a Debian package for the first time.
I can see in the logs that the error is "The installed criteria is not met. The current update was not installed on the device".
Does anyone know how I can resolve this error?

Manifest used:
```
{
    "name": "mycompany-iot-firmware",
    "version": "1.0.0",
    "packages": [
        {
            "name": "mycompany-iot-firmware",
            "version": "1.0.0"
        }
    ],
	"updateId": {
		"provider": "mycompany",
		"name": "mycompany-iot-firmware",
		"version": "1.0.0"
	},
	"updateType": "microsoft/apt:1",
	"installedCriteria": "mycompany-iot-firmware-1.0.0",
	"compatibility": [{
			"deviceManufacturer": "Sony",
			"deviceModel": "RaspberryPi4B"
		}
	],
	"files": [{
			"filename": "mycompany-iot-firmware.deb",
			"sizeInBytes": 20711084,
			"hashes": {
				"sha256": "Gtft/bPVfs9KmFrI+QK4o40YNpeMJFhqFqVjdBi5a6k="
			}
		}
	],
	"createdDateTime": "2021-10-25T06:16:43.2847417Z",
	"manifestVersion": "2.0"
}

```

Logs from **adu-agent**
```
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6854Z [I] Perform startup tasks. [ADUC_Workflow_HandleStartupWorkflowData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6855Z [I] Calling IsInstalledCallback to check if content is installed. [ADUC_MethodCall_IsInstalled]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6855Z [I] IsInstalledCallback called [IsInstalledCallback]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6855Z [I] IsInstalled called workflowId: , installed criteria: mycompany-iot-firmware-1.0.0 [IsInstalled]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6856Z [I] microsoft_apt_CreateFunc called. [microsoft_apt_CreateFunc]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6857Z [I] Evaluating installedCriteria mycompany-iot-firmware-1.0.0 [GetIsInstalled]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6857Z [I] The installed criteria is not met. The current update was not installed on the device. [ADUC_Workflow_HandleStartupWorkflowData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6858Z [I] Setting UpdateState to Idle [ADUC_SetUpdateStateHelper]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6858Z [I] Reporting state: 0, Idle (0); HTTP 200; result 1, 0 [AzureDeviceUpdateCoreInterface_ReportStateAndResultAsync]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6859Z [I] UpdateAction: Idle. WorkflowId: 211103060005 [ADUC_MethodCall_Idle]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6860Z [I] Calling IdleCallback [ADUC_MethodCall_Idle]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6860Z [I] Now idle. workflowId: 211103060005 [Idle]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6861Z [I] OrchestratorPropertyUpdateCallback ended [OrchestratorUpdateCallback]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6862Z [I] Processing existing Device Twin data after agent started. [ADUC_PnPDeviceTwin_Callback]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6862Z [D] Notifies components that all callback are subscribed. [ADUC_PnPDeviceTwin_Callback]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6862Z [I] DeviceInformation component is ready - reporting properties [DeviceInfoInterface_Connected]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6864Z [I] Property manufacturer changed to Sony [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6866Z [I] Property model changed to RaspberryPi4B [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6866Z [I] Property osName changed to Linux [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6867Z [I] Property swVersion changed to 5.10.17-v7l- [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.6868Z [I] Property processorArchitecture changed to armv7l [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.7079Z [I] Property processorManufacturer changed to ARM [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.7081Z [I] Property totalMemory changed to 3817356 [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: 2021-11-03T06:00:05.7082Z [I] Property totalStorage changed to 2344700 [RefreshDeviceInfoInterfaceData]
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: -> 17:00:05 SUBSCRIBE | PACKET_ID: 4 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: <- 17:00:05 SUBACK | PACKET_ID: 4 | RETURN_CODE: 0
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: -> 17:00:06 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=5 | PAYLOAD_LEN: 99
Nov 03 17:00:06 raspberrypi AducIotAgent[2906]: -> 17:00:06 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=6 | PAYLOAD_LEN: 3224
^C
```

**Comment by chrisjlin** [comment]
Hello, it appears you are attempting to import a .deb file directly to the Device Update service, then deploy it to your device. This is the workflow we support for **image-based** updating, but our **package-based** update flow is slightly different.

Package-based updating requires the user to first host the .deb package on a Linux package repository that is part of their on-device package manager's sources list. Then the user should import an **APT manifest** file to the Device Update service, **not the .deb package itself**. When a package-based update is deployed to a device, the APT manifest file is downloaded onto the device and the APT handler uses this to then get the .deb package from the appropriate repository and install it.

If the user desires to import and deploy a .deb package directly using the DU service (without hosting the package on a Linux package repository), then the user must also create their own on-device handler to install the package, and change the "updateType" field in their import manifest accordingly.

Additional information about the Import step and the package-based updating workflow can be found here: [Introduction to Device Update for Azure IoT Hub | Microsoft Docs](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/understand-device-update#importing). For an example of an APT manifest file, see [here](https://github.com/Azure/iot-hub-device-update/releases/download/0.7.0/Edge.package.update.samples.1.zip).

**Comment by mlagridigital** [comment]
Hi @chrisjlin , thank you for reply. You have confirmed for me that the idea of Device Update I had in mind isn't how Azure's DU works.

I question Azure's design for doing updates using APT packages. 
In Import Update screen, you ask for a manifest file, a collection of files to include in the update and a Storage Account directory. Importing this update actually gives Azure everything that it needs to install an update on the device.
So, why would you still require your users to host the .deb package on a Linux package repository first?

![image](https://user-images.githubusercontent.com/42328088/140217692-addaf197-32c2-47c0-b3bf-b8d50a5da906.png)

**Comment by esha0611** [comment]
@mlagridigital Thanks for the feedback! We have updated our import process with our Public Preview refresh release to make it easier to upload import manifest and files. Please take a look at the updated docs here. [Device Update apt manifest](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-apt-manifest)
Currently, Device Update delivers package-based updates from existing Debian repositories and does not have its own built-in Debian repository. Customers could choose to deploy their own Debian repository (i.e. [Debian repo setup](https://wiki.debian.org/DebianRepository/Setup)).

We are evaluating built-in Debian repository support for a future release of Device Update.
