### ISSUE TITLE
Setting up Device Update agent with IoTedge 1.1 for arm64 Xavier NX

### ISSUE THREAD

**Issue by abhishekcodework** [Azure/iot-hub-device-update#95]
I am using iotdge 1.1 on my linux edge device. The documentation mentions using aziot 1.2. How can I set up the agent using iotedge 1.1 since it uses config.yaml and not config.toml

**Comment by abhishekcodework** [comment]
My device is an arm64 Xavier NX. The tutorials are available for amd64 devices. sudo apt-get install device-update agent gives unable to locate package error.

**Comment by esha0611** [comment]
@abhishekcodework, the package name is deviceupdate-agent. The command sudo apt-get install deviceupdate-agent should work as expected for arm64. If there is need of additional information, please feel free to create a new issue!
